Repository EFForg/https-everywhere, pull requests merged in 2018-10, with the labels that each got.

#16646 Add Uclibc-ng.org.xml
  src/chrome/content/rules/Uclibc-ng.org.xml
Labels: new-ruleset

#16594 Create ruanyifeng.com.xml
  src/chrome/content/rules/ruanyifeng.com.xml
Labels: top-10k

#16672 Add ruleset for 7-zip.org
  src/chrome/content/rules/7-Zip.org.xml
Labels: top-10k

#16668 Update ruleset: CNN.com
  src/chrome/content/rules/CNN.com.xml
Labels: top-1k

#15734 [Verisign.co.jp] Separate ruleset
  src/chrome/content/rules/Verisign.co.jp.xml
Labels: ruleset-enhancement

#16169 [Avis.fr] New ruleset
  src/chrome/content/rules/Avis.fr.xml
Labels: new-ruleset, top-1m

#16167 [Avis.es] New ruleset
  src/chrome/content/rules/Avis.es.xml
Labels: new-ruleset, top-1m

#15736 [Verisign-Inc.com] Separate ruleset
  src/chrome/content/rules/Verisign-Inc.com.xml
Labels: ruleset-enhancement

#16313 [Thrifty.co.uk] New ruleset
  src/chrome/content/rules/Thrifty.co.uk.xml
Labels: new-ruleset

#16132 [Avis.com] Add subdomains
  src/chrome/content/rules/Avis.com.xml
Labels: top-10k

#16255 [Budget.com.ar] New ruleset
  src/chrome/content/rules/Budget.com.ar.xml
Labels: new-ruleset

#16002 [Retravision.com.au] New ruleset
  src/chrome/content/rules/Retravision.com.au.xml
Labels: new-ruleset

#16257 [Budget.com.br] New ruleset
  src/chrome/content/rules/Budget.com.br.xml
Labels: new-ruleset

#16645 Create Nuitka.net.xml, fix #16635
  src/chrome/content/rules/Nuitka.net.xml
Labels: top-1m

#16687 Create Jarir.com.xml
  src/chrome/content/rules/Jarir.com.xml
Labels: top-10k

#16678 Update VOA_Chinese.com.xml
  src/chrome/content/rules/VOA_Chinese.com.xml
Labels: top-100k

#16571 Update MeiPian.xml
  src/chrome/content/rules/MeiPian.xml
Labels: top-100k

#16623 Remove platform="mixedcontent" in Way2Allah.com.xml
  src/chrome/content/rules/Way2Allah.com.xml
Labels: top-100k

#16626 Create StreamVI.com.xml
  src/chrome/content/rules/StreamVI.com.xml
Labels: top-100k

#16413 Create CitizensForEthics.org.xml
  src/chrome/content/rules/CitizensForEthics.org.xml
Labels: top-1m

#16628 Update Jobvite.xml
  src/chrome/content/rules/Jobvite.xml
Labels: ruleset-bug, top-10k

#16700 Update ruleset: PortableApps.com
  src/chrome/content/rules/PortableApps.com.xml
Labels: top-100k

#16365 Ruleset for www.nic.cl
  src/chrome/content/rules/nicchile.xml
Labels: new-ruleset, top-100k

#16575 Add Tinc-vpn.org.xml
  src/chrome/content/rules/Tinc-vpn.org.xml
Labels: new-ruleset

#16728 Update Rust-Lang.org.xml
  src/chrome/content/rules/Rust-Lang.org.xml
Labels: top-100k

#16722 [PHP.xml] two subdomains now support HSTS
  src/chrome/content/rules/PHP.xml
Labels: top-10k

#16718 Add ruleset for openldap.org
  src/chrome/content/rules/OpenLDAP.org.xml
Labels: top-1m

#16712 Create FlatKill.org.xml
  src/chrome/content/rules/FlatKill.org.xml
Labels: top-100k

#16727 Update Perl.org.xml
  src/chrome/content/rules/Perl.org.xml
Labels: top-100k

#16723 Update HKEdCity.xml
  src/chrome/content/rules/HKEdCity.xml
Labels: top-100k

#16666 Update ruleset: The Conversation
  src/chrome/content/rules/The-Conversation.xml
  src/chrome/content/rules/The_Conversation.xml
Labels: top-10k

#15811 Create ruleset: Icecast.org
  src/chrome/content/rules/Icecast.org.xml
Labels: top-1m

#15710 Create ruleset: OceaniaCruises.com
  src/chrome/content/rules/OceaniaCruises.com.xml
Labels: top-1m

#16736 Update JoinMastodon.org.xml
  src/chrome/content/rules/JoinMastodon.org.xml
Labels: top-1m

#15472 Create IslamSyria.com.xml
  src/chrome/content/rules/IslamSyria.com.xml
Labels: top-1m

#15698 Create ruleset; KevinAThompson.com
  src/chrome/content/rules/KevinAThompson.com.xml
Labels: top-1m

#16680 Create Bridges-Foundation.org.xml
  src/chrome/content/rules/Bridges-Foundation.org.xml
Labels: top-1m

#16729 Update W3C.xml
  src/chrome/content/rules/W3C.xml
Labels: top-10k

#16717 Create NYMag.com.xml
  src/chrome/content/rules/NYMag.com.xml
Labels: top-10k

#16682 Create Islamic-Awareness.org.xml
  src/chrome/content/rules/Islamic-Awareness.org.xml
Labels: top-1m

#15233 Create Bayyinah.com.xml [top-1m]
  src/chrome/content/rules/Bayyinah.com.xml
Labels: top-1m

#15783 Update Verizon rulesets
  src/chrome/content/rules/Verizon-Enterprise.xml
  src/chrome/content/rules/Verizon-Wireless.xml
  src/chrome/content/rules/Verizon.xml
  src/chrome/content/rules/Verizon_Enterprise.xml
  src/chrome/content/rules/Verizon_Wireless.xml
  utils/ruleset-whitelist.csv
Labels: top-1k

#14400 [Ensighten.com] Remove wildcard
  src/chrome/content/rules/Ensighten.com.xml
  src/chrome/content/rules/Ensighten.xml
Labels: top-1m

#16083 [Avios.com] New ruleset
  src/chrome/content/rules/Avios.com.xml
Labels: top-100k

#16008 [MEPS FPX.com.my] New ruleset
  src/chrome/content/rules/MEPS-FPX.com.my.xml
Labels: top-100k

#16602 Add ruleset for sw-ka.de
  src/chrome/content/rules/Sw-KA.de.xml
Labels: top-1m

#16598 Add ruleset for poal.me
  src/chrome/content/rules/Poal.me.xml
Labels: top-1m

#15740 [Geekbuying.com] New ruleset
  src/chrome/content/rules/Geekbuying.com.xml
Labels: top-10k

#11924 add rule for Volantix.com:
  src/chrome/content/rules/Insnw.net.xml
  src/chrome/content/rules/Instart_Logic.com.xml
  src/chrome/content/rules/Volantix.com.xml
Labels: new-ruleset

#15657 Create ruleset: CityNews.ca
  src/chrome/content/rules/CityNews.ca.xml
Labels: new-ruleset, top-100k

#16070 Added ruleset for iksr.org
  src/chrome/content/rules/IKSR.org.xml
Labels: new-ruleset

#16434 Update ruleset: Handelsblatt
  src/chrome/content/rules/Handelsblatt.xml
Labels: ruleset-enhancement, top-10k

#15418 Create ruleset: ChemSpider.com
  src/chrome/content/rules/ChemSpider.com.xml
  src/chrome/content/rules/Royal-Society-of-Chemistry-mismatches.xml
  src/chrome/content/rules/Royal-Society-of-Chemistry.xml
Labels: top-10k

#16601 Add ruleset for deutsche-finanzagentur.de
  src/chrome/content/rules/Deutsche-Finanzagentur.de.xml
Labels: new-ruleset

#15545 Create ruleset: FamousFolks.ca
  src/chrome/content/rules/FamousFolks.ca.xml
Labels: new-ruleset

#15300 [OFX.com] New ruleset
  src/chrome/content/rules/OFX.com.xml
Labels: new-ruleset, top-100k

#16118 [Invaluable.com] New ruleset
  src/chrome/content/rules/Invaluable.com.xml
Labels: new-ruleset, top-100k

#16596 Add ruleset for Bnotk.de
  src/chrome/content/rules/Bnotk.de.xml
Labels: new-ruleset

#15950 Added ruleset for zkm.de
  src/chrome/content/rules/ZKM.de.xml
Labels: top-1m

#16068 Added ruleset for karlsruhe.de
  src/chrome/content/rules/Karlsruhe.de.xml
Labels: top-1m

#15577 Added ruleset for bibb.de
  src/chrome/content/rules/BIBB.de.xml
Labels: new-ruleset, top-1m

#16410 Create AlTafsir.com.xml
  src/chrome/content/rules/AlTafsir.com.xml
Labels: new-ruleset, top-1m

#16401 Create Azahera.net.xml
  src/chrome/content/rules/Azahera.net.xml
Labels: new-ruleset, top-1m

#16685 Create Taimiah.org.xml
  src/chrome/content/rules/Taimiah.org.xml
Labels: new-ruleset, top-1m

#14419 add rule for Interia.pl
  src/chrome/content/rules/Interia.pl.xml
Labels: new-ruleset

#16795 Remove Adobe_forms_central.com.xml, gone from DNS
  src/chrome/content/rules/Adobe.xml
  src/chrome/content/rules/Adobe_forms_central.com.xml
Labels: top-100

#16937 Create MathematiquesFaciles.com.xml
  src/chrome/content/rules/MathematiquesFaciles.com.xml
Labels: top-100k

#16936 Create MesExercices.com.xml
  src/chrome/content/rules/MesExercices.com.xml
Labels: top-1m

#16931 Create NLFacile.com.xml
  src/chrome/content/rules/NLFacile.com.xml
Labels: top-1m

#16935 Create Italien-Facile.com.xml
  src/chrome/content/rules/Italien-Facile.com.xml
Labels: top-100k

#16934 Create AllemandFacile.com.xml
  src/chrome/content/rules/AllemandFacile.com.xml
Labels: top-1m

#16933 Create FrancaisFacile.com.xml
  src/chrome/content/rules/FrancaisFacile.com.xml
Labels: top-10k

#16823 Re-activate Vodafone.xml
  src/chrome/content/rules/Vodafone.xml
Labels: top-100k

#16441 Update UDN.xml
  src/chrome/content/rules/UDN.xml
Labels: top-1k

#16952 Rename and Update American_Airlines.xml
  src/chrome/content/rules/AA.xml
  src/chrome/content/rules/American_Airlines.xml
Labels: top-10k

#16949 add more subdomains for Simpli.fi
  src/chrome/content/rules/Simpli.fi.xml
Labels: top-100k

#14559 Create SixthTone.com.xml
  src/chrome/content/rules/SixthTone.com.xml
Labels: top-1m

#16956 Create lczero.org.xml
  src/chrome/content/rules/lczero.org.xml
Labels: top-1m

#16978 Update Jammerbugt.dk to enforce HTTPS on the main domains and maps subdomain
  src/chrome/content/rules/Jammerbugt.dk-mixedcontent.xml
  src/chrome/content/rules/Jammerbugt.dk.xml
Labels: top-1m

#15873 Add dev-www.libreoffice.org
  src/chrome/content/rules/LibreOffice.org.xml
Labels: top-10k

#12782 [info.gov.hk] New ruleset
  src/chrome/content/rules/GovHK.xml
  src/chrome/content/rules/info.gov.hk.xml
Labels: top-100k

#14840 SZ:
  src/chrome/content/rules/Suddeutsche_Zeitung.xml
Labels: ruleset-bug, top-10k

#16975 Update Boligportal.dk to enforce HTTPS on main domains.
  src/chrome/content/rules/Boligportal.dk-mixedcontent.xml
  src/chrome/content/rules/Boligportal.dk.xml
Labels: top-100k

#15818 add rule Aftenbladet.no
  src/chrome/content/rules/Aftenbladet.no.xml
Labels: top-100k

#16977 Update CopenhagenMarathon.dk to enforce HTTPS on the maps subdomain
  src/chrome/content/rules/Copenhagenmarathon.dk-falsemixed.xml
  src/chrome/content/rules/Copenhagenmarathon.dk.xml
Labels: ruleset-enhancement

#16315 [Thrifty.com.au] New ruleset
  src/chrome/content/rules/Thrifty.com.au.xml
Labels: top-1m

#16972 Add ruleset for Aarhus University.
  src/chrome/content/rules/Au.dk.xml
Labels: top-100k

#16308 [Thrifty.com] New ruleset
  src/chrome/content/rules/Thrifty.com.xml
Labels: top-100k

#16629 Add ruleset: Minix3.org
  src/chrome/content/rules/Minix3.org.xml
Labels: new-ruleset

#16992 [familycouncil.gov.hk] New ruleset
  src/chrome/content/rules/GovHK.xml
  src/chrome/content/rules/familycouncil.gov.hk.xml
Labels: new-ruleset

#16993 [hiking.gov.hk] New ruleset
  src/chrome/content/rules/GovHK.xml
  src/chrome/content/rules/hiking.gov.hk.xml
Labels: new-ruleset

#16776 Add distro fallback on install-dev-dependencies.sh
  install-dev-dependencies.sh
Labels: enhancement, toolchain

#16997 Add more hosts to Debian.xml and remove Debian.org-problematic.xml
  src/chrome/content/rules/Debian.net.xml
  src/chrome/content/rules/Debian.org-problematic.xml
  src/chrome/content/rules/Debian.xml
Labels: ruleset-enhancement, top-10k

#16946 Update Baidu.xml and Bdimg.com.xml
  src/chrome/content/rules/Baidu.xml
  src/chrome/content/rules/Bdimg.com-mixedcontent.xml
  src/chrome/content/rules/Bdimg.com.xml
Labels: top-100
