Repository EFForg/https-everywhere, pull requests merged in 2018-05, with the labels that each got.

#15377 Create Sabq.org.xml [top-1k]
  src/chrome/content/rules/Sabq.org.xml
Labels: top-1k

#15379 Create ruleset: TheGuardian.pe.ca
  src/chrome/content/rules/TheGuardian.pe.ca.xml
Labels: top-100k

#15404 Activate LeMonde.fr.xml = no longer mixedcontent [top-1k]
  src/chrome/content/rules/LeMonde.fr.xml
Labels: top-1k

#15392 Update Catbox.moe.xml
  src/chrome/content/rules/Catbox.moe.xml
Labels: top-100k

#15369 [ArenaofValor.com] New ruleset
  src/chrome/content/rules/ArenaofValor.com.xml
Labels: top-1m

#15409 [omgubuntu.co.uk] New ruleset
  src/chrome/content/rules/Omgubuntu.co.uk.xml
Labels: top-100k

#15431 Update ruleset: FotoForensics.com
  src/chrome/content/rules/FotoForensics.com.xml
Labels: top-100k

#15370 [GearBest.com] New ruleset
  src/chrome/content/rules/GearBest.com.xml
Labels: top-1k

#15286 Create NakedCapitalism.com.xml [top-100k]
  src/chrome/content/rules/NakedCapitalism.com.xml
Labels: top-100k

#15317 Update QuranicAudio.com.xml [top-100k]
  src/chrome/content/rules/QuranicAudio.com.xml
Labels: top-1m

#15316 Create BuyMeACoffee.com.xml [top-100k]
  src/chrome/content/rules/BuyMeACoffee.com.xml
Labels: top-100k

#15426 Create ruleset: OrangeNaturals.com
  src/chrome/content/rules/OrangeNaturals.com.xml
Labels: broken MCB, new-ruleset

#15304 Create Coinsh.red.xml
  src/chrome/content/rules/Coinsh.red.xml
Labels: top-1m

#15296 Add ruleset: Wooting.nl
  src/chrome/content/rules/Wooting.nl.xml
Labels: top-1m

#15301 [Zello.com] New ruleset
  src/chrome/content/rules/Zello.com.xml
Labels: top-1m

#15324 Add ruleset: TimHortons.com
  src/chrome/content/rules/TimHortons.com.xml
Labels: top-100k

#15302 [CurrencyFair.com] New ruleset
  src/chrome/content/rules/CurrencyFair.com.xml
Labels: top-100k

#15225 Create Okaz.com.sa.xml [top-10k]
  src/chrome/content/rules/Okaz.com.sa.xml
Labels: top-10k

#15224 Create Futura-Sciences.com.xml [top-10k]
  src/chrome/content/rules/Futura-Sciences.com.xml
Labels: top-10k

#15419 Create ruleset: Toolbox.com
  src/chrome/content/rules/Toolbox.com.xml
Labels: top-100k

#15215 [cimbclicks.com.my] Add redirect rule
  src/chrome/content/rules/CIMBClicks.com.my.xml
Labels: top-10k

#15170 dslreports.com: Add exclusion for Puma6 test page
  src/chrome/content/rules/DSLReports.xml
Labels: ruleset-bug, top-100k

#15140 Add ruleset: speedify.com
  src/chrome/content/rules/Speedify.com.xml
Labels: top-100k

#15111 Create ogcio.gov.hk.xml
  src/chrome/content/rules/GovHK.xml
  src/chrome/content/rules/ogcio.gov.hk.xml
Labels: top-1m

#15267 Create HHVM.com.xml
  src/chrome/content/rules/HHVM.com.xml
Labels: top-1m

#15285 Create HalalTube.com.xml [top-1m]
  src/chrome/content/rules/HalalTube.com.xml
Labels: new-ruleset

#15438 Update ruleset: DigitalOcean.com
  src/chrome/content/rules/DigitalOcean.com.xml
Labels: top-10k

#15396 Increase selenium query_selector timeout
  test/selenium/util.py
Labels: ruleset-testing

#15206 Use SHA256 in make.sh
  make.sh
Labels: toolchain

#15287 t.me
  src/chrome/content/rules/Telegram.org.xml
  src/chrome/content/rules/t.me.xml
Labels: new-ruleset, top-1k

#15466 Create ruleset: iDreamx.com
  src/chrome/content/rules/iDreamx.com.xml
Labels: top-100k

#15502 Create ruleset: Australia.gov.au
  src/chrome/content/rules/Australia.gov.au.xml
Labels: top-100k

#15411 Add "Reset to Defaults" Option in Popup UI, Fix #10004
  chromium/background-scripts/background.js
  chromium/pages/popup/index.html
  chromium/pages/popup/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: enhancement

#15528 Create Wiredjs.com.xml
  src/chrome/content/rules/Wiredjs.com.xml
Labels: top-100k

#15141 Add ruleset: connectify.me
  src/chrome/content/rules/Connectify.me.xml
Labels: new-ruleset, top-100k

#15420 Create ruleset: ExtremeTech.com
  src/chrome/content/rules/ExtremeTech.com.xml
  src/chrome/content/rules/Extreme_Tech.com.xml
  src/chrome/content/rules/Ziff-Davis-mismatches.xml
  src/chrome/content/rules/Ziff-Davis.xml
Labels: ruleset-enhancement, top-100k

#15294 Add ruleset: Inmoment.com
  src/chrome/content/rules/Inmoment.com.xml
Labels: new-ruleset, top-100k

#15374 Update ruleset: Ubisoft Entertainment
  src/chrome/content/rules/Ubisoft-Entertainment.xml
  src/chrome/content/rules/Uplay.ubi.com.xml
Labels: top-10k

#15354 Add ruleset: PetTravel.com
  src/chrome/content/rules/PetTravel.com.xml
Labels: new-ruleset, top-1m

#15314 Added target to netzpolitik.org ruleset
  src/chrome/content/rules/Netzpolitik.xml
Labels: ruleset-enhancement, top-1m

#15255 ubuntu-fi.org
  src/chrome/content/rules/ubuntu-fi.org.xml
Labels: new-ruleset

#15352 [twentyonepilots.com] Add ruleset
  src/chrome/content/rules/store.twentyonepilots.com.xml
Labels: new-ruleset

#15533 Create CCleaner.com.xml
  src/chrome/content/rules/CCleaner.com.xml
Labels: top-1k

#15539 Create Sport-English.com.xml
  src/chrome/content/rules/Sport-English.com.xml
Labels: top-100k

#15468 Create ruleset: PPSSPP.org
  src/chrome/content/rules/PPSSPP.org.xml
Labels: top-100k

#15537 Create Streamja.com.xml
  src/chrome/content/rules/Streamja.com.xml
Labels: top-10k

#15524 Update ruleset: Sacramento Bee
  src/chrome/content/rules/Sacramento-Bee.xml
  src/chrome/content/rules/Sacramento_Bee.xml
Labels: top-10k

#15529 Create CoolBackgrounds.io.xml
  src/chrome/content/rules/CoolBackgrounds.io.xml
Labels: top-100k

#15548 Create ruleset: SlashFilm.com
  src/chrome/content/rules/SlashFilm.com.xml
Labels: top-10k

#15320 New ruleset for wordreference.com
  src/chrome/content/rules/wordreference.com.xml
Labels: new-ruleset, top-1k
