Repository EFForg/https-everywhere, pull requests merged in 2018-04, with the labels that each got.

#15020 Add Scala-lang.org.xml (fix #15017)
  src/chrome/content/rules/Scala-lang.org.xml
Labels: new-ruleset

#15018 [KnownHost] New ruleset
  src/chrome/content/rules/KnownHost.com.xml
Labels: top-100k

#14976 Update Bundestag.de
  src/chrome/content/rules/Deutscher_Bundestag.xml
Labels: ruleset-enhancement, top-100k

#14720 Create LessWrong.com.xml
  src/chrome/content/rules/LessWrong.com.xml
Labels: new-ruleset, top-100k

#15034 Update and rename Zopim.xml to Zopim.com.xml
  src/chrome/content/rules/Zopim.com.xml
  src/chrome/content/rules/Zopim.xml
Labels: ruleset-enhancement

#11485 [DataFile.com] Merge and simplify rulesets
  src/chrome/content/rules/DataFile.com-resources.xml
  src/chrome/content/rules/datafile.com-resources.xml
  src/chrome/content/rules/datafile.com.xml
Labels: needs revision, ruleset-bug, top-10k

#15032 Update Samsung.xml
  src/chrome/content/rules/Samsung.xml
Labels: ruleset-bug

#15035 Remove unnecessary rule from UK_Ministry_of_Defence.xml
  src/chrome/content/rules/UK_Ministry_of_Defence.xml
Labels: ruleset-enhancement

#14822 [Banca Intesa Beograd] New ruleset
  src/chrome/content/rules/Banca-Intesa-Beograd.xml
Labels: new-ruleset

#15016 [Halo oglasi] New ruleset
  src/chrome/content/rules/Halo-oglasi.xml
Labels: top-100k

#15006 Update DENX.de.xml
  src/chrome/content/rules/DENX.de.xml
Labels: top-1m

#14765 Add spacepools.org
  src/chrome/content/rules/spacepools.org.xml
Labels: new-ruleset, top-100k

#11864 Added jugendaemter.com
  src/chrome/content/rules/Jugendaemter.com.xml
Labels: new-ruleset

#14955 [FMLife.com] Default_off ruleset
  src/chrome/content/rules/FMyLife.com.xml
Labels: ruleset-bug, top-100k

#14761 Add electroneum.com
  src/chrome/content/rules/electroneum.com.xml
Labels: new-ruleset, top-100k

#14699 Create Doarama.com.xml
  src/chrome/content/rules/Doarama.com.xml
Labels: top-1m

#14749 Add Worldofplayers.de
  src/chrome/content/rules/worldofplayers.de.xml
Labels: new-ruleset, top-100k

#14708 Add ruleset for vertx.com
  src/chrome/content/rules/Vertx.com.xml
Labels: top-1m

#14972 Update Sinaimg.cn.xml
  src/chrome/content/rules/Sinaimg.cn.xml
Labels: top-100k

#14922 [SciPy.org] Reactivate ruleset
  src/chrome/content/rules/SciPy.org.xml
Labels: top-10k

#14773 Create Ithenticate.com.xml
  src/chrome/content/rules/Ithenticate.com.xml
Labels: top-100k

#14736 Create GISTI.org.xml
  src/chrome/content/rules/GISTI.org.xml
Labels: top-1m

#14945 Create SemanticScholar.org.xml
  src/chrome/content/rules/SemanticScholar.org.xml
Labels: top-10k

#14551 Create LitRes.ru.xml
  src/chrome/content/rules/LitRes.ru.xml
Labels: top-10k

#14818 Added ruleset for bam.de
  src/chrome/content/rules/BAM.de.xml
Labels: new-ruleset, top-1m

#12804 Zakonypreludi
  src/chrome/content/rules/Zakonypreludi.sk.xml
Labels: top-1m

#14148 add rule for Aniview.com
  src/chrome/content/rules/Aniview.com.xml
Labels: new-ruleset, top-1m

#15024 Update Imperial-College-London.xml
  src/chrome/content/rules/Imperial-College-London.xml
Labels: top-10k

#14868 Add ruleset for Lawyermarketing.com
  src/chrome/content/rules/Lawyermarketing.com.xml
Labels: new-ruleset

#14786 Restore a missing line break
  docs/en_US/development.md
Labels: docs

#14534 Add rtm.quebec
  src/chrome/content/rules/rtm.quebec.xml
Labels: top-1m

#15124 Add zli.ch ruleset
  src/chrome/content/rules/zli.ch.xml
Labels: new-ruleset

#14781 Update Threema.xml
  src/chrome/content/rules/Threema.xml
Labels: top-1m

#14660 Add Test for duplicated test URLs, Fix #14659
  test/rules/src/https_everywhere_checker/rules.py
  utils/ruleset-whitelist.csv
Labels: ruleset-testing

#14920 [Nelonen.fi] Merge and simplify rulesets
  src/chrome/content/rules/Nelonen.fi-mixedvideo.xml
  src/chrome/content/rules/Nelonen.fi.xml
Labels: top-1m
