Repository EFForg/https-everywhere, pull requests merged in 2018-03, with the labels that each got.

#14641 added subdomains of cs.byu.edu that should be https only
  src/chrome/content/rules/BYU.edu.xml
Labels: top-10k

#14830 Add target to Twitch.tv ruleset
  src/chrome/content/rules/Twitch.tv.xml
Labels: top-100

#14820 Added ruleset for bav.bund.de
  src/chrome/content/rules/Verwaltung_Online.xml
  src/chrome/content/rules/bav.bund.de.xml
Labels: top-100k

#14804 [Nyx.cz] Remove duplicate test url
  src/chrome/content/rules/Nyx.cz.xml
Labels: top-100k

#14793 Update Washington-Post-Company.xml
  src/chrome/content/rules/Washington-Post-Company.xml
Labels: top-1k

#14766 Update lofter.com.xml
  src/chrome/content/rules/lofter.com.xml
Labels: top-100k

#14828 [PrettyLightsMusic.com] Remove platform
  src/chrome/content/rules/PrettyLightsMusic.com.xml
  src/chrome/content/rules/PrettyLightsMusic.xml
Labels: top-1m

#14689 Add byond.com ruleset
  src/chrome/content/rules/Byond.com.xml
Labels: new-ruleset, top-100k

#10948 Update Eventim.xml
  src/chrome/content/rules/Eventim.co.il.xml
  src/chrome/content/rules/Eventim.co.uk.xml
  src/chrome/content/rules/Eventim.com.br.xml
  src/chrome/content/rules/Eventim.com.xml
  src/chrome/content/rules/Eventim.cu.xml
  src/chrome/content/rules/Eventim.de.xml
  src/chrome/content/rules/Eventim.fr.xml
  src/chrome/content/rules/Eventim.nl.xml
  src/chrome/content/rules/Eventim.no.xml
  src/chrome/content/rules/Eventim.pl.xml
  src/chrome/content/rules/Eventim.se.xml
  src/chrome/content/rules/Eventim.sk.xml
  src/chrome/content/rules/Eventim.xml
  src/chrome/content/rules/Getgo.de.xml
  src/chrome/content/rules/Getgo.xml
  src/chrome/content/rules/Lippupiste_Oy.xml
  src/chrome/content/rules/Oeticket.xml
  src/chrome/content/rules/Parter.ru.xml
  src/chrome/content/rules/Paytoll.xml
  src/chrome/content/rules/Ticketcorner.ch.xml
Labels: ruleset-enhancement, top-10k

#14846 [Po.st] Add exclusion (fix #14845)
  src/chrome/content/rules/Po.st.xml
Labels: top-100k

#14847 [RTS Planeta] New ruleset
  src/chrome/content/rules/RTS-Planeta.xml
Labels: top-100k

#14831 [CAD-comic] Simplify ruleset and add targets
  src/chrome/content/rules/CAD-Comic.com.xml
  src/chrome/content/rules/Ctrl_Alt_Del.xml
Labels: top-100k

#14827 [Upaiyun.com] Add exclusion (fix #13532)
  src/chrome/content/rules/Upaiyun.com.xml
Labels: top-100k

#14812 [WEForum.org] Fix broken redirect
  src/chrome/content/rules/WEForum.org.xml
  src/chrome/content/rules/WE_Forum.org.xml
Labels: top-10k

#14814 [Theses.cz] Update regex style
  src/chrome/content/rules/Theses.cz.xml
Labels: top-1m

#14811 [AmazonAWS.com] Fix unescaped dots
  src/chrome/content/rules/AmazonAWS.com.xml
Labels: top-100

#14791 [SurfCanyon.com] Default_off ruleset
  src/chrome/content/rules/Surfcanyon.com.xml
Labels: top-1m

#14794 Update and rename MerNetwork.xml to MerNetwork.com.xml
  src/chrome/content/rules/MerNetwork.com.xml
  src/chrome/content/rules/MerNetwork.xml
Labels: top-1m

#14852 Update Chefkoch.de
  src/chrome/content/rules/Chefkoch.de.xml
Labels: top-10k

#14855 [cimb.com] Insert back the references
  src/chrome/content/rules/CIMB.com.xml
Labels: top-100k

#14854 [Mozilla.org] Update working or non-existent hosts
  src/chrome/content/rules/Mozilla.xml
Labels: top-1k

#13757 Improve CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#14875 Remove cacert platform
  chromium/background-scripts/rules.js
  src/chrome/content/rules/CAcert.xml
  src/chrome/content/rules/CHDK.xml
  src/chrome/content/rules/Flaska.net.xml
  src/chrome/content/rules/Jensge.org.xml
  src/chrome/content/rules/Le_Loop.org.xml
  src/chrome/content/rules/LinuxTag.org.xml
  src/chrome/content/rules/Lolnet.org.xml
  src/chrome/content/rules/Micro_Polia.xml
  src/chrome/content/rules/SF-Mail.de.xml
  src/chrome/content/rules/Someserver.xml
  src/chrome/content/rules/Xiscosoft.es.xml
  src/chrome/content/rules/Zugaina-mismatches.xml
  test/rules/platform_certs/cacert/5ed36f99.0
  test/rules/platform_certs/cacert/99d0fa06.0
  test/rules/platform_certs/cacert/cacert_class1_root.pem
  test/validations/relaxng/schema.xml
Labels: top-1m

#14881 [Cloudfront.net] Add exclusion (fix #3045)
  src/chrome/content/rules/Cloudfront.xml
Labels: top-1k

#14075 [Etiqa.com.my] New ruleset
  src/chrome/content/rules/Etiqa.com.my.xml
Labels: new-ruleset, top-1m

#14070 [Maybank-KE.co.th] New ruleset
  src/chrome/content/rules/Maybank-KE.co.th.xml
Labels: new-ruleset

#14858 [Wikimedia.xml] Remove blog.wikimedia.de from exclusion
  src/chrome/content/rules/Wikimedia.xml
Labels: top-100k

#14870 Added ruleset for bundesanzeiger.de
  src/chrome/content/rules/Bundesanzeiger.de.xml
Labels: top-100k

#14884 [Ikea.com] Add target
  src/chrome/content/rules/Ikea.com.xml
Labels: top-1k

#14865 Update FileFormat.info.xml
  src/chrome/content/rules/FileFormat.info.xml
Labels: top-100k

#14864 Rename and update whisky.de.xml
  src/chrome/content/rules/Whisky.de.xml
  src/chrome/content/rules/whisky.de.xml
Labels: top-100k

#14901 [Allizom.org] Simplify and reactivate ruleset
  src/chrome/content/rules/Allizom.org.xml
Labels: top-1m

#14796 Update Demonoid.xml
  src/chrome/content/rules/Demonoid.xml
Labels: top-10k

#14900 Create Cinemas-Utopia.org.xml
  src/chrome/content/rules/Cinemas-Utopia.org.xml
Labels: top-1m

#14899 [Commission_Junction] Remove duplicated target
  src/chrome/content/rules/Commission_Junction.xml
  utils/ruleset-whitelist.csv
Labels: top-10k

#13647 Add Les-Crises.fr.xml
  src/chrome/content/rules/Les-Crises.fr.xml
Labels: top-100k

#14011 Update US-military.xml
  src/chrome/content/rules/US-military.xml
  utils/ruleset-whitelist.csv
Labels: top-1m

#14042 [ourcommons.ca] New rule
  src/chrome/content/rules/NosCommunes.ca.xml
  src/chrome/content/rules/OurCommons.ca.xml
Labels: top-1m

#8361 Add ImamReza.net.xml
  src/chrome/content/rules/ImamReza.net.xml
Labels: top-1m

#14892 Add BleepingComputer.com
  src/chrome/content/rules/bleepingcomputer.com.xml
Labels: top-10k

#14780 Update freeboard.io.xml
  src/chrome/content/rules/freeboard.io.xml
Labels: top-1m

#14779 Update cede.ch.xml
  src/chrome/content/rules/cede.ch.xml
Labels: top-100k

#14799 Update and rename Pfennigparade.xml to Pfennigparade.de.xml
  src/chrome/content/rules/Pfennigparade.de.xml
  src/chrome/content/rules/Pfennigparade.xml
Labels: top-1m

#14921 Add planet.gnu.org, Fix #14890, Re-open #14891
  src/chrome/content/rules/GNU.org.xml
Labels: top-10k

#14554 Create RoyalLib.com.xml
  src/chrome/content/rules/RoyalLib.com.xml
Labels: top-10k

#14926 Update WDR
  src/chrome/content/rules/Wdr.de.xml
Labels: top-10k

#14556 Create CoolLib.com.xml
  src/chrome/content/rules/CoolLib.com.xml
Labels: top-100k

#14853 Add Transfermarkt.de
  src/chrome/content/rules/transfermarkt.de.xml
Labels: failing tests, top-10k

#14816 [Panasonic.com] Add targets
  src/chrome/content/rules/Panasonic.com.xml
Labels: top-10k

#14465 Add symmetricstrength.com
  src/chrome/content/rules/SymmetricStrength.com.xml
Labels: top-1m

#14930 Add Mvnrepository.com.xml
  src/chrome/content/rules/Mvnrepository.com.xml
Labels: new-ruleset, top-10k

#14929 Add Iemoji.com.xml
  src/chrome/content/rules/Iemoji.com.xml
Labels: new-ruleset, top-100k

#14931 Add Getemoji.com.xml
  src/chrome/content/rules/Getemoji.com.xml
Labels: new-ruleset, top-10k

#14346 Add Alaalam.org.xml
  src/chrome/content/rules/Alaalam.org.xml
Labels: top-1m

#14897 [Adbusters.org] Add subdomains
  src/chrome/content/rules/Adbusters.org.xml
Labels: top-1m

#11462 Add FreeRADIUS.org
  src/chrome/content/rules/FreeRADIUS.org.xml
Labels: top-1m

#14819 Added ruleset for bast.de
  src/chrome/content/rules/BASt.de.xml
Labels: top-1m

#8368 Add TheIsmaili.org.xml
  src/chrome/content/rules/The.Ismaili.xml
  src/chrome/content/rules/TheIsmaili.org.xml
Labels: top-1m

#14742 [BALPA.org] Trivialize ruleset
  src/chrome/content/rules/BALPA.org.xml
  src/chrome/content/rules/British_Airline_Pilots_Association.xml
Labels: top-1m

#14960 Added ruleset for baf.bund.de
  src/chrome/content/rules/Verwaltung_Online.xml
  src/chrome/content/rules/baf.bund.de.xml
Labels: top-100k

#14975 Create GrandViewOutdoors.com.xml
  src/chrome/content/rules/GrandViewOutdoors.com.xml
Labels: top-1m

#14965 [FogCreek.com] Add targets
  src/chrome/content/rules/FogCreek.com.xml
  src/chrome/content/rules/Fog_Creek.xml
Labels: top-1m

#14824 Create Doe.com.ua.xml
  src/chrome/content/rules/Doe.com.ua.xml
Labels: top-1m

#13865 Create Vim.org.xml
  src/chrome/content/rules/Vim.org.xml
Labels: top-100k

#14994 Create chuapp.com.xml
  src/chrome/content/rules/chuapp.com.xml
Labels: top-100k

#14996 Remove duplicates from Inc.com.xml
  src/chrome/content/rules/Inc.com-falsemixed.xml
  src/chrome/content/rules/Inc.com.xml
Labels: top-10k

#14983 Rename and Update WyndhamHotels.com.xml, Fix #12672
  src/chrome/content/rules/CanvasHolidays.co.uk.xml
  src/chrome/content/rules/Cheznous.com.xml
  src/chrome/content/rules/Cottages.com.xml
  src/chrome/content/rules/Cottages4you.co.uk.xml
  src/chrome/content/rules/Cottagesdirect.co.uk.xml
  src/chrome/content/rules/English-Country-Cottages.co.uk.xml
  src/chrome/content/rules/Hoseasons.co.uk.xml
  src/chrome/content/rules/Irish-Country-Cottages.co.uk.xml
  src/chrome/content/rules/Italian-Country-Cottages.co.uk.xml
  src/chrome/content/rules/JamesVillas.co.uk.xml
  src/chrome/content/rules/Landal.xml
  src/chrome/content/rules/Ovscruise.com.xml
  src/chrome/content/rules/RCITravelStore.co.uk.xml
  src/chrome/content/rules/Scottish-Country-Cottages.co.uk.xml
  src/chrome/content/rules/WelcomeCottages.com.xml
  src/chrome/content/rules/Welsh-Country-Cottages.co.uk.xml
  src/chrome/content/rules/Wyndham.xml
  src/chrome/content/rules/WyndhamHotels.com.xml
  src/chrome/content/rules/WyndhamJobs.com.xml
  src/chrome/content/rules/WyndhamVacationRentals.com.xml
  src/chrome/content/rules/Wyndhamvrap.com.xml
  src/chrome/content/rules/landalskilife.be.xml
  src/chrome/content/rules/landalskilife.ch.xml
  src/chrome/content/rules/landalskilife.com.xml
  src/chrome/content/rules/landalskilife.cz.xml
  src/chrome/content/rules/landalskilife.de.xml
  src/chrome/content/rules/landalskilife.fr.xml
  src/chrome/content/rules/landalskilife.nl.xml
  utils/ruleset-whitelist.csv
Labels: top-100k

#15003 Delete linuxgizmos.com.xml
  src/chrome/content/rules/linuxgizmos.com.xml
Labels: top-1m

#14987 Delete Stuart-Robbins.xml
  src/chrome/content/rules/Stuart-Robbins.xml
Labels: top-1m

#15002 [Solarbotics.com] Trivialize ruleset
  src/chrome/content/rules/Solarbotics.com.xml
Labels: top-1m

#14954 [Indiana.edu] Add exclusion
  src/chrome/content/rules/Indiana.edu.xml
Labels: ruleset-bug, top-10k

#15013 Remove duplicates of thediplomat.com
  src/chrome/content/rules/The-Diplomat.xml
  src/chrome/content/rules/TheDiplomat.com.xml
  src/chrome/content/rules/thediplomat.com-resources.xml
Labels: top-100k

#15009 [Mwave.com.au] Simplify ruleset
  src/chrome/content/rules/Mwave.com.au.xml
  src/chrome/content/rules/Mwave.xml
Labels: top-100k

#15012 Remove duplicates of thefederalistpapers.org
  src/chrome/content/rules/TheFederalistPapers.org.xml
  src/chrome/content/rules/The_Federalist_Papers.org-falsemixed.xml
  src/chrome/content/rules/The_Federalist_Papers.org.xml
Labels: top-1m

#15014 [StockTwits.com] Simplify ruleset
  src/chrome/content/rules/StockTwits.com.xml
  src/chrome/content/rules/StockTwits.xml
Labels: top-10k

#14951 [Ghost.org] Add targets and simplify ruleset
  src/chrome/content/rules/Ghost.org.xml
Labels: top-100k

#15010 Remove duplicates of blogsmithmedia.com
  src/chrome/content/rules/AOL-mismatches.xml
  src/chrome/content/rules/Moviefone.xml
Labels: top-10k

#13464 Add ruleset for asrock.com
  src/chrome/content/rules/Asrock.com.xml
Labels: new-ruleset, top-100k

#14072 [Maybank.co.id] New ruleset
  src/chrome/content/rules/Maybank.co.id.xml
Labels: new-ruleset, top-100k

#14069 [Maybank.com.sg] New ruleset
  src/chrome/content/rules/Maybank.com.sg.xml
Labels: new-ruleset

#14004 [DBA.dk] New ruleset
  src/chrome/content/rules/DBA.dk.xml
Labels: new-ruleset, top-10k

#14984 Create Wikimonde.com.xml
  src/chrome/content/rules/Wikimonde.com.xml
Labels: top-1m

#14267 [Gittigidiyor.net] Update subdomains
  src/chrome/content/rules/Gittigidiyor.net.xml
  src/chrome/content/rules/Gittigidiyor.xml
Labels: conflict, top-10k

#14988 [TechRepublic.com] Merge and simplify rulesets
  src/chrome/content/rules/CBS.xml
  src/chrome/content/rules/TechRepublic.com-problematic.xml
  src/chrome/content/rules/TechRepublic.com.xml
  src/chrome/content/rules/TechRepublic.xml
  utils/ruleset-whitelist.csv
Labels: top-10k

#13398 [hercrentals.com] New ruleset
  src/chrome/content/rules/Hercrentals.com.xml
Labels: failing tests, new-ruleset, top-1m

#14986 add rule for Ur.se
  src/chrome/content/rules/Ur.se.xml
Labels: top-1m

#14985 add rule for MediathekView.de
  src/chrome/content/rules/MediathekView.de.xml
Labels: top-1m

#14971 Added ruleset for zlib.net
  src/chrome/content/rules/zlib.net.xml
Labels: top-1m

#14911 Update blogtrottr.com ruleset
  src/chrome/content/rules/Blogtrottr.com.xml
Labels: top-1m

#14919 Fix ruleset for Hatena
  src/chrome/content/rules/Hatena.xml
Labels: ruleset-bug, top-1k

#14928 Create Performance-PCs.com.xml
  src/chrome/content/rules/Performance-PCs.com.xml
Labels: top-100k

#14941 Added ruleset for cncf.io
  src/chrome/content/rules/cncf.io.xml
Labels: top-1m

#14959 Added ruleset for bundesarchiv.de
  src/chrome/content/rules/Bundesarchiv.de.xml
Labels: top-1m

#14851 Update SWU.de
  src/chrome/content/rules/Swu.de.xml
Labels: top-1m

#14790 Create NBCOlympics.com.xml
  src/chrome/content/rules/NBCOlympics.com.xml
Labels: top-1k

#14792 [Journeyed.com] Add targets
  src/chrome/content/rules/Journeyed.com.xml
Labels: top-1m

#14759 [Thp.io] Add subdomains
  src/chrome/content/rules/Thp.io.xml
Labels: top-1m

#14950 Official Enjin Ruleset
  src/chrome/content/rules/Enjin.xml
Labels: ruleset-bug, ruleset-enhancement, top-100k

#14633 [INaturalist.org] Add targets and simplify rule
  src/chrome/content/rules/INaturalist.org.xml
Labels: top-100k

#15037 [Vr-mfr.de] New ruleset
  src/chrome/content/rules/Vr-mfr.de.xml
Labels: new-ruleset
