Repository EFForg/https-everywhere, pull requests merged in 2018-06, with the labels that each got.

#15525 Update Tool Labs section to bring all of wmflabs to HTTPS
  src/chrome/content/rules/Wikimedia.xml
Labels: top-1m

#15499 Create ruleset: CrazyHD.com
  src/chrome/content/rules/CrazyHD.com.xml
Labels: top-100k

#15376 [dongleauth.info] Add ruleset
  src/chrome/content/rules/dongleauth.info.xml
Labels: new-ruleset

#15310 Add ruleset: afterdawn.com
  src/chrome/content/rules/Afterdawn.com.xml
Labels: new-ruleset, top-100k

#15569 Create ProxySite.club.xml
  src/chrome/content/rules/ProxySite.club.xml
Labels: top-1m

#15565 Create ImageTwist.com.xml
  src/chrome/content/rules/ImageTwist.com.xml
Labels: top-10k

#15567 Create Ultrasawt.com.xml
  src/chrome/content/rules/Ultrasawt.com.xml
Labels: top-100k

#15574 Create MaxMaillots.org.xml
  src/chrome/content/rules/MaxMaillots.org.xml
Labels: top-1m

#15572 Create NQuran.com.xml
  src/chrome/content/rules/NQuran.com.xml
Labels: top-1m

#15562 Added ruleset for bundesgerichtshof.de
  src/chrome/content/rules/Bundesgerichtshof.de.xml
Labels: top-1m

#15544 Create ruleset: ValidCreditCardNumber.com
  src/chrome/content/rules/ValidCreditCardNumber.com.xml
Labels: top-1m

#15543 Update and rename kt.kz.xml to KT.kz.xml
  src/chrome/content/rules/KT.kz.xml
Labels: top-1m

#15550 Create ruleset: CrowdTangle.com
  src/chrome/content/rules/CrowdTangle.xml
Labels: top-100k

#15386 [tbz.ch] Add ruleset
  src/chrome/content/rules/tbz.ch.xml
Labels: new-ruleset, top-1m

#15571 Create QTafsir.com.xml
  src/chrome/content/rules/QTafsir.com.xml
Labels: broken MCB, new-ruleset, top-1m

#15570 Create GuildEducation.com.xml
  src/chrome/content/rules/GuildEducation.com.xml
Labels: top-1m

#15460 Update ruleset: Lotame
  src/chrome/content/rules/Lotame.xml
Labels: top-100k

#15505 Create ruleset: Chorizo.ca
  src/chrome/content/rules/Chorizo.ca.xml
Labels: top-1m

#15506 Create ruleset: BTToronto.ca
  src/chrome/content/rules/BTToronto.ca.xml
Labels: top-1m

#15470 Create ruleset: ExtremeTacticalDynamics.com
  src/chrome/content/rules/ExtremeTacticalDynamics.com.xml
Labels: top-1m

#15480 Update ruleset: SoupCDN.com
  src/chrome/content/rules/Soup.io.xml
  src/chrome/content/rules/SoupCDN.com.xml
Labels: top-100k

#15488 Create ruleset: Chefmansousvide.com
  src/chrome/content/rules/Chefmansousvide.com.xml
Labels: top-1m

#15583 Create Al-Madina.com.xml
  src/chrome/content/rules/Al-Madina.com.xml
Labels: broken MCB, new-ruleset, top-100k

#15588 Update ruleset: Messenger.com
  src/chrome/content/rules/Messenger.com.xml
Labels: top-1k

#15489 Simplify and update Bloomberg.xml
  src/chrome/content/rules/Bloomberg.com-problematic.xml
  src/chrome/content/rules/Bloomberg.xml
Labels: top-1k

#15449 Update TouTiao.xml
  src/chrome/content/rules/TouTiao.xml
Labels: top-10k

#15479 Update ruleset: Soup.io
  src/chrome/content/rules/Soup.io.xml
Labels: top-100k

#14626 [ebay.co.uk] New ruleset
  src/chrome/content/rules/ebay.co.uk.xml
  src/chrome/content/rules/ebay.com.xml
Labels: failing tests, top-1k

#15589 Create HotHardware.com.xml
  src/chrome/content/rules/HotHardware.com.xml
Labels: top-100k

#15560 Added ruleset for bev.bund.de
  src/chrome/content/rules/BEV.bund.de.xml
  src/chrome/content/rules/Verwaltung_Online.xml
Labels: top-100k

#15458 Create ruleset: DailyHive.com
  src/chrome/content/rules/DailyHive.com.xml
Labels: new-ruleset, top-100k

#15471 Update ruleset: NGP VAN
  src/chrome/content/rules/NGP-VAN.xml
  src/chrome/content/rules/NGP_VAN.xml
Labels: ruleset-bug, top-100k

#15298 [CatchConnect.com.au] New ruleset
  src/chrome/content/rules/Catch.com.au.xml
  src/chrome/content/rules/CatchConnect.com.au.xml
Labels: top-100k

#15549 Create K-tb.com.xml
  src/chrome/content/rules/K-tb.com.xml
Labels: broken MCB, new-ruleset, top-1m

#15519 Fixed and updated schema.org ruleset.
  src/chrome/content/rules/schema.org.xml
Labels: top-100k

#15332 [Unsplash.com] New ruleset
  src/chrome/content/rules/Unsplash.com.xml
Labels: new-ruleset, top-1k

#15408 [Inhabitat.com] New ruleset
  src/chrome/content/rules/Inhabitat.com.xml
Labels: top-100k

#15463 Update Ravenjs.com.xml
  src/chrome/content/rules/Ravenjs.com.xml
  src/chrome/content/rules/ravenjs.com.xml
Labels: top-1m

#15323 Update ruleset: BodyBuilding.com
  src/chrome/content/rules/BodyBuilding.com.xml
Labels: top-10k

#15599 Create ruleset: MyAMS.org
  src/chrome/content/rules/MyAMS.org.xml
Labels: top-1m

#15598 Update ruleset: LongTail
  src/chrome/content/rules/LongTail.xml
Labels: top-10k

#15540 Update and rename Diskusjon.xml to Diskusjon.no.xml
  src/chrome/content/rules/Diskusjon.no.xml
  src/chrome/content/rules/Diskusjon.xml
Labels: top-100k

#15542 Update Aea.se.xml
  src/chrome/content/rules/Aea.se.xml
Labels: top-1m

#15585 Create Pravduh.com.xml
  src/chrome/content/rules/Pravduh.com.xml
Labels: top-100k

#14953 [Zhihu.xml] worldcup2014 doesn't redirect to http now
  src/chrome/content/rules/Zhihu.xml
Labels: top-1k

#15593 [FreeThesaurus.com] New ruleset
  src/chrome/content/rules/FreeThesaurus.com.xml
  src/chrome/content/rules/TheFreeDictionary.com.xml
Labels: top-1k

#15378 [tomshardware.com] Add ruleset
  src/chrome/content/rules/TomsHardware.com.xml
Labels: top-1k

#15611 Create ruleset: SheldonBrown.com
  src/chrome/content/rules/SheldonBrown.com.xml
Labels: top-100k

#15610 Create Me.me.xml
  src/chrome/content/rules/Me.me.xml
Labels: top-10k

#15365 Update ruleset: Fox News
  src/chrome/content/rules/Fox-News.xml
  src/chrome/content/rules/Fox_News.xml
  src/chrome/content/rules/News-Corporation.xml
Labels: top-1k

#15617 Update and rename IELTS.xml to IELTS.org.xml [mixedcontents audit]
  src/chrome/content/rules/IELTS.org.xml
  src/chrome/content/rules/IELTS.xml
Labels: top-100k

#14778 Add Bahnhof.se.xml
  src/chrome/content/rules/Bahnhof.se.xml
Labels: new-ruleset, top-100k

#14784 Add ruleset for thinkwiki.org
  src/chrome/content/rules/Thinkwiki.org.xml
Labels: new-ruleset, top-1m

#15609 Update and rename RIAA.xml to RIAA.com.xml [mixedcontents audit]
  src/chrome/content/rules/RIAA.com.xml
  src/chrome/content/rules/RIAA.xml
Labels: top-1m

#15622 Update ruleset: Khan Academy
  src/chrome/content/rules/Khan-Academy.xml
Labels: top-1k

#15601 Create ruleset: ResearcherID.com
  src/chrome/content/rules/ResearcherID.com.xml
Labels: top-100k

#15626 Create ruleset: HealthyGeorge.com
  src/chrome/content/rules/HealthyGeorge.com.xml
Labels: top-100k

#13637 [Telstra.com.au] New rulesets
  src/chrome/content/rules/Telstra.com.au.xml
Labels: top-10k

#15604 Create ruleset: GoingAwesomePlaces.com
  src/chrome/content/rules/GoingAwesomePlaces.com.xml
Labels: top-1m

#15638 Update Firefox.com.xml
  src/chrome/content/rules/Firefox.com.xml
Labels: top-1k

#15637 Update and rename Mint.xml to Mint.com.xml [mixedcontents audit]
  src/chrome/content/rules/Mint.com.xml
  src/chrome/content/rules/Mint.xml
Labels: top-10k

#15597 Create ruleset: StyleCaster.com
  src/chrome/content/rules/StyleCaster.com.xml
Labels: top-100k

#15645 Update ruleset: Criteo.com
  src/chrome/content/rules/Criteo.com.xml
Labels: top-10k

#15648 Create ArtOfProblemSolving.com.xml
  src/chrome/content/rules/ArtOfProblemSolving.com.xml
Labels: top-100k

#15580 Added ruleset for spreadprivacy.com
  src/chrome/content/rules/DuckDuckGo.xml
  src/chrome/content/rules/SpreadPrivacy.com.xml
Labels: new-ruleset

#15649 Update and rename MakeUseOf.xml to MakeUseOf.com.xml
  src/chrome/content/rules/MakeUseOf.com.xml
  src/chrome/content/rules/MakeUseOf.xml
Labels: top-10k

#15532 Improve popup page performance and reduce memory usage
  chromium/pages/popup/style.css
  chromium/pages/popup/ux.js
Labels: performance, ui

#15682 Create ruleset: CNNIC.net.cn
  src/chrome/content/rules/CNNIC.net.cn.xml
Labels: top-1m

#14271 [Stubhub.es] New ruleset
  src/chrome/content/rules/Stubhub.es.xml
  utils/ruleset-whitelist.csv
Labels: failing tests, top-1m

#15703 Update ruleset: Dell.com-falsemixed
  src/chrome/content/rules/Dell.com-falsemixed.xml
Labels: top-1k

#15343 [FirstChoiceLiquor.com.au] New ruleset
  src/chrome/content/rules/FirstChoiceLiquor.com.au.xml
Labels: top-1m

#15346 [Liquorland.com.au] New ruleset
  src/chrome/content/rules/Liquorland.com.au.xml
Labels: top-1m

#15349 [VintageCellars.com.au] New ruleset
  src/chrome/content/rules/VintageCellars.com.au.xml
Labels: top-1m

#15347 [mycoles.com.au] New ruleset
  src/chrome/content/rules/Mycoles.com.au.xml
Labels: top-1m

#15719 [Afterpay.com] New ruleset
  src/chrome/content/rules/Afterpay.com.xml
Labels: top-100k

#15676 Update PRV.se.xml [mixedcontents audit]
  src/chrome/content/rules/PRV.se.xml
Labels: top-1m

#15658 Update and rename from-ua.com.xml to From-UA.com.xml [mixedcontents audit]
  src/chrome/content/rules/From-UA.com.xml
Labels: top-100k

#15686 Update and rename gtrk.tv.xml to GTRK.TV.xml [mixedcontents audit]
  src/chrome/content/rules/GTRK.TV.xml
Labels: top-1m

#15437 Update EasyNews.com.xml, fix #15436
  src/chrome/content/rules/EasyNews.com.xml
  src/chrome/content/rules/EasyNews.xml
Labels: top-100k

#15440 Create Vidga.me.xml
  src/chrome/content/rules/Vidga.me.xml
Labels: top-1m

#15344 [Kmart.com.au] New ruleset
  src/chrome/content/rules/Kmart.com.au.xml
Labels: new-ruleset, top-100k

#15709 Update ruleset: Taboola
  src/chrome/content/rules/Taboola.xml
Labels: top-1k

#15714 Update Firefox.com.xml
  src/chrome/content/rules/Firefox.com.xml
Labels: top-10k

#15342 [ColesExpress.com.au] New ruleset
  src/chrome/content/rules/ColesExpress.com.au.xml
Labels: new-ruleset, top-1m

#15613 Create ruleset: Furry.ch
  src/chrome/content/rules/Furry.ch.xml
Labels: top-1m

#15678 Create Sketch.systems.xml
  src/chrome/content/rules/Sketch.systems.xml
Labels: top-1m

#14640 Delete GannettLocal.xml
  src/chrome/content/rules/Gannett-Company.xml
  src/chrome/content/rules/GannettLocal.xml
Labels: top-1m

#14578 Move IBsrv.net to its own ruleset and fix broken redirects
  src/chrome/content/rules/IBsrv.net.xml
  src/chrome/content/rules/Internet_Brands.xml
Labels: ruleset-bug, top-1m

#15490 Update Financial_Times.xml
  src/chrome/content/rules/Financial_Times.xml
Labels: top-10k

#15563 Added ruleset for bfarm.de
  src/chrome/content/rules/BfArM.de.xml
Labels: top-1m

#15306 Create Audioz.download.xml [top-10k]
  src/chrome/content/rules/Audioz.download.xml
Labels: top-10k

#15624 wait for option page to load
  test/selenium/test_options.py
Labels: ruleset-testing

#15521 Added ruleset for hessenschau.de
  src/chrome/content/rules/hessenschau.de.xml
Labels: new-ruleset, top-100k

#15397 Revise ruleset: University of California Berkeley
  src/chrome/content/rules/University-of-California-Berkeley.xml
Labels: top-1k

#15299 [TransferWise.com] Add subdomains
  src/chrome/content/rules/TransferWise.com.xml
Labels: top-10k

#14005 [alaMaula.com] New ruleset
  src/chrome/content/rules/alaMaula.com.xml
Labels: top-100k

#15514 Added ruleset for ardmediathek.de
  src/chrome/content/rules/ARDMediathek.de.xml
Labels: new-ruleset, top-10k

#15356 Add ruleset: Eurowings.com
  src/chrome/content/rules/Eurowings.com.xml
Labels: new-ruleset, top-10k

#15558 Added ruleset for bundesrechnungshof.de
  src/chrome/content/rules/Bundesrechnungshof.de.xml
Labels: new-ruleset

#15330 update Zeit.de
  src/chrome/content/rules/Zeit.de.xml
Labels: top-10k

#15619 Create TrumpGolfCount.com.xml
  src/chrome/content/rules/TrumpGolfCount.com.xml
Labels: top-100k

#15633 [RunRepeat.com] New ruleset
  src/chrome/content/rules/RunRepeat.com.xml
Labels: top-100k

#15603 Create ruleset: Mozio.com
  src/chrome/content/rules/Mozio.com.xml
Labels: top-1m

#15620 Create ruleset: EQBank.ca
  src/chrome/content/rules/EQBank.ca.xml
Labels: top-100k

#15623 Create ruleset: Avidemux.org
  src/chrome/content/rules/Avidemux.org.xml
Labels: top-1m

#15530 Create KissKissBankBank.com.xml
  src/chrome/content/rules/KissKissBankBank.com.xml
Labels: top-1m

#15689 Create ruleset: EatByDate.com
  src/chrome/content/rules/EatbyDate.com.xml
Labels: top-100k

#15697 Create ruleset: AutoBuzz.my
  src/chrome/content/rules/AutoBuzz.my.xml
Labels: top-1m

#15696 Create ruleset: DSF.my
  src/chrome/content/rules/DSF.my.xml
Labels: top-1m

#15333 Create Dro-s.com.xml [top-100k]
  src/chrome/content/rules/Dro-s.com.xml
Labels: top-1m

#15244 Create Ida2at.com.xml [top-100k]
  src/chrome/content/rules/Ida2at.com.xml
Labels: top-1m

#15559 Added ruleset for bundesdruckerei.de
  src/chrome/content/rules/Bundesdruckerei.de.xml
Labels: new-ruleset, top-1m

#15230 Create SpringfieldSpringfield.co.uk.xml [top-100k]
  src/chrome/content/rules/SpringfieldSpringfield.co.uk.xml
Labels: top-100k

#15371 [Banggood.com] New ruleset
  src/chrome/content/rules/Banggood.com.xml
Labels: new-ruleset, top-1k

#15744 Fix MCB in WolframAlpha widgets
  src/chrome/content/rules/WolframAlpha.com.xml
Labels: ruleset-bug, top-10k

#15172 Create Kizunaai.com.xml
  src/chrome/content/rules/Kizunaai.com.xml
Labels: broken MCB, new-ruleset, top-1m

#15669 Create ruleset: IMSLP
  src/chrome/content/rules/IMSLP.xml
Labels: new-ruleset, top-10k

#15134 Add ruleset: mentalfloss.com
  src/chrome/content/rules/Mentalfloss.com.xml
Labels: new-ruleset, top-10k

#15653 Update ruleset: Cheezburger
  src/chrome/content/rules/Cheezburger.xml
Labels: ruleset-bug, top-10k

#15695 Create ruleset: FoodRepublic.com
  src/chrome/content/rules/FoodRepublic.com.xml
Labels: new-ruleset, top-100k

#15712 Update ruleset: Eclipse.org
  src/chrome/content/rules/Eclipse.xml
  src/chrome/content/rules/EclipseCon.org.xml
Labels: ruleset-enhancement, top-10k

#15321 Create CrowdJustice.com.xml [top-1m]
  src/chrome/content/rules/CrowdJustice.com.xml
Labels: new-ruleset, top-1m

#15305 Create Shatiby.edu.sa.xml
  src/chrome/content/rules/Shatiby.edu.sa.xml
Labels: new-ruleset

#15232 Create CrooksAndLiars.com.xml [top-100k]
  src/chrome/content/rules/CrooksAndLiars.com.xml
Labels: new-ruleset, top-100k

#15226 Create NZF.org.uk.xml
  src/chrome/content/rules/NZF.org.uk.xml
Labels: new-ruleset

#15080 Create OADOI.org.xml
  src/chrome/content/rules/OADOI.org.xml
  src/chrome/content/rules/Unpaywall.org.xml
Labels: new-ruleset

#15711 Update ruleset: Wargaming
  src/chrome/content/rules/Wargaming.net.xml
  src/chrome/content/rules/Wargaming.xml
  src/chrome/content/rules/World-of-Warships.xml
Labels: top-10k

#15683 Create ruleset: Team Liquid
  src/chrome/content/rules/Team-Liquid.xml
Labels: top-10k

#15680 Create ruleset: TotalProSports.com
  src/chrome/content/rules/TotalProSports.com.xml
Labels: top-100k

#15681 Create ruleset: RefinedGuy.com
  src/chrome/content/rules/RefinedGuy.com.xml
Labels: top-1m

#15679 Create IraqBodyCount.org.xml
  src/chrome/content/rules/IraqBodyCount.org.xml
Labels: top-1m

#15308 Add ruleset: Sgtools.info
  src/chrome/content/rules/Sgtools.info.xml
Labels: top-1m

#14414 Added ruleset for robeha.de
  src/chrome/content/rules/ROBEHA.de.xml
Labels: new-ruleset

#15030 Added ruleset for phantafriends.de
  src/chrome/content/rules/PhantaFriends.de.xml
Labels: new-ruleset

#14529 Added ruleset for bundesimmobilien.de
  src/chrome/content/rules/Bundesimmobilien.de.xml
Labels: new-ruleset, top-1m

#15207 Create Nightmarish-Dream.ru.xml
  src/chrome/content/rules/Nightmarish-Dream.ru.xml
  utils/ruleset-whitelist.csv
Labels: top-1m

#15741 [Gardening Know How.com] New ruleset
  src/chrome/content/rules/Gardening-Know-How.com.xml
Labels: new-ruleset, top-10k

#15515 Updates test sites for Solus-Project.com and makes it deafult to on
  src/chrome/content/rules/Solus-Project.com.xml
Labels: top-100k

#15264 Re-enable trezor.io
  src/chrome/content/rules/trezor.io.xml
Labels: ruleset-bug, top-100k

#15309 Add ruleset: high.fi
  src/chrome/content/rules/High.fi.xml
Labels: new-ruleset, top-1m

#14408 Added ruleset for bgr.de
  src/chrome/content/rules/BGR.de.xml
Labels: new-ruleset

#14181 Updated serienjunkies.de ruleset.
  src/chrome/content/rules/Serienjunkies.de.xml
Labels: ruleset-enhancement, top-100k

#15694 Create ruleset: MOMOClothing.co.uk
  src/chrome/content/rules/MOMOClothing.co.uk.xml
Labels: new-ruleset

#15259 sprinklecontent.com
  src/chrome/content/rules/sprinklecontent.com.xml
Labels: top-1m

#14381 Added ruleset for FMSA.de
  src/chrome/content/rules/FMSA.de.xml
Labels: new-ruleset

#15297 [EverydayGiftCards.com.au] New ruleset
  src/chrome/content/rules/EverydayGiftCards.com.au.xml
  src/chrome/content/rules/Woolworths.com.au.xml
Labels: new-ruleset, top-10k

#15641 Create GetOutline.org.xml
  src/chrome/content/rules/GetOutline.org.xml
  src/chrome/content/rules/GoogleServices.xml
Labels: new-ruleset, top-1m

#15605 Update aastocks.com.xml
  src/chrome/content/rules/aastocks.com.xml
Labels: ruleset-bug, top-10k

#15652 Update ruleset: BGR.com
  src/chrome/content/rules/BGR.com.xml
Labels: new-ruleset, top-10k

#15749 Create ruleset: QUADAtYork.ca
  src/chrome/content/rules/QUADAtYork.ca.xml
Labels: new-ruleset
