Repository EFForg/https-everywhere, pull requests merged in 2018-12, with the labels that each got.

#17097 Add ruleset for fhem.de
  src/chrome/content/rules/FHEM.de.xml
Labels: top-1m

#17104 Update Adobe.xml
  src/chrome/content/rules/Adobe-mismatches.xml
  src/chrome/content/rules/Adobe.xml
Labels: top-100

#17115 Create Footprintcalculator.org.xml
  src/chrome/content/rules/FootprintCalculator.org.xml
Labels: top-1m

#17110 Create Taranis.news.xml
  src/chrome/content/rules/Taranis.news.xml
Labels: top-1m

#16573 Add Seamonkey-project.org.xml
  src/chrome/content/rules/Seamonkey-project.org.xml
Labels: new-ruleset, top-1m

#16576 Add Quassel-irc.org.xml
  src/chrome/content/rules/Quassel-irc.org.xml
Labels: new-ruleset

#15871 Re-enable Deluge.xml
  src/chrome/content/rules/Deluge-torrent.org.xml
Labels: top-100k

#15874 Add Colordiff.org.xml
  src/chrome/content/rules/Colordiff.org.xml
Labels: new-ruleset

#16452 Update ruleset: Wall Street Journal
  src/chrome/content/rules/Wall-Street-Journal.xml
Labels: top-1k

#17112 Create SocalistWorker.org.xml
  src/chrome/content/rules/SocialistWorker.org.xml
Labels: new-ruleset, top-1m

#17125 Update ruleset: RaceForward.org
  src/chrome/content/rules/RaceForward.org.xml
  src/chrome/content/rules/Race_Forward.org.xml
Labels: top-1m

#15872 Add Qemu.org.xml
  src/chrome/content/rules/Qemu.org.xml
Labels: new-ruleset, top-1m

#17030 Create Invidio.us.xml
  src/chrome/content/rules/Invidio.us.xml
Labels: top-1m

#17122 Update ruleset: Oracle
  src/chrome/content/rules/Oracle.xml
Labels: top-1k

#17117 Update Intel.xml and Intel.co.uk.xml
  src/chrome/content/rules/Intel-mismatches.xml
  src/chrome/content/rules/Intel.co.uk.xml
  src/chrome/content/rules/Intel.xml
Labels: top-1k

#17108 Update Weibo.com.xml
  src/chrome/content/rules/Sina.com.cn.xml
  src/chrome/content/rules/Weibo.com-mixedcontent.xml
  src/chrome/content/rules/Weibo.com.xml
Labels: top-100

#17124 Update ruleset: Wall Street Journal
  src/chrome/content/rules/Wall-Street-Journal.xml
Labels: top-1k

#17121 Update ruleset: Consumer Reports
  src/chrome/content/rules/ConsumerReports.xml
  src/chrome/content/rules/Consumer_Reports.com-falsemixed.xml
  src/chrome/content/rules/RightNow-clients.xml
Labels: top-1k

#17096 Add manpages.ubuntu.com
  src/chrome/content/rules/Ubuntu.xml
Labels: ruleset-enhancement, top-10k

#16586 Update Musl-libc.org.xml
  src/chrome/content/rules/Musl-libc.org.xml
Labels: ruleset-enhancement

#17127 Create SlidePlayer.fr.xml
  src/chrome/content/rules/SlidePlayer.fr.xml
Labels: top-100k

#17119 Create GMPG.org.xml
  src/chrome/content/rules/GMPG.org.xml
Labels: top-1m

#16716 Update ruleset: mheducation.com.xml
  src/chrome/content/rules/mheducation.com.xml
Labels: top-1k

#17105 Re-activate and Update Walmart.com.xml
  src/chrome/content/rules/Walmart.com.xml
Labels: top-1k

#17140 Create ruleset: pop2imap.com
  src/chrome/content/rules/Pop2imap.com.xml
Labels: top-1m

#15242 Add ruleset: Tsumino.com (nsfw)
  src/chrome/content/rules/Tsumino.com.xml
Labels: top-10k

#17154 Update Ruby-China.org.xml
  src/chrome/content/rules/Ruby-China.org.xml
Labels: top-100k

#17120 Update ruleset: RightNow
  src/chrome/content/rules/RightNow.xml
Labels: top-1m

#16369 Create Shinobi.jp.xml
  src/chrome/content/rules/Shinobi.jp.xml
Labels: top-10k

#17153 Update OSChina.net.xml
  src/chrome/content/rules/OSChina.net.xml
Labels: top-10k

#17161 Update Baidu.xml
  src/chrome/content/rules/Baidu.xml
Labels: top-100

#17165 Remove NVidia-mismatches.xml and Update NVidia.xml
  src/chrome/content/rules/NVidia-mismatches.xml
  src/chrome/content/rules/NVidia.xml
Labels: top-1k

#17164 Re-activate and Update Okta.com.xml
  src/chrome/content/rules/Okta.com.xml
Labels: top-1k

#17131 Add ruleset for x.org
  src/chrome/content/rules/X.Org.xml
Labels: top-1m

#17149 Update ruleset: m2ch.hk
  src/chrome/content/rules/m2ch.hk.xml
Labels: top-1m

#17176 Re-activate and Update 7-Eleven.com.xml
  src/chrome/content/rules/7-Eleven.com.xml
Labels: ruleset-bug, top-100k

#17177 Update QQ.xml
  src/chrome/content/rules/QQ.com-Problematic.xml
  src/chrome/content/rules/QQ.com-mixedcontent.xml
  src/chrome/content/rules/QQ.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100

#17179 Re-activate and Update Vox related rulesets
  src/chrome/content/rules/Vox.com.xml
  src/chrome/content/rules/voxmedia.com-resources.xml
Labels: top-10k

#17180 Re-activate and Update Nikkei.com.xml
  src/chrome/content/rules/Nikkei.com.xml
Labels: top-1k

#17178 Re-activate and Update Economist.xml
  src/chrome/content/rules/Economist.xml
Labels: top-10k

#17182 Re-activate and Update Metro.co.uk.xml
  src/chrome/content/rules/Metro.co.uk.xml
  src/chrome/content/rules/Metro.xml
Labels: top-10k

#16649 add spiegel-de subdomain
  src/chrome/content/rules/Spiegel.xml
Labels: needs revision, top-1k

#17172 Add Viazul.com.xml
  src/chrome/content/rules/Viazul.com.xml
Labels: new-ruleset

#17163 Re-activate and Update UOL.xml
  src/chrome/content/rules/UOL.xml
Labels: top-10k

#17056 Simplify and Update UNM.edu.xml
  src/chrome/content/rules/UNM.edu-falsemixed.xml
  src/chrome/content/rules/UNM.edu-problematic.xml
  src/chrome/content/rules/UNM.edu.xml
  src/chrome/content/rules/UNM.xml
Labels: ruleset-enhancement, top-10k

#17109 Remove GS-media.de.xml and Update GameSports.net.xml
  src/chrome/content/rules/GS-media.de.xml
  src/chrome/content/rules/GameSports.net-falsemixed.xml
  src/chrome/content/rules/GameSports.net.xml
Labels: ruleset-bug

#17181 Re-activate and Update WP.pl.xml
  src/chrome/content/rules/WP.pl-problematic.xml
  src/chrome/content/rules/WP.pl.xml
Labels: top-1k

#17184 Update Grinnell_College.xml
  src/chrome/content/rules/Grinnell_College.xml
Labels: ruleset-enhancement, top-100k

#17191 Re-activate and update DailyMail.co.uk.xml
  src/chrome/content/rules/DailyMail.co.uk.xml
  src/chrome/content/rules/Daily_Mail-problematic.xml
Labels: top-1k

#17188 Update Bitbucket.xml and Remove Bitbucket-mismatches.xml
  src/chrome/content/rules/Bitbucket-mismatches.xml
  src/chrome/content/rules/Bitbucket.xml
Labels: top-1k

#17187 Update FedEx.com.xml and remove FedEx.com-problematic.xml
  src/chrome/content/rules/FedEx.com-problematic.xml
  src/chrome/content/rules/FedEx.com.xml
Labels: top-1k

#17142 Add ruleset: FloridaPolitics.com
  src/chrome/content/rules/FloridaPolitics.com.xml
Labels: top-1m

#17190 Re-activate and update Zillow.com related rulesets
  src/chrome/content/rules/Zillow-problematic.xml
  src/chrome/content/rules/Zillow.com.xml
  src/chrome/content/rules/Zillow.xml
  src/chrome/content/rules/Zillowstatic.com.xml
Labels: top-1k
