Repository EFForg/https-everywhere, pull requests merged in 2018-02, with the labels that each got.

#14585 Update test/run_travis.sh, Fix Travis fetch-test
  test/run_travis.sh
Labels: High Priority, top-100k

#14604 [CollegeInfoGeek.com] Remove mixedcontent platform
  src/chrome/content/rules/collegeinfogeek.com.xml
Labels: top-100k

#14423 Bring docs into line with Markdown style guide
  docs/README.md
  docs/en_US/development.md
  docs/en_US/faq.md
  docs/en_US/rulesets.md
  docs/es/faq.md
Labels: docs

#14507 Split RCI.com.xml from Wyndham.xml
  src/chrome/content/rules/RCI.com.xml
  src/chrome/content/rules/Wyndham.xml
Labels: top-100k

#13991 [2ememain.be] New ruleset
  src/chrome/content/rules/2ememain.be.xml
Labels: top-10k

#14251 [Kijiji.it] New ruleset
  src/chrome/content/rules/Kijiji.it.xml
Labels: top-10k

#13990 [2dehands.be] New ruleset
  src/chrome/content/rules/2dehands.be.xml
Labels: top-10k

#14244 [Vivanuncios.com.mx] New ruleset
  src/chrome/content/rules/Vivanuncios.com.mx.xml
Labels: new-ruleset, top-100k

#14676 [Disqus] Fix duplicate test url
  src/chrome/content/rules/Disqus.xml
Labels: top-1k

#14672 Remove duplicated test urls from continuousphp.com.xml
  src/chrome/content/rules/continuousphp.com.xml
Labels: top-1m

#14671 Remove duplicated test urls from 2345.com.xml
  src/chrome/content/rules/2345.com.xml
Labels: top-100k

#14667 Remove duplicated test urls from 2ch.net.xml
  src/chrome/content/rules/2ch.net.xml
Labels: top-1k

#14664 Remove duplicated test urls from Mozilla.xml
  src/chrome/content/rules/Mozilla.xml
Labels: top-1k

#14662 Remove duplicated test urls from Twitter.xml
  src/chrome/content/rules/Twitter.xml
Labels: top-100

#14663 Remove duplicated test urls from PolyU.edu.hk.xml
  src/chrome/content/rules/PolyU.edu.hk.xml
Labels: top-100k

#14657 Update Firefox.net.cn.xml
  src/chrome/content/rules/Firefox.net.cn.xml
Labels: top-1m

#14650 [Thompsonhotels.com] Default_off ruleset
  src/chrome/content/rules/Thompson_Hotels.com.xml
Labels: top-1m

#14648 [Vodafone.ie] Remove broken targets
  src/chrome/content/rules/Vodafone.ie.xml
Labels: top-100k

#14656 [AmazonAWS.com] Add exclusion for anvato-api-config
  src/chrome/content/rules/AmazonAWS.com.xml
Labels: top-100

#14670 Remove duplicated test urls from Flickr.xml
  src/chrome/content/rules/Flickr.xml
Labels: top-1k

#14669 Remove duplicated test urls from Washington_Times.xml
  src/chrome/content/rules/Washington_Times.xml
Labels: top-10k

#14651 [TMZ.com] Simplify ruleset
  src/chrome/content/rules/TMZ.com.xml
Labels: top-10k

#14637 Rename and Update PCGamer.com.xml, Fix #14516
  src/chrome/content/rules/PCGamer.com.xml
Labels: top-1k

#14649 [Where2GetIt.com] Remove broken rules and wildcard
  src/chrome/content/rules/Where2GetIt.com.xml
  src/chrome/content/rules/Where_2_Get_It.xml
Labels: top-1m

#14621 [SharedCount.com] Increase coverage
  src/chrome/content/rules/SharedCount.com.xml
  src/chrome/content/rules/Sharedcount.com-API.xml
Labels: top-1m

#14566 Create KyngChaos.com.xml
  src/chrome/content/rules/KyngChaos.com.xml
Labels: top-1m

#14706 [AmazonAWS.com] Add exclusion (fix #11640)
  src/chrome/content/rules/AmazonAWS.com.xml
Labels: top-100

#14658 Update PConline.xml
  src/chrome/content/rules/PConline.xml
Labels: top-100k

#14707 Fixed gentoo.org ruleset.
  src/chrome/content/rules/Gentoo.xml
Labels: top-100k

#14705 [Cloudfront.net] Add exclusion (fix #3021 and #5060)
  src/chrome/content/rules/Cloudfront.xml
Labels: top-1k

#14701 [JWPlatform.com] Fix exclusion pattern regex
  src/chrome/content/rules/JW_Platform.com.xml
Labels: top-1m

#14693 [StatusPage.io] Fix duplicated test url
  src/chrome/content/rules/StatusPage.io.xml
Labels: top-100k

#14692 [Shields.io] Remove extra test url
  src/chrome/content/rules/shields.io.xml
Labels: top-1m

#14688 Remove duplicated test urls from NYTimes-Problematic.xml
  src/chrome/content/rules/NYTimes-Problematic.xml
Labels: top-1k

#14686 Remove duplicated test urls from Youku.com.xml
  src/chrome/content/rules/Youku.com.xml
Labels: top-10k

#14631 [PeerJ.com] Simplify rule and securecookie
  src/chrome/content/rules/PeerJ.com.xml
  src/chrome/content/rules/PeerJ.xml
Labels: top-100k

#14638 [KISSmetrics.com] Simplify ruleset
  src/chrome/content/rules/KISSmetrics.xml
Labels: top-100k

#14589 Update iQiyi.com.xml
  src/chrome/content/rules/iQiyi.com.xml
Labels: top-1k

#14704 Create QLCrew.com.xml
  src/chrome/content/rules/QLCrew.com.xml
Labels: new-ruleset, top-1m

#14588 Update Qiyi.com.xml
  src/chrome/content/rules/Qiyi.com.xml
Labels: top-100k

#14563 [CDON] Remove cdon.se subdomains
  src/chrome/content/rules/CDON.COM.xml
  src/chrome/content/rules/cdon.se.xml
Labels: top-100k

#14697 Create DigitalAttackMap.com.xml
  src/chrome/content/rules/DigitalAttackMap.com.xml
Labels: top-1m

#14479 [HomeTheaterReview.com] Merge and simplify rulesets
  src/chrome/content/rules/HomeTheaterReview.com.xml
  src/chrome/content/rules/Home_Theater_Review.com-falsemixed.xml
  src/chrome/content/rules/Home_Theater_Review.com.xml
Labels: top-1m

#14416 Updated drillisch.de ruleset.
  src/chrome/content/rules/Drillisch.de.xml
Labels: top-1m

#14558 [Transifex.com] Add subdomains
  src/chrome/content/rules/Transifex.com.xml
  src/chrome/content/rules/Transifex.xml
Labels: top-1m

#14537 [OUmedicine.com] Add subdomains
  src/chrome/content/rules/Oumedicine.com.xml
Labels: top-1m

#14601 Update Centralfield.com.xml
  src/chrome/content/rules/Centralfield.com.xml
Labels: top-1m

#14109 [Gumtree.com] Re-enable ruleset and add subdomains
  src/chrome/content/rules/Gumtree.com.xml
  src/chrome/content/rules/gumtree.com.xml
Labels: failing tests, needs test coverage update, top-10k

#14690 Add ruleset for Blogtrottr.com
  src/chrome/content/rules/Blogtrottr.com.xml
Labels: new-ruleset

#14557 Update yousuu.com.xml
  src/chrome/content/rules/yousuu.com.xml
Labels: top-100k

#14606 Update AndroidPolice.com
  src/chrome/content/rules/AndroidPolice.xml
Labels: top-10k

#14379 Add dhbw-mannheim.de
  src/chrome/content/rules/dhbw-mannheim.de.xml
Labels: top-1m

#14732 [AmazonAWS.com] Add exclusion (fix #14731)
  src/chrome/content/rules/AmazonAWS.com.xml
Labels: top-100

#14709 Add ruleset for cheatbook.de
  src/chrome/content/rules/Cheatbook.de.xml
Labels: new-ruleset, top-100k

#14740 [GoogleAPIs.com] Add exclusion (fix #1828)
  src/chrome/content/rules/GoogleAPIs.xml
Labels: top-1k

#14745 add rule for Thunderbird.net
  src/chrome/content/rules/Thunderbird.net.xml
Labels: top-1m

#14530 Added ruleset for wetter.com
  src/chrome/content/rules/wetter.com.xml
Labels: top-10k

#14499 LongTail:
  src/chrome/content/rules/LongTail.xml
Labels: top-10k

#8192 redbubble.com: Remove obsolete exclusions
  src/chrome/content/rules/RedBubble.xml
Labels: ruleset-enhancement, top-10k

#14510 [Ticketmaster] Remove billettservice.no and lippulpalvelu subdomains
  src/chrome/content/rules/Ticketmaster.xml
Labels: top-1k

#14573 Update University-of-Waterloo.xml yet again
  src/chrome/content/rules/University-of-Waterloo.xml
Labels: top-10k

#14713 [Intercom.io] Reactivate ruleset
  src/chrome/content/rules/Intercom.io.xml
Labels: top-10k

#14694 [Tcl.tk] Add target and simplify rule
  src/chrome/content/rules/Tcl.tk.xml
Labels: top-100k

#13946 [CIMB Indonesia] Update domains
  src/chrome/content/rules/CIMB-Indonesia.xml
Labels: top-100k

#14227 [MoE.gov.my] New ruleset
  src/chrome/content/rules/MoE.gov.my.xml
Labels: top-10k

#14715 [BU.edu] Remove wildcard and add subdomains
  src/chrome/content/rules/BU.edu.xml
  src/chrome/content/rules/Boston_University.xml
Labels: top-10k

#14261 [Monster.com] Simplify ruleset
  src/chrome/content/rules/Monster.com.xml
  src/chrome/content/rules/Monster.xml
Labels: ruleset-enhancement, top-10k

#14674 Update Pixiv.xml
  src/chrome/content/rules/Pixiv.xml
Labels: top-10k

#14498 Add ruleset for torontohydro.com
  src/chrome/content/rules/Torontohydro.com.xml
Labels: top-100k

#14590 Remove bcvs.ch subdomains from kantonalbanken.xml
  src/chrome/content/rules/kantonalbanken.xml
Labels: top-100k

#14700 [MusicBrainz.org] Add targets
  src/chrome/content/rules/MusicBrainz.org.xml
Labels: top-100k

#14696 Fixed and updated rsf.org ruleset.
  src/chrome/content/rules/RSF.org-falsemixed.xml
  src/chrome/content/rules/Reporters_Without_Borders.xml
Labels: top-100k

#14681 Update tagesschau.de
  src/chrome/content/rules/tagesschau.de.xml
Labels: top-10k

#14522 Create BirdLife.org.xml
  src/chrome/content/rules/BirdLife.org-problematic.xml
  src/chrome/content/rules/BirdLife.org.xml
Labels: new-ruleset, top-100k

#14639 Simplify University-of-California-San-Diego.xml
  src/chrome/content/rules/UCSD.edu-self-signed.xml
  src/chrome/content/rules/UCSD.edu.xml
  src/chrome/content/rules/University-of-California-San-Diego.xml
Labels: top-10k

#14760 [IMDb] Add targets
  src/chrome/content/rules/IMDB.xml
Labels: top-100

#14750 [Heavy.com] Add target (fix #13157)
  src/chrome/content/rules/Heavy.com.xml
Labels: top-10k

#14718 [Blogspot] Add exclusion (fix #8113)
  src/chrome/content/rules/Blogspot.com_blogs.xml
Labels: ruleset-bug, top-100

#14632 [Auctiva.com] Simplify rule
  src/chrome/content/rules/Auctiva.com.xml
Labels: top-100k

#14763 Update derstandard.at.xml
  src/chrome/content/rules/derstandard.at.xml
Labels: top-10k

#14762 Update LinuxFoundation.xml
  src/chrome/content/rules/LinuxFoundation.xml
Labels: top-100k

#14758 [PlayerAttack.com] Simplify ruleset
  src/chrome/content/rules/Player-Attack.xml
  src/chrome/content/rules/PlayerAttack.com.xml
Labels: top-1m

#14719 [WolframAlpha.com.xml] Remove wildcard and broken rules
  src/chrome/content/rules/Wolfram.com.xml
  src/chrome/content/rules/WolframAlpha.com.xml
  src/chrome/content/rules/Wolfram_Alpha.xml
  src/chrome/content/rules/Wolfram_CDN.com.xml
  src/chrome/content/rules/Wolframcloud.com.xml
  src/chrome/content/rules/Wolframscience.com.xml
Labels: ruleset-bug, top-10k

#14401 Create SpringerNature.com.xml
  src/chrome/content/rules/SpringerNature.com.xml
Labels: new-ruleset, top-100k

#13998 Create Mashable.com.xml
  src/chrome/content/rules/Mashable.com.xml
  src/chrome/content/rules/mshcdn.com.xml
Labels: new-ruleset, top-1k

#14752 [InternetSociety.org] Simplify ruleset
  src/chrome/content/rules/ISOC.org.xml
  src/chrome/content/rules/Internet-Society.xml
  src/chrome/content/rules/InternetSociety.org.xml
Labels: top-100k

#14627 [ebay.com.sg] New ruleset
  src/chrome/content/rules/ebay.com.sg.xml
Labels: new-ruleset, top-100k

#13949 [CIMB Thailand] Re-enable ruleset
  src/chrome/content/rules/CIMB-Thailand.xml
Labels: top-1m

#14224 [Shopee.com.my] New ruleset
  src/chrome/content/rules/Shopee.com.my.xml
Labels: new-ruleset, top-10k

#14771 [ProstoVPN.org] Remove duplicate test url
  src/chrome/content/rules/ProstoVPN.org.xml
  src/chrome/content/rules/prostovpn.org.xml
Labels: top-1m

#14035 [cimb.com] Add subdomains and rename ruleset
  src/chrome/content/rules/CIMB-Malaysia.xml
  src/chrome/content/rules/CIMB.com.xml
Labels: top-10k

#14249 [Kijiji.ca] New ruleset
  src/chrome/content/rules/Kijiji.ca.xml
Labels: top-1k

#14756 Update Tello.xml
  src/chrome/content/rules/Tello.xml
Labels: top-1m

#14754 Update Amica.com.xml
  src/chrome/content/rules/Amica.com.xml
Labels: top-100k

#14055 [itradecimb.com.my] Move to a separate ruleset
  src/chrome/content/rules/iTradeCIMB.com.my.xml
Labels: top-100k

#14050 [cimbclicks.com.my] Add subdomains
  src/chrome/content/rules/CIMBClicks.com.my.xml
Labels: top-10k

#14471 Added ruleset for darc.de
  src/chrome/content/rules/DARC.de.xml
Labels: new-ruleset, top-1m

#14569 Added rulesets for sonarqube.org, sonarsource.com, sonarlint.org, son…
  src/chrome/content/rules/SonarCloud.io.xml
  src/chrome/content/rules/SonarLint.org.xml
  src/chrome/content/rules/SonarQube.org.xml
  src/chrome/content/rules/SonarSource.com.xml
Labels: new-ruleset, top-100k

#14053 [cimb-principal.com.my] Move to separate ruleset
  src/chrome/content/rules/CIMB-Principal.com.my.xml
Labels: top-1m

#14049 [cimbbank.com.my] Add subdomains
  src/chrome/content/rules/CIMBBank.com.my.xml
Labels: top-100k

#14068 [Maybank2e.com] New ruleset
  src/chrome/content/rules/Maybank2e.com.xml
Labels: top-1m

#14076 [KETrade.com.sg] New ruleset
  src/chrome/content/rules/KETrade.com.sg.xml
Labels: top-1m

#14710 Create ruleset for seriouseats.com
  src/chrome/content/rules/Seriouseats.com.xml
Labels: top-10k
