Repository EFForg/https-everywhere, pull requests merged in 2018-09, with the labels that each got.

#16454 Update ruleset: News Limited
  src/chrome/content/rules/News-Limited.xml
Labels: top-1k

#16457 Update ruleset: Marketwatch.com
  src/chrome/content/rules/Marketwatch.com.xml
Labels: top-1k

#16437 Create ruleset: SIRCorp.com
  src/chrome/content/rules/SIRCorp.com.xml
Labels: new-ruleset

#15646 Update ruleset: Adnxs.com
  src/chrome/content/rules/Adnxs.com.xml
Labels: top-100k

#16462 Update yikeweiqi.com.xml
  src/chrome/content/rules/yikeweiqi.com.xml
Labels: ruleset-enhancement

#14776 Create NatureCast.org.xml
  src/chrome/content/rules/NatureCast.org.xml
Labels: new-ruleset

#16531 Update and rename LiveInternet.xml to LiveInternet.ru.xml
  src/chrome/content/rules/Li.ru.xml
  src/chrome/content/rules/LiveInternet-falsemixed.xml
  src/chrome/content/rules/LiveInternet.ru.xml
  src/chrome/content/rules/LiveInternet.xml
  src/chrome/content/rules/Yadro.ru.xml
Labels: top-10k

#16476 Update cnblogs.com.xml
  src/chrome/content/rules/cnblogs.com.xml
Labels: top-1k

#16515 Update TouTiao.xml
  src/chrome/content/rules/TouTiao.xml
Labels: top-10k

#16535 Add reference to related rulesets
  src/chrome/content/rules/Motley-Fool.xml
Labels: top-10k

#16528 [PayPal.me] New ruleset
  src/chrome/content/rules/PayPal.me.xml
Labels: top-10k

#16518 Trivialize some obsolete CDN rewrites
  src/chrome/content/rules/360Cities.xml
  src/chrome/content/rules/GeekWire.com.xml
  src/chrome/content/rules/GeekWire.xml
  src/chrome/content/rules/PolitiFact.xml
  src/chrome/content/rules/PressPlus.xml
  src/chrome/content/rules/RebelMouse.com.xml
  src/chrome/content/rules/Tim_Minchin.com.xml
  src/chrome/content/rules/Vulture.com.xml
  src/chrome/content/rules/centralindex.com.xml
Labels: top-1m

#16544 Update QQ.xml
  src/chrome/content/rules/QQ.com-Problematic.xml
  src/chrome/content/rules/QQ.com-mixedcontent.xml
  src/chrome/content/rules/QQ.xml
Labels: top-100

#16565 Update ruleset: Nginx.org
  src/chrome/content/rules/Nginx.org.xml
Labels: top-100k

#16554 Add ruleset for bmu.de
  src/chrome/content/rules/BMU.de.xml
Labels: top-100k

#16553 Add ruleset for Bundesgesundheitsministerium.de
  src/chrome/content/rules/Bundesgesundheitsministerium.de.xml
Labels: top-1m

#16465 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: top-10k

#16003 [Crisco.com] New ruleset
  src/chrome/content/rules/Crisco.com.xml
Labels: top-1m

#2033 Add rules for franckgirard.net
  src/chrome/content/rules/franckgirard.net.xml
Labels: needs revision, new-ruleset

#15355 Add ruleset: AirMalta.com
  src/chrome/content/rules/AirMalta.com.xml
Labels: new-ruleset, top-100k

#15905 Create ruleset: BrooksBrothers.com
  src/chrome/content/rules/BrooksBrothers.com.xml
Labels: top-100k

#16425 Update hsbc.com.hk, add more subdomains
  src/chrome/content/rules/hsbc.com.hk.xml
Labels: ruleset-enhancement, top-10k

#16451 Create ruleset: Aviary.com
  src/chrome/content/rules/Aviary.com.xml
Labels: new-ruleset, top-1m

#16449 Create ruleset: DATACM.com
  src/chrome/content/rules/DATACM.com.xml
Labels: new-ruleset

#16435 Update ruleset: AT&T
  src/chrome/content/rules/ATandT.xml
Labels: ruleset-enhancement, top-1k

#16566 Update ruleset: IGN
  src/chrome/content/rules/IGN-problematic.xml
  src/chrome/content/rules/IGN.xml
Labels: top-1k

#16399 Create Islam21c.com.xml
  src/chrome/content/rules/Islam21c.com.xml
Labels: top-1m

#16374 Update Eastday.com.xml
  src/chrome/content/rules/Eastday.com.xml
Labels: ruleset-enhancement, top-1k

#16426 Create abpchina.org.xml
  src/chrome/content/rules/abpchina.org.xml
Labels: broken MCB, new-ruleset

#16578 Add Graphviz.org.xml
  src/chrome/content/rules/Graphviz.org.xml
Labels: new-ruleset, top-100k

#15429 Update rulesets: NYDailyNews
  src/chrome/content/rules/Cloudfront.xml
  src/chrome/content/rules/NYDailyNews.com-falsemixed.xml
  src/chrome/content/rules/NYDailyNews.xml
Labels: ruleset-enhancement, top-10k

#16305 Updated apache.org ruleset
  src/chrome/content/rules/Apache.org-falsemixed.xml
  src/chrome/content/rules/Apache.xml
Labels: needs test coverage update, top-10k

#16556 Add ruleset for bmz.de
  src/chrome/content/rules/BMZ.de.xml
Labels: new-ruleset, top-1m

#16467 Update ruleset: Electronic Arts
  src/chrome/content/rules/Electronic-Arts.xml
Labels: ruleset-enhancement, top-1k

#16355 Update Sina.com.cn.xml
  src/chrome/content/rules/Sina.com.cn-mixedcontent.xml
  src/chrome/content/rules/Sina.com.cn.xml
Labels: top-100

#16474 Update ruleset: Real World OCaml.org
  src/chrome/content/rules/Real_World_OCaml.org.xml
Labels: ruleset-bug

#16591 Update expreview.com.xml
  src/chrome/content/rules/expreview.com.xml
Labels: top-10k

#16581 Add Gtk.org.xml
  src/chrome/content/rules/Gtk.org.xml
Labels: new-ruleset, top-100k

#16545 Update Ruleset for Comic Con
  src/chrome/content/rules/Comic-Con-Intl.xml
Labels: ruleset-bug, top-1m

#16588 Add Openjpeg.org.xml
  src/chrome/content/rules/Openjpeg.org.xml
Labels: new-ruleset

#16583 Add Libssh2.org.xml
  src/chrome/content/rules/Libssh2.org.xml
Labels: new-ruleset

#16621 Update Java.net.xml, fix #16611, fix #16612
  src/chrome/content/rules/Java.net.xml
Labels: top-100k

#16540 Add a script to trivialize a special form of securecookies
  src/chrome/content/rules/Acessoseguro.net.xml
  src/chrome/content/rules/BCGolf.com-mismatches.xml
  src/chrome/content/rules/Bauhaus-University_Weimar.xml
  src/chrome/content/rules/ChampionCasino.net.xml
  src/chrome/content/rules/CloudSwitch.xml
  src/chrome/content/rules/Common_Criteria_Portal.xml
  src/chrome/content/rules/DM_tracker.com.xml
  src/chrome/content/rules/Demdex.com.xml
  src/chrome/content/rules/Demdex.net.xml
  src/chrome/content/rules/EBlastEngine.com.xml
  src/chrome/content/rules/EUKhosting.xml
  src/chrome/content/rules/Easyspace.xml
  src/chrome/content/rules/George-Washington-University.xml
  src/chrome/content/rules/Google_App_Engine.xml
  src/chrome/content/rules/Hesecure.com.xml
  src/chrome/content/rules/Higher_Education_Academy.xml
  src/chrome/content/rules/IGrasp.xml
  src/chrome/content/rules/Ibiza-Rocks.xml
  src/chrome/content/rules/Instella_Platform.xml
  src/chrome/content/rules/Kayako-clients.xml
  src/chrome/content/rules/Law_School_Admission_Council.xml
  src/chrome/content/rules/ListrakBI.com.xml
  src/chrome/content/rules/LivePerson.net.xml
  src/chrome/content/rules/Merchantquest.net.xml
  src/chrome/content/rules/Mktoresp.com.xml
  src/chrome/content/rules/Mozdev-mismatches.xml
  src/chrome/content/rules/Musicmetric.xml
  src/chrome/content/rules/Myregisteredsite.com.xml
  src/chrome/content/rules/Net-Applications.xml
  src/chrome/content/rules/Network-Depot.xml
  src/chrome/content/rules/OVPN.xml
  src/chrome/content/rules/Omeda.xml
  src/chrome/content/rules/Open_Badges.xml
  src/chrome/content/rules/Osmo.xml
  src/chrome/content/rules/PayGarden.com.xml
  src/chrome/content/rules/Pritunl.com.xml
  src/chrome/content/rules/RIKEN.jp.xml
  src/chrome/content/rules/RNW.nl.xml
  src/chrome/content/rules/Razor_Servers.xml
  src/chrome/content/rules/Scania.xml
  src/chrome/content/rules/SharpSpring.xml
  src/chrome/content/rules/ShopCo.com.xml
  src/chrome/content/rules/Ssldomain.com.xml
  src/chrome/content/rules/Surfeasy.com.xml
  src/chrome/content/rules/TravelBlog.xml
  src/chrome/content/rules/University_of_Derby.xml
  src/chrome/content/rules/Velaro.xml
  src/chrome/content/rules/Web-servers.com.au.xml
  src/chrome/content/rules/WebEx-Communications.xml
  src/chrome/content/rules/Wrapadviser.co.uk.xml
  src/chrome/content/rules/Zissousecure.com.xml
  src/chrome/content/rules/vogogo.com.xml
  utils/ruleset-whitelist.csv
  utils/trivialize-rules/package.json
  utils/trivialize-rules/trivialize-cookie-rules.js
Labels: top-1k

#16585 Add Uclibc.org.xml
  src/chrome/content/rules/Uclibc.org.xml
Labels: new-ruleset

#16643 Update Speedtest.net, fix #16615
  src/chrome/content/rules/Speedtest.net.xml
Labels: top-1k

#15357 Add ruleset: FlyEdelweiss.com
  src/chrome/content/rules/FlyEdelweiss.com.xml
Labels: new-ruleset, top-1m

#16599 Add ruleset for bundespraesident.de
  src/chrome/content/rules/Bundespraesident.de.xml
Labels: top-1m

#15311 Add ruleset: wind.it
  src/chrome/content/rules/Wind.it.xml
Labels: new-ruleset, top-10k
