Repository EFForg/https-everywhere, pull requests merged in 2018-07, with the labels that each got.

#15240 typescriptlang.org
  src/chrome/content/rules/typescriptlang.org.xml
Labels: new-ruleset, top-100k

#15535 Create ruleset: Mono project and pronoun.is
  src/chrome/content/rules/Mono-project.xml
  src/chrome/content/rules/pronoun.is.xml
Labels: new-ruleset, top-100k

#15825 Create expreview.com.xml
  src/chrome/content/rules/expreview.com.xml
Labels: top-100k

#16000 Batch trivialize unnecessary amazonaws.com rewrites
  src/chrome/content/rules/Adbooth.net.xml
  src/chrome/content/rules/Couchbase.xml
  src/chrome/content/rules/Fine_Art_America.xml
  src/chrome/content/rules/Freshdesk.xml
  src/chrome/content/rules/FrostWire.xml
  src/chrome/content/rules/GetGlue.xml
  src/chrome/content/rules/HubSpot.com.xml
  src/chrome/content/rules/Huffington-Post.xml
  src/chrome/content/rules/Pardot.xml
  src/chrome/content/rules/PepperJam_Exchange.xml
  src/chrome/content/rules/PolitiFact.xml
  src/chrome/content/rules/SB-Nation.xml
  src/chrome/content/rules/TranslateThi.is.xml
  src/chrome/content/rules/Velvet_Cache.org.xml
  src/chrome/content/rules/Vzaar.xml
  src/chrome/content/rules/nlx.org.xml
  utils/ruleset-whitelist.csv
Labels: top-1k

#16079 [Convert-JPG-to-PDF.net] New ruleset
  src/chrome/content/rules/Convert-JPG-to-PDF.net.xml
Labels: top-100k

#16099 Re-activate Beatport.xml
  src/chrome/content/rules/Beatport.com.xml
  src/chrome/content/rules/Beatport.xml
Labels: top-10k
