Repository EFForg/https-everywhere, pull requests merged in 2018-08, with the labels that each got.

#16075 Update Weibo.com.xml
  src/chrome/content/rules/Weibo.com-mixedcontent.xml
  src/chrome/content/rules/Weibo.com.xml
Labels: top-100

#15982 Remove problematic protocol rewrite from YouVersion.xml
  src/chrome/content/rules/Bible.com.xml
  src/chrome/content/rules/BibleSociety.co.za.xml
  src/chrome/content/rules/YouVersion.com.xml
  src/chrome/content/rules/YouVersion.xml
Labels: ruleset-bug, top-10k

#15846 Update ThePirateBay.xml
  src/chrome/content/rules/ThePirateBay.xml
Labels: failing tests

#15108 add more Subdomains to Rubicon-Project ruleset
  src/chrome/content/rules/Rubicon-Project.xml
Labels: broken MCB, top-100k

#15664 Posta.sk
  src/chrome/content/rules/Posta.sk.xml
Labels: new-ruleset, top-100k

#16047 Add redirect for play.rust-lang.org
  src/chrome/content/rules/Rust-Lang.org.xml
Labels: top-100k

#16235 Create hko.gov.hk.xml
  src/chrome/content/rules/GovHK.xml
  src/chrome/content/rules/hko.gov.hk.xml
Labels: new-ruleset, top-10k

#16089 Added ruleset for ortenau.freifunk.net
  src/chrome/content/rules/Freifunk.xml
  src/chrome/content/rules/ortenau.freifunk.net.xml
Labels: top-1m

#16091 Added ruleset for techstage.de
  src/chrome/content/rules/TechStage.de.xml
Labels: top-100k

#16028 Update Sohu.com.xml
  src/chrome/content/rules/Sohu.com.xml
Labels: top-100

#15949 Added ruleset for bundeskartellamt.de
  src/chrome/content/rules/Bundeskartellamt.de.xml
Labels: top-1m

#16001 [Mosh.org] New ruleset
  src/chrome/content/rules/Mosh.org.xml
Labels: top-1m

#16238 Update CMBChina.com.xml
  src/chrome/content/rules/CMBChina.com.xml
Labels: top-10k

#16116 [Fool.sg] New ruleset
  src/chrome/content/rules/Motley-Fool-Singapore.xml
Labels: top-1m

#16115 [Fool.de] New ruleset
  src/chrome/content/rules/Motley-Fool-Germany.xml
Labels: top-1m

#16111 [Fool.com] Add subdomains and remove wildcard
  src/chrome/content/rules/Fool.com-falsemixed.xml
  src/chrome/content/rules/Motley-Fool.xml
Labels: top-10k

#15937 Added ruleset for bfr.bund.de
  src/chrome/content/rules/BfR.bund.de.xml
  src/chrome/content/rules/Verwaltung_Online.xml
Labels: top-100k

#15986 [The Iconic.com.au] Add subdomains and rename ruleset
  src/chrome/content/rules/The-Iconic.com.au.xml
  src/chrome/content/rules/The_Iconic.com.au.xml
Labels: top-100k

#15945 Update Vice.xml, add shop.vice.com
  src/chrome/content/rules/Vice-problematic.xml
  src/chrome/content/rules/Vice.xml
Labels: top-1k

#15920 Create ruleset: 680news.com
  src/chrome/content/rules/680news.com.xml
Labels: top-100k

#15642 [Verisign.com] Re-enable ruleset
  src/chrome/content/rules/Verisign.xml
Labels: top-100k

#16063 Create ruleset: MQTT.org
  src/chrome/content/rules/MQTT.org.xml
Labels: top-1m

#16031 Create ruleset: IITBooks.co.in
  src/chrome/content/rules/IITBooks.co.in.xml
Labels: top-1m

#16026 Add two other domains for Bangumi
  src/chrome/content/rules/Bgm.tv.xml
Labels: top-10k

#15975 Trivialize and update League_of_Legends.com.xml
  src/chrome/content/rules/League_of_Legends.com.xml
Labels: top-1k

#16048 Create ruleset: MTCCC.com
  src/chrome/content/rules/MTCCC.com.xml
Labels: top-1m

#15973 Trivialize and update Engineering.com.xml
  src/chrome/content/rules/Engineering.com.xml
Labels: top-100k

#16066 Create ruleset: Government Attic
  src/chrome/content/rules/Government-Attic.xml
  src/chrome/content/rules/Governmentattic.org.xml
Labels: top-1m

#15976 Rename and update AP.org.xml
  src/chrome/content/rules/AP.org.xml
  src/chrome/content/rules/Associated_Press.xml
Labels: top-10k

#16082 [Adyen.com] New ruleset
  src/chrome/content/rules/Adyen.com.xml
Labels: top-10k

#16245 Create dwnews.com-mixedcontent.xml
  src/chrome/content/rules/dwnews.com-mixedcontent.xml
  src/chrome/content/rules/dwnews.net.xml
Labels: top-10k

#15390 Create ruleset: openscad.org
  src/chrome/content/rules/openscad.org.xml
Labels: new-ruleset, top-1m

#15974 Re-activate and update NASA.gov.xml
  src/chrome/content/rules/NASA.gov.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#16287 Add Piwigo.com.xml
  src/chrome/content/rules/Piwigo.com.xml
Labels: new-ruleset, top-1m

#16286 Add Piwigo.org.xml
  src/chrome/content/rules/Piwigo.org.xml
Labels: new-ruleset, top-1m

#16130 Probios.sk
  src/chrome/content/rules/Probios.sk.xml
Labels: new-ruleset

#16006 [Taxify.eu] New ruleset
  src/chrome/content/rules/Taxify.eu.xml
Labels: top-100k

#16117 [foolcdn.com] Separate ruleset
  src/chrome/content/rules/Fool-CDN.com.xml
Labels: ruleset-enhancement

#16112 [Fool.com.au] Separate ruleset
  src/chrome/content/rules/Motley-Fool-Australia.xml
Labels: top-100k

#16114 [Fool.co.uk] Separate ruleset
  src/chrome/content/rules/Motley-Fool-UK.xml
Labels: top-1m

#15882 [STA Travel.com] New ruleset
  src/chrome/content/rules/STA-Travel.com.xml
Labels: top-100k

#16105 Create ruleset: Tokopedia.com
  src/chrome/content/rules/Tokopedia.com.xml
Labels: new-ruleset, top-1k

#16104 Create ruleset: Bukalapak.com
  src/chrome/content/rules/Bukalapak.com.xml
Labels: new-ruleset, top-1k

#14151 Lijit.com:
  src/chrome/content/rules/Lijit.com.xml
Labels: top-100k

#15486 Use pytest instead of py.test per upstream recommendation, #dropthedot
  test/run_travis.sh
  test/selenium/requirements.txt
Labels: EFF, ruleset-testing

#15790 Remove libxml dependencies
  test/setup_travis.sh
Labels: ruleset-testing, toolchain

#15747 [rewriter.js] Update paths
  utils/rewriter/rewriter.js
Labels: bug

#15929 [benj.cloud] Add ruleset
  src/chrome/content/rules/benj.cloud.xml
  utils/ruleset-whitelist.csv
Labels: failing tests, new-ruleset

#16275 [Budget.no] New ruleset
  src/chrome/content/rules/Budget.no.xml
Labels: top-1m

#16277 [Budgetautonoleggio.it] New ruleset
  src/chrome/content/rules/Budgetautonoleggio.it.xml
Labels: top-1m

#16270 [Budget.ie] New ruleset
  src/chrome/content/rules/Budget.ie.xml
Labels: top-1m

#16264 [Budget.com.tr] New ruleset
  src/chrome/content/rules/Budget.com.tr.xml
Labels: top-1m

#16268 [Budget.es] New ruleset
  src/chrome/content/rules/Budget.es.xml
Labels: top-1m

#16253 [Budget.co.uk] New ruleset
  src/chrome/content/rules/Budget.co.uk.xml
Labels: top-1m

#16265 [Budget.de] New ruleset
  src/chrome/content/rules/Budget.de.xml
Labels: top-1m

#16269 [Budget.fr] New ruleset
  src/chrome/content/rules/Budget.fr.xml
Labels: top-1m

#16177 [Avisautonoleggio.it] New ruleset
  src/chrome/content/rules/Avisautonoleggio.it.xml
Labels: top-1m

#16176 [Avis.tc] New ruleset
  src/chrome/content/rules/Avis.tc.xml
Labels: top-1m

#16173 [Avis.no] New ruleset
  src/chrome/content/rules/Avis.no.xml
Labels: top-1m

#16174 [Avis.pl] New ruleset
  src/chrome/content/rules/Avis.pl.xml
Labels: top-1m

#16172 [Avis.nl] New ruleset
  src/chrome/content/rules/Avis.nl.xml
Labels: top-1m

#16139 [Avis.be] New ruleset
  src/chrome/content/rules/Avis.be.xml
Labels: top-1m

#16141 [Avis.ch] New ruleset
  src/chrome/content/rules/Avis.ch.xml
Labels: top-1m

#16140 [Avis.ca] New ruleset
  src/chrome/content/rules/Avis.ca.xml
Labels: top-1m

#16163 [Avis.com.tr] New ruleset
  src/chrome/content/rules/Avis.com.tr.xml
Labels: top-1m

#16143 [Avis.co.il] New ruleset
  src/chrome/content/rules/Avis.co.il.xml
Labels: top-1m

#16145 [Avis.co.uk] New ruleset
  src/chrome/content/rules/Avis.co.uk.xml
Labels: top-100k

#16150 [Avis.com.co] New ruleset
  src/chrome/content/rules/Avis.com.co.xml
Labels: top-1m

#16146 [Avis.co.za] New ruleset
  src/chrome/content/rules/Avis.co.za.xml
Labels: top-1m

#16137 [Avis-Thailand.com] New ruleset
  src/chrome/content/rules/Avis-Thailand.com.xml
Labels: top-1m

#16136 [Avis-Taiwan.com] New ruleset
  src/chrome/content/rules/Avis-Taiwan.com.xml
Labels: top-1m

#16373 [cloud3.me] Add ruleset
  src/chrome/content/rules/cloud3.me.xml
Labels: new-ruleset

#16357 Add archive.openwrt.org
  src/chrome/content/rules/OpenWRT.xml
Labels: ruleset-enhancement

#16032 Create ruleset: CrackSAT.net
  src/chrome/content/rules/CrackSAT.net.xml
Labels: top-1m

#15934 Create ruleset: DifferenceBetween.info
  src/chrome/content/rules/DifferenceBetween.info.xml
Labels: top-100k

#15935 Create ruleset: CufonFonts.com
  src/chrome/content/rules/CufonFonts.com.xml
Labels: top-1m

#15936 Create ruleset: Typ.io
  src/chrome/content/rules/Typ.io.xml
Labels: top-1m

#16036 Create ruleset: CFINotebook.net
  src/chrome/content/rules/CFINotebook.net.xml
Labels: top-1m

#15915 Create ruleset: ConcreteConstruction.net
  src/chrome/content/rules/ConcreteConstruction.net.xml
Labels: top-1m

#15918 Create ruleset: PinchOfNom.com
  src/chrome/content/rules/PinchOfNom.com.xml
Labels: top-1m

#15656 Create ruleset: Hooch.net
  src/chrome/content/rules/Hooch.net.xml
Labels: top-100k

#15138 Add ruleset: memberhealthplan.com
  src/chrome/content/rules/Memberhealthplan.com.xml
Labels: top-1m

#15133 Add ruleset: landfall.se
  src/chrome/content/rules/Landfall.se.xml
Labels: top-1m

#15136 Add ruleset: bluerazor.com
  src/chrome/content/rules/Bluerazor.com.xml
Labels: top-1m

#15135 Add ruleset: trapologyboston.com
  src/chrome/content/rules/Trapologyboston.com.xml
Labels: top-1m

#15271 Add ruleset: Logdown.com
  src/chrome/content/rules/Logdown.com.xml
Labels: top-100k

#15496 Create ruleset: Omaha.com
  src/chrome/content/rules/Omaha.com.xml
Labels: top-100k

#16012 Create ruleset: DutyFreeIslandShop.com
  src/chrome/content/rules/DutyFreeIslandShop.com.xml
Labels: new-ruleset, top-1m

#15956 Create ruleset: PrimeHost.ca
  src/chrome/content/rules/PrimeHost.ca.xml
Labels: new-ruleset

#15942 Create ruleset: CertifiedAccessories.com
  src/chrome/content/rules/CertifiedAccessories.com.xml
Labels: broken MCB

#15836 Create ruleset: MORryde.com
  src/chrome/content/rules/MORryde.com.xml
Labels: broken MCB, new-ruleset, top-1m

#15833 Create ruleset: Joico.com
  src/chrome/content/rules/Joico.com.xml
Labels: new-ruleset, top-1m

#15504 Create ruleset: Danze.com
  src/chrome/content/rules/Danze.com.xml
Labels: new-ruleset

#15187 Add ruleset: gs1ca.org
  src/chrome/content/rules/Gs1ca.org.xml
Labels: new-ruleset, top-1m

#15337 Add ruleset: TheChronicleHerald.ca
  src/chrome/content/rules/TheChronicleHerald.ca.xml
Labels: new-ruleset, top-100k

#15803 Create ruleset: Marcusoft.net
  src/chrome/content/rules/Marcusoft.net.xml
Labels: new-ruleset

#16391 Update ruleset: TheSwanSanctuary.org
  src/chrome/content/rules/TheSwanSanctuary.org.uk.xml
Labels: ruleset-bug

#16004 [Loans.com.au] New ruleset
  src/chrome/content/rules/Loans.com.au.xml
Labels: top-1m

#15947 Create Koonoz.info.xml
  src/chrome/content/rules/Koonoz.info.xml
Labels: top-1m

#15650 Update and rename stackedit.io.xml to StackEdit.io.xml
  src/chrome/content/rules/StackEdit.io.xml
  src/chrome/content/rules/stackedit.io.xml
Labels: top-1m

#15898 Create IGCD.net.xml
  src/chrome/content/rules/IGCD.net.xml
Labels: top-1m

#15662 Create Ghisler.com.xml
  src/chrome/content/rules/Ghisler.com.xml
Labels: top-100k

#15865 Create Ejaaba.com.xml
  src/chrome/content/rules/Ejaaba.com.xml
Labels: top-100k

#15828 Add zadolba.li
  src/chrome/content/rules/Zadolba.li.xml
Labels: top-100k

#16395 Update Android.xml, add messages.android.com
  src/chrome/content/rules/Android.xml
Labels: ruleset-enhancement

#15139 Add ruleset: 1-800courier.com
  src/chrome/content/rules/1-800courier.com.xml
Labels: new-ruleset

#15985 [Zanbase.com] New ruleset
  src/chrome/content/rules/Zanbase.com.xml
Labels: new-ruleset, top-1m

#15197 Add ruleset: Freenom.com
  src/chrome/content/rules/Freenom.com.xml
Labels: new-ruleset, top-100k

#15830 Create trivial ruleset for nxbus.co.uk
  src/chrome/content/rules/NXBus.co.uk.xml
Labels: new-ruleset, top-1m

#16392 Update ruleset: Alteeve.ca
  src/chrome/content/rules/Alteeve.ca.xml
Labels: ruleset-enhancement

#16098 Re-activate Cubify.com.xml
  src/chrome/content/rules/Cubify.com.xml
  src/chrome/content/rules/Cubify.xml
Labels: ruleset-enhancement

#15143 Add ruleset: adidas.ca
  src/chrome/content/rules/Adidas.ca.xml
  utils/ruleset-whitelist.csv
Labels: failing tests, new-ruleset, top-100k

#15142 Add ruleset: reebok.ca
  src/chrome/content/rules/Reebok.ca.xml
  utils/ruleset-whitelist.csv
Labels: failing tests, new-ruleset, top-1m

#15417 Create ruleset: Shouldianswer.com
  src/chrome/content/rules/ShouldIAnswer.xml
Labels: new-ruleset, top-100k

#15962 Create MiKTEX.org.xml, fix #15960
  src/chrome/content/rules/MiKTEX.org.xml
Labels: new-ruleset, top-1m

#15965 Simplify and update CBS.xml, fix #12526
  src/chrome/content/rules/CBS-Sports-Network.xml
  src/chrome/content/rules/CBS.xml
  src/chrome/content/rules/CBSInteractive.co.uk.xml
  src/chrome/content/rules/CBSInteractive.com.au.xml
  src/chrome/content/rules/CBSInteractive.com.xml
  src/chrome/content/rules/CBSNews.com.xml
  src/chrome/content/rules/CBSStatic.com.xml
  src/chrome/content/rules/CBS_Store.xml
  src/chrome/content/rules/CBSi.com.au.xml
  src/chrome/content/rules/CBSimg.net.xml
  src/chrome/content/rules/CNET.com.au.xml
  src/chrome/content/rules/CNETFrance.fr.xml
  src/chrome/content/rules/FindArticles.com.xml
  src/chrome/content/rules/Giant_Bomb.com.xml
  src/chrome/content/rules/News.com.xml
  src/chrome/content/rules/com.com.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#16304 Added ruleset for fkfev.de
  src/chrome/content/rules/FKFeV.de.xml
Labels: new-ruleset
