Repository EFForg/https-everywhere, pull requests merged in 2018-11, with the labels that each got.

#17008 Create ruleset: CentraFoods.com
  src/chrome/content/rules/CentraFoods.com.xml
Labels: top-1m

#16924 HTTPS to HTTPS 40 Rules Refactor
  src/chrome/content/rules/AJC.com.xml
  src/chrome/content/rules/Aeriagames.xml
  src/chrome/content/rules/Cru.org.xml
  src/chrome/content/rules/DailyDot.xml
  src/chrome/content/rules/Epic-Systems.xml
  src/chrome/content/rules/Fasthosts.xml
  src/chrome/content/rules/First_Class_Magazine.se.xml
  src/chrome/content/rules/Intelliworks_Chat.com.xml
  src/chrome/content/rules/KKH.de.xml
  src/chrome/content/rules/Khalsa-Credit-Union.xml
  src/chrome/content/rules/Knappschaft-Bahn-See.xml
  src/chrome/content/rules/MoveOn.xml
  src/chrome/content/rules/Necuhb.xml
  src/chrome/content/rules/Pair-Networks.xml
  src/chrome/content/rules/Perfect_Audience.xml
  src/chrome/content/rules/VEVO.xml
  src/chrome/content/rules/Yimg.com.xml
  src/chrome/content/rules/basekit.com.xml
  src/chrome/content/rules/spectator.co.uk.xml
  src/chrome/content/rules/yWorks.com.xml
Labels: enhancement, ruleset-enhancement, top-1k

#17015 Update Your-Mailing-List-Provider.xml
  src/chrome/content/rules/Your-Mailing-List-Provider.xml
Labels: top-100k

#17011 Add ruleset: NumPy.org
  src/chrome/content/rules/NumPy.org.xml
Labels: top-100k

#16681 Create Alukah.net.xml
  src/chrome/content/rules/Alukah.net.xml
Labels: top-10k

#17043 Clean up HTTPS to HTTPS rulesets
  src/chrome/content/rules/AdultShopping.com.xml
  src/chrome/content/rules/BME.hu.xml
  src/chrome/content/rules/BME.hu_incomplete.xml
  src/chrome/content/rules/Blip.xml
  src/chrome/content/rules/CafePress.xml
  src/chrome/content/rules/Caltech.xml
  src/chrome/content/rules/Care-Net.xml
  src/chrome/content/rules/MYEDDEBT.com.xml
  src/chrome/content/rules/Plymouth-University.xml
  src/chrome/content/rules/SSSup.it.xml
  src/chrome/content/rules/Sberbank_of_Russia.xml
  src/chrome/content/rules/Telus.xml
  src/chrome/content/rules/cnv.com.xml
Labels: ruleset-testing, top-1k

#17038 [Webex.com] Add exclusion and tests (fix #17037)
  src/chrome/content/rules/WebEx-Communications.xml
  src/chrome/content/rules/Webex.com.xml
Labels: top-10k

#17024 Update Caltech.edu.xml
  src/chrome/content/rules/Caltech.edu.xml
Labels: top-10k

#17050 Update ProPublica.org.xml
  src/chrome/content/rules/ProPublica.org.xml
Labels: top-100k

#17003 Create ruleset: Zones.com
  src/chrome/content/rules/Zones.com.xml
Labels: top-1m

#16996 [smokefree.hk] New ruleset
  src/chrome/content/rules/smokefree.hk.xml
Labels: top-1m

#17028 Create No-Thank-You.de.xml
  src/chrome/content/rules/No-Thank-You.de.xml
Labels: new-ruleset

#16990 Update University-of-Exeter.xml, fix #16473
  src/chrome/content/rules/University-of-Exeter.xml
Labels: ruleset-enhancement, top-100k

#14071 [Maybank2u.com.ph] New ruleset
  src/chrome/content/rules/Maybank2u.com.ph.xml
Labels: needs revision, new-ruleset, top-1m

#17054 [NordVPN.com] Add subdomains
  src/chrome/content/rules/NordVPN.com.xml
Labels: top-10k

#15742 [ParcelPoint.com.au] New ruleset
  src/chrome/content/rules/ParcelPoint.com.au.xml
Labels: new-ruleset, top-1m

#14242 [Marktplaats.nl] Update subdomains and rename ruleset
  src/chrome/content/rules/Marktplaats.nl.xml
  src/chrome/content/rules/Marktplaats.xml
Labels: new-ruleset, top-10k

#15787 [QBE.com.au] New ruleset
  src/chrome/content/rules/QBE.com.au.xml
Labels: new-ruleset, top-1m

#14863 [Marktplaatsperskamer.nl] Move to a separate ruleset
  src/chrome/content/rules/Marktplaatsperskamer.nl.xml
Labels: ruleset-enhancement

#14862 [Marktplaats.com] Update subdomains
  src/chrome/content/rules/Marktplaats.com.xml
Labels: ruleset-enhancement

#16249 [Budget.ca] New ruleset
  src/chrome/content/rules/Budget.ca.xml
Labels: new-ruleset, top-1m

#16663 [Undraw.co] Add ruleset
  src/chrome/content/rules/undraw.co.xml
Labels: new-ruleset, top-1m

#17055 Add Freelibrary.org.xml
  src/chrome/content/rules/Freelibrary.org.xml
Labels: new-ruleset, top-1m

#17020 Update Telus.xml
  src/chrome/content/rules/Telus.xml
Labels: top-10k

#17021 Update AdultShopping.com.xml
  src/chrome/content/rules/AdultShopping.com.xml
Labels: top-1m

#17023 Update Care-Net.org.xml
  src/chrome/content/rules/Care-Net.org.xml
  src/chrome/content/rules/Care-Net.xml
Labels: top-1m

#14020 Add narsol.org
  src/chrome/content/rules/NARSOL.org.xml
  src/chrome/content/rules/NationalRSOL.org.xml
  src/chrome/content/rules/RSOLConference.org.xml
Labels: top-1m

#14179 Added ruleset for ekd.de
  src/chrome/content/rules/ekd.de.xml
Labels: top-1m

#14420 add rule for RMF FM
  src/chrome/content/rules/RMF.pl.xml
Labels: top-100k

#15164 Update Broadcasthe.net domains
  src/chrome/content/rules/Broadcasthe.net.xml
Labels: top-100k

#17067 Create ruleset: JSON Schema
  src/chrome/content/rules/JSON-Schema.org.xml
Labels: top-1m

#16246 [Budget.com] New ruleset
  src/chrome/content/rules/Budget.com.xml
Labels: top-100k

#15725 [iPay88.com] New ruleset
  src/chrome/content/rules/iPay88.com.xml
Labels: new-ruleset, top-1m

#16327 [realestate.com.au] New ruleset
  src/chrome/content/rules/realestate.com.au.xml
Labels: top-10k

#17059 Update Kiwix.org.xml
  src/chrome/content/rules/Kiwix.org.xml
Labels: ruleset-enhancement

#17066 Update ruleset: Legacy.com
  src/chrome/content/rules/Legacy.com.xml
Labels: top-10k

#16603 Create youth.cn.xml
  src/chrome/content/rules/youth.cn.xml
Labels: top-1k

#17073 Add ruleset for ruliweb.com
  src/chrome/content/rules/Ruliweb.com.xml
Labels: top-1k

#17071 Use latest stable node in travis
  .travis.yml
  chromium/package.json
Labels: ruleset-testing

#14913 [AmazonAWS.com] Add exclusion (fix #4510)
  src/chrome/content/rules/AmazonAWS.com.xml
Labels: ruleset-bug, top-100

#15367 Update ruleset: News Corporation
  src/chrome/content/rules/News-Corporation.xml
Labels: top-1k

#17089 Update ruleset: Microsoft Store
  src/chrome/content/rules/Microsoft_Store.xml
Labels: top-100
