Repository EFForg/https-everywhere, pull requests merged in 2019-01, with the labels that each got.

#16343 [Europcar.de] New ruleset
  src/chrome/content/rules/Europcar.de.xml
Labels: new-ruleset, top-100k

#17158 Create GoodSmile.info.xml
  src/chrome/content/rules/GoodSmile.info.xml
Labels: top-100k

#17065 Update ruleset: Digg
  src/chrome/content/rules/Digg.xml
Labels: top-10k

#17162 Create docin.xml
  src/chrome/content/rules/docin.xml
Labels: top-10k

#15875 Update Exim.org.xml
  src/chrome/content/rules/Exim.org.xml
Labels: top-1m

#16694 Create singyin.edu.hk.xml
  src/chrome/content/rules/singyin.edu.hk.xml
Labels: new-ruleset, top-1m

#16595 Remove wildcard from Sunrise.xml (fix #15862)
  src/chrome/content/rules/Sunrise.xml
Labels: ruleset-bug, top-100k

#17147 Add ruleset: Siciarz.net
  src/chrome/content/rules/Siciarz.net.xml
Labels: new-ruleset

#17156 Change HTTP Block language
  chromium/pages/popup/index.html
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#17233 Add Duply.net.xml
  src/chrome/content/rules/Duply.net.xml
Labels: new-ruleset

#17204 Reload current tab when enabling EASE mode, fix #16870
  chromium/pages/popup/ux.js
Labels: EASE

#15879 Update PostgreSQL.xml
  src/chrome/content/rules/PostgreSQL-self-signed.xml
  src/chrome/content/rules/PostgreSQL.xml
  src/chrome/content/rules/Postgresql.eu.xml
  src/chrome/content/rules/Postgresql.fr.xml
  src/chrome/content/rules/Postgresql.org.xml
  src/chrome/content/rules/Postgresql.us.xml
Labels: ruleset-enhancement, top-10k

#17234 Remove Network message for unknown hosts
  chromium/background-scripts/background.js
Labels: EASE

#15752 Update Nginx.org.xml
  src/chrome/content/rules/Nginx.org.xml
Labels: top-100k

#16632 Update ruleset: PostImage
  src/chrome/content/rules/PostImage.xml
Labels: top-10k

#16356 Update and rename Flyspray.org.xml
  src/chrome/content/rules/Flyspray.org.xml
  src/chrome/content/rules/flyspray.org.xml
Labels: ruleset-enhancement

#17232 Create Cucumber.io.xml
  src/chrome/content/rules/Cucumber.io.xml
Labels: new-ruleset

#16701 Update TI.com ruleset
  src/chrome/content/rules/TI.com-falsemixed.xml
  src/chrome/content/rules/Texas-Instruments.xml
  utils/ruleset-whitelist.csv
Labels: top-10k

#17254 Do not modify headers if EASE is disabled. fix #17253
  chromium/background-scripts/background.js
Labels: EASE

#17113 Update Fanli.com.xml
  src/chrome/content/rules/Fanli.com.xml
Labels: top-100k

#16580 Add Avahi.org.xml
  src/chrome/content/rules/Avahi.org.xml
Labels: new-ruleset

#16587 Update Mono-project.xml
  src/chrome/content/rules/Mono-project.xml
Labels: ruleset-enhancement, top-1m

#15753 Add X.org.xml
  src/chrome/content/rules/X.org.xml
Labels: top-1m

#17287 Remove X.org.xml in favor of X.Org.xml
  src/chrome/content/rules/X.org.xml
Labels: bug, high priority

#17294 Add Net-dns.org.xml
  src/chrome/content/rules/Net-dns.org.xml
Labels: new-ruleset

#17297 Add Offlineimap.org.xml
  src/chrome/content/rules/Offlineimap.org.xml
Labels: new-ruleset

#14769 Remove IP address in targets
  src/chrome/content/rules/Digiweb-self-signed.xml
  src/chrome/content/rules/LFC-Hosting.xml
  src/chrome/content/rules/Xxxbunker.com.xml
  utils/ruleset-whitelist.csv
Labels: top-100k

#17274 Disable "Show Counter" test (temporarily) for Chrome
  test/selenium/shim.py
  test/selenium/test_options.py
Labels: failing tests
