Repository EFForg/https-everywhere, pull requests merged in 2019-05, with the labels that each got.

#17674 Updated URL to new Atlas URL
  chromium/pages/popup/index.html
Labels: EFF, ui

#17854 New UX for HTTPS Everywhere: For Release
  chromium/background-scripts/background.js
  chromium/images/HTTPS-Everywhere-Logo.png
  chromium/images/icons/SettingsIcon.png
  chromium/images/icons/icon-active-128.png
  chromium/images/icons/icon-active-38.png
  chromium/images/icons/icon-active-48.png
  chromium/images/icons/icon-blocking-38.png
  chromium/images/icons/icon-disabled-38.png
  chromium/pages/popup/index.html
  chromium/pages/popup/style.css
  chromium/pages/popup/ux.js
  src/chrome/locale/en/https-everywhere.dtd
  test/selenium/test_popup.py
  test/selenium/util.py
Labels: ui

#17865 Release 2019.5.2.1
  chromium/manifest.json
  src/Changelog
  src/META-INF/manifest.mf
  src/META-INF/mozilla.rsa
  src/META-INF/mozilla.sf
  test/validations/special/duplicate-whitelist.txt
  utils/ruleset-whitelist.csv
Labels: EFF

#17874 Fix typo causing trustlogo.com unprotected in Comodo.xml
  src/chrome/content/rules/Comodo.xml
  utils/ruleset-whitelist.csv
Labels: top-10k

#17872 Update Traction-Digital.com.xml, remove unused rules
  src/chrome/content/rules/Traction-Digital.com.xml
Labels: ruleset-enhancement

#17875 Update business.gov.au.xml
  src/chrome/content/rules/BusinessAU.xml
  src/chrome/content/rules/business.gov.au.xml
Labels: ruleset-enhancement, top-10k

#17889 Fix typo causing *.nexway.com unprotected
  src/chrome/content/rules/Nexaway.xml
  src/chrome/content/rules/Nexway.com.xml
Labels: top-1m

#17905 Fix typo causing *.redferret.net unprotected
  src/chrome/content/rules/RedFerret.net.xml
  src/chrome/content/rules/Red_Ferret.xml
Labels: ruleset-enhancement

#17899 Add LuaJIT.org.xml
  src/chrome/content/rules/LuaJIT.org.xml
Labels: new-ruleset

#17909 Update AkademikerForsakring.se.xml (remove last non-punycode unicode domain)
  src/chrome/content/rules/AkademikerForsakring.se.xml
Labels: ruleset-enhancement

#17878 Update CadSoft.xml
  src/chrome/content/rules/CadSoft.de.xml
  src/chrome/content/rules/CadSoft.xml
Labels: ruleset-enhancement

#17869 Rename and Update BlueCava.com.xml
  src/chrome/content/rules/BlueCava.com.xml
  src/chrome/content/rules/BlueCava.xml
Labels: ruleset-enhancement

#17911 UI Patches for Immediate fixes
  chromium/images/icons/SettingsIcon.png
  chromium/pages/cancel/index.html
  chromium/pages/options/index.html
  chromium/pages/options/ux.js
  chromium/pages/popup/index.html
  chromium/pages/popup/style.css
  chromium/pages/popup/ux.js
  test/selenium/test_options.py
Labels: high priority, ui

#17913 Update Instagr.am.xml
  src/chrome/content/rules/Instagr.am.xml
Labels: ruleset-enhancement

#17919 Properly change ON/OFF switch description, fix #17891
  chromium/pages/popup/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#17921 Update CamelCamelCamel ruleset
  src/chrome/content/rules/CamelCamelCamel.com.xml
  src/chrome/content/rules/Camelcamelcamel.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-10k

#17926 Update Tapatalk.xml
  src/chrome/content/rules/Tapatalk.com.xml
  src/chrome/content/rules/Tapatalk.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-10k

#17922 Update MoveOn.xml
  src/chrome/content/rules/MoveOn.org.xml
  src/chrome/content/rules/MoveOn.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-100k

#17873 Remove snapping redirect for ActBlue.com.xml
  src/chrome/content/rules/ActBlue.com.xml
  src/chrome/content/rules/ActBlue.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-10k

#17914 Update and rename Free_Press.xml to FreePress.net.xml
  src/chrome/content/rules/FreePress.net.xml
  src/chrome/content/rules/Free_Press.xml
Labels: amazon-s3-2020, ruleset-enhancement

#17924 Update Vcommerce.com.xml
  src/chrome/content/rules/Vcommerce.com.xml
  src/chrome/content/rules/Vcommerce.xml
Labels: amazon-s3-2020, ruleset-enhancement

#17925 Update Linksys.xml
  src/chrome/content/rules/Linksys.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-100k

#17923 Update DocumentCloud.xml
  src/chrome/content/rules/DocumentCloud.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-100k

#17940 Delete AdExcite.xml, gone from DNS
  src/chrome/content/rules/AdExcite.xml
Labels: amazon-s3-2020

#17941 Delete highways.gov.uk.xml, gone from dns
  src/chrome/content/rules/GOV.UK.xml
  src/chrome/content/rules/highways.gov.uk.xml
  utils/ruleset-whitelist.csv
Labels: amazon-s3-2020

#17942 Update Translation Strings Properly
  chromium/pages/popup/index.html
  chromium/pages/popup/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#17846 [BU.edu] Remove securecookie (fix #17838)
  src/chrome/content/rules/BU.edu.xml
Labels: ruleset-enhancement, top-10k

#17818 Add ruleset for DidierStevens.com
  src/chrome/content/rules/DidierStevens.xml
Labels: new-ruleset

#17907 Run npm audit fix on hsts-prune
  utils/hsts-prune/package-lock.json
Labels: high priority, ruleset-testing

#17953 Delete News_Distribution_Network.xml, on sale
  src/chrome/content/rules/News_Distribution_Network.xml
Labels: amazon-s3-2020

#17948 Delete Cloud-Privacy.xml, gone from dns
  src/chrome/content/rules/Cloud-Privacy.xml
Labels: amazon-s3-2020

#17954 Fix counter show number of experimental rulesets
  chromium/pages/popup/ux.js
Labels: ui

#17952 Amend test for stable rules
  test/selenium/test_popup.py
Labels: toolchain

#17877 Fix typo causing abccommercial.com unprotected
  src/chrome/content/rules/ABC-Online.xml
Labels: ruleset-enhancement, top-10k

#17665 Add Saveyourinternet.eu.xml
  src/chrome/content/rules/Saveyourinternet.eu.xml
Labels: new-ruleset, top-100k

#17947 Rename and update OpenSecrets.org.xml
  src/chrome/content/rules/Center-for-Responsive-Politics.xml
  src/chrome/content/rules/OpenSecrets.org.xml
Labels: amazon-s3-2020, top-100k

#17946 Re-activate and update JList.com.xml
  src/chrome/content/rules/JList.com.xml
Labels: amazon-s3-2020, top-100k

#17888 Update Weather Underground related rulesets
  src/chrome/content/rules/Weather-Underground.xml
  src/chrome/content/rules/Wunderground.com.xml
  src/chrome/content/rules/Wxug.com.xml
Labels: ruleset-enhancement, top-1k

#17959 Added ruleset for Equiac.com
  src/chrome/content/rules/Equiac.com.xml
Labels: top-1m

#13408 Added ruleset for as250.net
  src/chrome/content/rules/as250.net.xml
Labels: failing tests

#15363 Create ruleset: Tvp.pl
  src/chrome/content/rules/Tvp.pl.xml
Labels: failing tests, needs revision, new-ruleset, top-10k

#17849 [Communities.gov.uk] Remove broken target (fix #17845)
  src/chrome/content/rules/communities.gov.uk.xml
Labels: ruleset-enhancement

#17968 Create zimuku.la.xml
  src/chrome/content/rules/zimuku.la.xml
Labels: new-ruleset, top-10k

#17966 Update and rename Nowy_BIP.xml to nowybip.pl.xml
  src/chrome/content/rules/Nowy_BIP.xml
  src/chrome/content/rules/nowybip.pl.xml
Labels: ruleset-enhancement

#17962 Update UST.hk.xml, add catalog.ust.hk
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement, top-100k

#17949 Create Khamsat.com.xml
  src/chrome/content/rules/Khamsat.com.xml
Labels: new-ruleset, top-10k

#17951 Create ResidueTheorem.com.xml
  src/chrome/content/rules/ResidueTheorem.com.xml
Labels: new-ruleset

#17900 Add MoonScript.org.xml
  src/chrome/content/rules/MoonScript.org.xml
Labels: new-ruleset

#17950 Create Slader.com.xml
  src/chrome/content/rules/Slader.com.xml
Labels: new-ruleset, top-10k

#17906 Trivialize and update Florida_Today.xml
  src/chrome/content/rules/Florida_Today.xml
Labels: ruleset-enhancement, top-100k

#17870 Fix rule Swan.sk
  src/chrome/content/rules/Swan.sk.xml
Labels: ruleset-bug, top-1m

#17973 Update Aberystwyth-University.xml
  src/chrome/content/rules/Aberystwyth-University.xml
Labels: ruleset-enhancement, top-100k

#17864 [Worldtimebuddy.com] New ruleset
  src/chrome/content/rules/Worldtimebuddy.com.xml
Labels: new-ruleset, top-100k

#17859 Create NimporteQui.com.xml
  src/chrome/content/rules/NimporteQui.com.xml
Labels: new-ruleset

#17858 Create MusaFurber.com.xml
  src/chrome/content/rules/MusaFurber.com.xml
Labels: new-ruleset

#17856 Create Islamosaic.com.xml
  src/chrome/content/rules/Islamosaic.com.xml
Labels: new-ruleset

#17751 Add EPAG.de.xml
  src/chrome/content/rules/EPAG.de.xml
Labels: new-ruleset

#17734 Add SRB2Skybase.org.xml
  src/chrome/content/rules/SRB2Skybase.org.xml
Labels: new-ruleset

#17719 Add Cockbox.org.xml
  src/chrome/content/rules/Cockbox.org.xml
Labels: new-ruleset

#17762 Create minmyndighetspost.se.xml
  src/chrome/content/rules/minmyndighetspost.se.xml
Labels: new-ruleset

#17768 Create riksdagen.se.xml
  src/chrome/content/rules/riksdagen.se.xml
Labels: new-ruleset, top-1m

#17769 Create regeringen.se.xml
  src/chrome/content/rules/regeringen.se.xml
Labels: new-ruleset, top-1m

#17771 Create synonymer.se.xml
  src/chrome/content/rules/synonymer.se.xml
Labels: new-ruleset, top-100k

#17848 Fix rule Csob
  src/chrome/content/rules/Csob.sk.xml
Labels: ruleset-enhancement, top-100k

#17794 Update SJ.se.xml
  src/chrome/content/rules/SJ.se.xml
Labels: ruleset-enhancement, top-100k

#17773 Update SVT.se.xml
  src/chrome/content/rules/SVT.se.xml
Labels: ruleset-enhancement, top-10k

#17920 Add postimgs.org to PostImage
  src/chrome/content/rules/PostImage.xml
Labels: ruleset-enhancement, top-10k

#17977 Update Sinaimg.cn.xml
  src/chrome/content/rules/Sinaimg.cn.xml
Labels: ruleset-enhancement, top-10k

#17967 Update Argus_Leader.xml
  src/chrome/content/rules/Argus_Leader.xml
Labels: ruleset-enhancement, top-1m

#17971 Removing platform="mixedcontent" in goud.ma.xml
  src/chrome/content/rules/Goud.ma.xml
  src/chrome/content/rules/goud.ma.xml
Labels: ruleset-enhancement, top-10k

#17261 Create Gigabyte.eu.xml
  src/chrome/content/rules/Gigabyte.eu.xml
Labels: new-ruleset

#17260 Create Gigabyte.us.xml
  src/chrome/content/rules/Gigabyte.us.xml
Labels: new-ruleset

#17262 Create download.gigabyte.asia.xml
  src/chrome/content/rules/download.gigabyte.asia.xml
Labels: new-ruleset

#17979 Add ruleset for wettergefahren.de
  src/chrome/content/rules/Wettergefahren.de.xml
Labels: new-ruleset, top-1m

#17964 Fix typo causing *.uni.lu unprotected
  src/chrome/content/rules/Uni.Lu.xml
Labels: ruleset-enhancement, top-100k

#17844 Run HSTS-prune and update references
  src/chrome/content/rules/22Delta.xml
  src/chrome/content/rules/Bitly_branded_short_domains.xml
  src/chrome/content/rules/Byte.nl.xml
  src/chrome/content/rules/Bytenoc.nl.xml
  src/chrome/content/rules/Catbox.moe.xml
  src/chrome/content/rules/Cdig.me.xml
  src/chrome/content/rules/Cihar.com.xml
  src/chrome/content/rules/Despora.de.xml
  src/chrome/content/rules/Enalean.com.xml
  src/chrome/content/rules/GitHub.xml
  src/chrome/content/rules/Intercom.io.xml
  src/chrome/content/rules/Intercom_CDN.com.xml
  src/chrome/content/rules/LUV.asn.au.xml
  src/chrome/content/rules/Libravatar.org.xml
  src/chrome/content/rules/Nextiva.xml
  src/chrome/content/rules/PagerDuty.com.xml
  src/chrome/content/rules/RandomOrg.xml
  src/chrome/content/rules/Rudloff.pro.xml
  src/chrome/content/rules/Safercar.gov.xml
  src/chrome/content/rules/StartMail.com.xml
  src/chrome/content/rules/Tdesktop.com.xml
  src/chrome/content/rules/Telegram.me.xml
  src/chrome/content/rules/Telegram.org.xml
  src/chrome/content/rules/Telegram.wiki.xml
  src/chrome/content/rules/US_Citizenship_and_Immigration_Services.xml
  src/chrome/content/rules/Wildcard_Corp.com.xml
  src/chrome/content/rules/administrator.de.xml
  src/chrome/content/rules/aviationweather.gov.xml
  src/chrome/content/rules/integrityglobal.com.xml
  src/chrome/content/rules/jwz.org.xml
  src/chrome/content/rules/t.me.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-1k

#17957 Update outdated paragraph about MCB and Tor
  docs/en_US/rulesets.md
Labels: docs

#17980 DRY out loading of rulesets, make everything parsed through addFromJson
  chromium/background-scripts/rules.js
Labels: performance

#17982 [EducationNext.org] Simplify and reactivate ruleset
  src/chrome/content/rules/Education-Next.xml
  src/chrome/content/rules/EducationNext.org.xml
Labels: ruleset-enhancement, top-1m

#17970 Update Fujitsu.xml
  src/chrome/content/rules/Fujitsu.xml
  src/chrome/content/rules/fmworld.net.xml
  src/chrome/content/rules/fujitsu-webmart.com.xml
Labels: ruleset-enhancement, top-10k

#17876 Update Coupons-Inc.xml
  src/chrome/content/rules/Coupons-Inc.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#17985 Fix #17983 (some URL parameters dropped from EASE return links)
  chromium/background-scripts/background.js
  chromium/pages/cancel/ux.js
Labels: EASE, bug, high priority

#17843 Remove malformed regex from Globat.com.xml
  src/chrome/content/rules/Globat.com.xml
  src/chrome/content/rules/Globat.xml
Labels: ruleset-enhancement, top-1m

#17989 Create Wccftech.com.xml
  src/chrome/content/rules/Wccftech.com.xml
Labels: top-10k

#17850 Add Xwiki.org.xml
  src/chrome/content/rules/Xwiki.org.xml
Labels: new-ruleset, top-1m

#17974 Create miaopai.com.xml
  src/chrome/content/rules/miaopai.com.xml
Labels: new-ruleset, top-10k

#18001 Create ifeng.com.xml
  src/chrome/content/rules/ifeng.com.xml
Labels: top-1k

#18013 Create Instogram.pro.xml
  src/chrome/content/rules/Instogram.pro.xml
Labels: top-1m

#18003 Create EksiSozluk.com.xml
  src/chrome/content/rules/EksiSozluk.com.xml
Labels: new-ruleset, top-1k

#18011 Update Alukah.net.xml
  src/chrome/content/rules/Alukah.net.xml
Labels: ruleset-enhancement, top-10k

#18016 Remove useless target from AcademiaPress.be.xml
  src/chrome/content/rules/Academia-Press.xml
  src/chrome/content/rules/AcademiaPress.be.xml
Labels: top-1m

#18009 Create OneMathematicalCat.org.xml
  src/chrome/content/rules/OneMathematicalCat.org.xml
Labels: new-ruleset, top-1m

#18019 Fix missing target causes online.nl unprotected
  src/chrome/content/rules/Online.nl.xml
Labels: ruleset-enhancement, top-1m

#17969 Delete MediaSpan.xml
  src/chrome/content/rules/MediaSpan.xml
Labels: ruleset-enhancement

#17853 Add git reference to OOB ruleset releases, close #17641
  utils/sign-rulesets/async-request.sh
  utils/sign-rulesets/standalone.sh
Labels: sign-rulesets

#17998 Rename and update ARM.com.xml
  src/chrome/content/rules/ARM.com-problematic.xml
  src/chrome/content/rules/ARM.com.xml
  src/chrome/content/rules/ARM.xml
Labels: ruleset-enhancement, top-100k

#18026 Add ruleset for pki.goog
  src/chrome/content/rules/GoogleServices.xml
  src/chrome/content/rules/pki.goog.xml
Labels: new-ruleset, top-10k

#18025 Update letsencrypt.org ruleset
  src/chrome/content/rules/Lets_Encrypt.org.xml
Labels: ruleset-enhancement, top-100k

#18012 Create FCBarcelonaClan.com.xml
  src/chrome/content/rules/FCBarcelonaClan.com.xml
Labels: new-ruleset, top-100k

#18017 Create AdoredTV.com.xml
  src/chrome/content/rules/AdoredTV.com.xml
Labels: new-ruleset, top-100k

#18007 Create KutubPDFBook.com.xml
  src/chrome/content/rules/KutubPDFBook.com.xml
Labels: new-ruleset, top-100k

#18027 Fix and update status.io ruleset
  src/chrome/content/rules/status.io.xml
Labels: ruleset-enhancement, top-1m

#18000 Update and rename Duolingo.com.xml to Duolingo.xml
  src/chrome/content/rules/Duolingo.com.xml
  src/chrome/content/rules/Duolingo.xml
Labels: ruleset-enhancement, top-1k

#17999 Update SemiAccurate.xml
  src/chrome/content/rules/SemiAccurate.com.xml
  src/chrome/content/rules/SemiAccurate.xml
  src/chrome/content/rules/StoneArch.net.xml
Labels: ruleset-enhancement, top-1m

#17997 Update Clicksor.com.xml
  src/chrome/content/rules/Clicksor.com.xml
Labels: ruleset-enhancement

#18015 Update Media-Storehouse.xml
  src/chrome/content/rules/Media-Storehouse.xml
Labels: ruleset-enhancement, top-1m

#17986 Update Halifax.xml
  src/chrome/content/rules/Halifax-Online.co.uk.xml
  src/chrome/content/rules/Halifax.co.uk.xml
  src/chrome/content/rules/Halifax.xml
Labels: ruleset-enhancement, top-10k

#18043 Add AntennaPod.org (#18042)
  src/chrome/content/rules/AntennaPod.org.xml
Labels: new-ruleset

#18036 Re-activate and update Vzaar.xml
  src/chrome/content/rules/Vzaar.xml
Labels: ruleset-enhancement, top-1m

#18002 Added ruleset for PayMongo
  src/chrome/content/rules/PayMongo.xml
Labels: new-ruleset
