Repository EFForg/https-everywhere, pull requests merged in 2019-04, with the labels that each got.

#13992 [ANZ.com.au] New ruleset
  src/chrome/content/rules/ANZ.co.nz.xml
  src/chrome/content/rules/ANZ.com.au.xml
  src/chrome/content/rules/ANZ.com.xml
Labels: failing tests, needs revision, top-10k

#17668 Add Lecanardenchaine.fr.xml
  src/chrome/content/rules/Lecanardenchaine.fr.xml
Labels: new-ruleset

#17670 Update Geckodriver in dependencies
  install-dev-dependencies.sh
Labels: firefox

#17699 Create ChangeAView.org.xml
  src/chrome/content/rules/ChangeAView.org.xml
Labels: new-ruleset

#17703 Add elm-lang.org.xml
  src/chrome/content/rules/elm-lang.org.xml
Labels: new-ruleset, top-100k

#17698 Create ChangeAView.com.xml
  src/chrome/content/rules/ChangeAView.com.xml
Labels: new-ruleset

#17678 [Tinypass.com] Merge and simplify rulesets
  src/chrome/content/rules/Tinypass.com-falsemixed.xml
  src/chrome/content/rules/Tinypass.com.xml
Labels: ruleset-enhancement, top-1m

#17712 Update NPM Dependencies in Issue Formating Bot
  utils/issue-format-bot/package-lock.json
  utils/issue-format-bot/package.json
Labels: toolchain

#17596 Fix DeprecationWarning in HTTPS Everywhere Checker
  test/rules/src/https_everywhere_checker/check_rules.py
Labels: ruleset-testing

#17656 Fix bug in Chromium that makes popup links always load in non-incognito mode
  chromium/pages/popup/ux.js
Labels: bug, chrome, ui

#17705 Add Gegl.org.xml
  src/chrome/content/rules/Gegl.org.xml
Labels: new-ruleset

#17704 Add Tryton.org.xml
  src/chrome/content/rules/Tryton.org.xml
Labels: new-ruleset, top-1m

#17557 Fix Chromium local store exception
  chromium/background-scripts/store.js
Labels: chrome

#17001 Add Rockman-Corner.com ruleset
  src/chrome/content/rules/Rockman-Corner.com.xml
Labels: new-ruleset, top-1m

#17723 Add YourWorldOfText.com.xml
  src/chrome/content/rules/YourWorldOfText.com.xml
Labels: new-ruleset

#17697 Create GCemetery.co.xml
  src/chrome/content/rules/GCemetery.co.xml
Labels: new-ruleset, top-1m

#17702 Add WebAssembly.studio.xml
  src/chrome/content/rules/WebAssembly.studio.xml
Labels: new-ruleset

#17694 Update QQ.xml
  src/chrome/content/rules/QQ.xml
Labels: ruleset-enhancement, top-100

#17715 Remove middle wildcard support in rules.js
  chromium/background-scripts/rules.js
  chromium/test/rules_test.js
Labels: enhancement

#17736 Avoid redundant statement branching in safeToSecureCookie()
  chromium/background-scripts/rules.js
Labels: enhancement

#17667 Add Workzeitung.ch.xml
  src/chrome/content/rules/Workzeitung.ch.xml
Labels: new-ruleset

#17745 Adding references to EFF's Public Project Code of Conduct.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: EFF, docs

#17737 Remove duplicated reverb.echo.nasa.gov, gone from dns
  src/chrome/content/rules/NASA.gov-falsemixed.xml
  src/chrome/content/rules/NASA.gov.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#17648 Create Mawdoo3.com.xml
  src/chrome/content/rules/Mawdoo3.com.xml
Labels: new-ruleset, top-1k

#17538 Create sis001.xml
  src/chrome/content/rules/sis001.xml
Labels: new-ruleset, top-10k

#17541 Create cool18.xml
  src/chrome/content/rules/cool18.com.xml
Labels: new-ruleset, top-100k

#17786 Create FreePDFHosting.com.xml
  src/chrome/content/rules/FreePDFHosting.com.xml
Labels: new-ruleset, top-1m

#17788 Minor Edit to sahih-bukhari.com.xml
  src/chrome/content/rules/Sahih-Bukhari.com.xml
Labels: ruleset-enhancement, top-1m

#17795 Update Halebop.se.xml
  src/chrome/content/rules/Halebop.se.xml
Labels: ruleset-enhancement, top-1m

#17790 Update ICA.se.xml
  src/chrome/content/rules/ICA.se.xml
Labels: ruleset-enhancement, top-100k

#17747 www.europarl.europa.eu now working over https
  src/chrome/content/rules/Europa.eu.xml
Labels: ruleset-enhancement

#17764 Update Baidu.xml
  src/chrome/content/rules/Baidu.xml
Labels: ruleset-enhancement, top-100

#17749 Add 123domain.eu.xml
  src/chrome/content/rules/123domain.eu.xml
Labels: new-ruleset

#17765 Update 163.com.xml
  src/chrome/content/rules/163.com-mixedcontent.xml
  src/chrome/content/rules/163.com.xml
Labels: ruleset-enhancement

#17802 Update Xiaomi.cn.xml
  src/chrome/content/rules/Xiaomi.cn.xml
Labels: top-10k

#17772 Create expressen.se.xml
  src/chrome/content/rules/Expressen.se.xml
Labels: new-ruleset, top-10k

#17812 Update Panopticlick.com.xml
  src/chrome/content/rules/Panopticlick.com.xml
Labels: ruleset-enhancement

#17787 Create AskAMathematician.com.xml
  src/chrome/content/rules/AskAMathematician.com.xml
Labels: new-ruleset, top-1m

#17729 Add Greatis.net.xml
  src/chrome/content/rules/Greatis.net.xml
Labels: new-ruleset

#17683 Add WebDiplomacy.net.xml
  src/chrome/content/rules/WebDiplomacy.net.xml
Labels: new-ruleset, top-1m

#17684 Add FF7.fr.xml
  src/chrome/content/rules/FF7.fr.xml
Labels: new-ruleset

#17695 Add WorldOfPlayers.ru.xml
  src/chrome/content/rules/WorldOfPlayers.ru.xml
Labels: new-ruleset, top-1m

#17676 Add BlamBot.com.xml
  src/chrome/content/rules/BlamBot.com.xml
Labels: new-ruleset, top-1m

#17612 Create RomStation.fr.xml
  src/chrome/content/rules/RomStation.fr.xml
Labels: new-ruleset

#17598 Create Systemspace.network.xml
  src/chrome/content/rules/Systemspace.network.xml
Labels: new-ruleset

#17611 Create Digiology.org.xml
  src/chrome/content/rules/Digiology.org.xml
Labels: new-ruleset

#17835 Use the latest LTS Node.js release for unittests, fix #17829
  .travis.yml
Labels: toolchain

#17435 Added ruleset - Stellwerksim.de.xml
  src/chrome/content/rules/Stellwerksim.de.xml
Labels: new-ruleset, top-1m

#17685 Add buaa.edu.cn.xml
  src/chrome/content/rules/buaa.edu.cn.xml
Labels: new-ruleset

#17617 Create OldUnreal.com.xml
  src/chrome/content/rules/OldUnreal.com.xml
Labels: new-ruleset

#17816 Update Payson.xml
  src/chrome/content/rules/Payson.xml
Labels: ruleset-enhancement

#17804 Update topicbox.com.xml
  src/chrome/content/rules/topicbox.com.xml
Labels: ruleset-enhancement

#17803 Update Pobox.xml
  src/chrome/content/rules/Pobox.xml
Labels: ruleset-enhancement, top-1m

#17827 Add RPGRussia.com.xml
  src/chrome/content/rules/RPGRussia.com.xml
Labels: new-ruleset, top-100k

#17652 Create 22Fevrier2019.org.xml
  src/chrome/content/rules/22Fevrier2019.org.xml
Labels: new-ruleset

#17779 Create HowiyaPress.com.xml
  src/chrome/content/rules/HowiyaPress.com.xml
Labels: new-ruleset, top-100k

#17776 Create Kutub.one.xml
  src/chrome/content/rules/Kutub.one.xml
Labels: new-ruleset

#17785 Create Oneworld-Publications.com.xml
  src/chrome/content/rules/Oneworld-Publications.com.xml
Labels: new-ruleset

#17780 Create FoulaBook.com.xml
  src/chrome/content/rules/FoulaBook.com.xml
Labels: new-ruleset, top-1m

#17766 Update 1177.se.xml
  src/chrome/content/rules/1177.se.xml
Labels: ruleset-enhancement, top-100k

#17793 Update Apoteket.se.xml
  src/chrome/content/rules/Apoteket.se.xml
Labels: ruleset-enhancement, top-1m

#17687 Add OpenGroup.org.xml and delete The-Open-Group.xml
  src/chrome/content/rules/OpenGroup.org.xml
  src/chrome/content/rules/The-Open-Group.xml
  src/chrome/content/rules/WordPress-blogs.xml
Labels: ruleset-enhancement, top-100k

#17791 Create icabanken.se.xml
  src/chrome/content/rules/icabanken.se.xml
Labels: new-ruleset, top-100k

#14978 Create Gdl.de.xml
  src/chrome/content/rules/Gdl-hof.de.xml
  src/chrome/content/rules/Gdl-kempten.de.xml
  src/chrome/content/rules/Gdl-m.de.xml
  src/chrome/content/rules/Gdl-nn.de.xml
  src/chrome/content/rules/Gdl-og-gera.de.xml
  src/chrome/content/rules/Gdl-sbahn-berlin.de.xml
  src/chrome/content/rules/Gdl.de.xml
  src/chrome/content/rules/Gdlhamm.de.xml
Labels: new-ruleset

#17840 Update Debian.net.xml
  src/chrome/content/rules/Debian.net.xml
Labels: ruleset-enhancement
