Repository EFForg/https-everywhere, pull requests merged in 2019-02, with the labels that each got.

#17350 Create AreWeFluentYet.com.xml
  src/chrome/content/rules/AreWeFluentYet.com.xml
Labels: new-ruleset

#17290 Add Remmina.org.xml
  src/chrome/content/rules/Remmina.org.xml
Labels: new-ruleset

#14591 [FreePornGif.com] Simplify and merge rulesets
  src/chrome/content/rules/Free_Porn_Gif.com-falsemixed.xml
  src/chrome/content/rules/Free_Porn_Gif.com.xml
Labels: top-1m

#16398 Update and simplify Geocaching.com.xml
  src/chrome/content/rules/Geocaching.com-falsemixed.xml
  src/chrome/content/rules/Geocaching.com.xml
Labels: ruleset-enhancement, top-10k

#16584 Add Libspf2.org.xml
  src/chrome/content/rules/Libspf2.org.xml
Labels: new-ruleset

#17285 Add Rsyslog.com.xml
  src/chrome/content/rules/Rsyslog.com.xml
Labels: new-ruleset

#16097 Re-activate Svenskakyrkan.se.xml (Swedish Church)
  src/chrome/content/rules/Svenskakyrkan.se.xml
Labels: top-1m

#17292 Add Pgpool.net.xml
  src/chrome/content/rules/Pgpool.net.xml
Labels: new-ruleset

#16582 Add Libarchive.org.xml
  src/chrome/content/rules/Libarchive.org.xml
Labels: new-ruleset

#17347 Change the open URL link to a button
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
  chromium/pages/cancel/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#17415 Add ruleset: Bashy.io
  src/chrome/content/rules/Bashy.io.xml
Labels: new-ruleset

#17144 Add ruleset: UAB.edu
  src/chrome/content/rules/UAB.edu.xml
Labels: top-100k

#17488 Create Quantlib.org.xml
  src/chrome/content/rules/Quantlib.org.xml
Labels: new-ruleset

#17392 Update Microsoft.xml
  src/chrome/content/rules/Microsoft.xml
Labels: failing tests, top-1k

#17288 Add Privoxy.org.xml
  src/chrome/content/rules/Privoxy.org.xml
Labels: new-ruleset

#15877 Update gimp.org.xml
  src/chrome/content/rules/gimp.org.xml
Labels: top-10k

#15876 Add art.gnome.org and ftp.gnome.org
  src/chrome/content/rules/GNOME.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100k

#17386 Update Onamae.com.xml
  src/chrome/content/rules/GMO_Internet.xml
  src/chrome/content/rules/Onamae.com.xml
Labels: top-100k

#17497 Create OpenWall.com.xml
  src/chrome/content/rules/OpenWall.com.xml
Labels: new-ruleset
