Repository EFForg/https-everywhere, pull requests merged in 2019-03, with the labels that each got.

#17530 Add SSL internal error code to SSL misconfiguration list
  chromium/background-scripts/background.js
Labels: EASE

#17509 Update Hao123.com.xml
  src/chrome/content/rules/Hao123.com-mixedcontent.xml
  src/chrome/content/rules/Hao123.com.xml
Labels: top-100

#17513 Update Mayo-Clinic.xml
  src/chrome/content/rules/Mayo-Clinic.xml
Labels: top-1k

#17515 Update prnt.sc.xml
  src/chrome/content/rules/prnt.sc.xml
Labels: top-1k

#17502 Create ThisPersonDoesNotExist.com.xml
  src/chrome/content/rules/ThisPersonDoesNotExist.com.xml
Labels: top-10k

#17500 Create ThisCatDoesNotExist.com.xml
  src/chrome/content/rules/ThisCatDoesNotExist.com.xml
Labels: top-100k

#17471 Delete alibaba-inc.com-falsemixed.xml
  src/chrome/content/rules/alibaba-inc.com-falsemixed.xml
  src/chrome/content/rules/alibaba-inc.com.xml
Labels: top-1k

#17543 Update 126.com.xml
  src/chrome/content/rules/126.com.xml
Labels: top-1k

#17516 Update People.com.xml
  src/chrome/content/rules/People.com-problematic.xml
  src/chrome/content/rules/People.com.xml
Labels: top-10k

#17495 Delete ruleset: QupZilla.com
  src/chrome/content/rules/QupZilla.com.xml
Labels: top-1m

#17517 Update Dell.xml
  src/chrome/content/rules/Dell.com-falsemixed.xml
  src/chrome/content/rules/Dell.xml
Labels: top-1k

#17512 Update GameSpot.xml
  src/chrome/content/rules/CBS.xml
  src/chrome/content/rules/GameSpot.com-falsemixed.xml
  src/chrome/content/rules/GameSpot.com.xml
  src/chrome/content/rules/GameSpot.xml
Labels: top-1k

#17558 Add a METEO.PL ruleset
  src/chrome/content/rules/METEO.PL.xml
Labels: top-10k

#17503 Create VClock.com.xml
  src/chrome/content/rules/VClock.com.xml
Labels: top-100k

#17564 Update HSTS preload max age
  CONTRIBUTING.md
Labels: docs

#17548 Fix and update openstreetmap.fr ruleset
  src/chrome/content/rules/Openstreetmap.fr.xml
Labels: top-1m

#17549 Create iliad.it.xml
  src/chrome/content/rules/iliad.it.xml
Labels: top-100k

#17380 Create FrenchLeaks.fr.xml
  src/chrome/content/rules/FrenchLeaks.fr.xml
Labels: new-ruleset

#17334 Create WriteTheDocs.org.xml
  src/chrome/content/rules/WriteTheDocs.org.xml
Labels: new-ruleset

#17444 Update 17track.net.xml
  src/chrome/content/rules/17track.net.xml
Labels: top-10k

#17534 Update yikeweiqi.com.xml
  src/chrome/content/rules/yikeweiqi.com.xml
Labels: top-100k

#17533 Create EDRDG.org.xml
  src/chrome/content/rules/EDRDG.org.xml
Labels: top-100k

#17385 Update ahcdn.com.xml
  src/chrome/content/rules/ahcdn.com-falsemixed.xml
  src/chrome/content/rules/ahcdn.com.xml
Labels: top-10k

#17384 Re-activate and Update AKG.com.xml
  src/chrome/content/rules/AKG.com.xml
  src/chrome/content/rules/Harman-International-Industries.xml
Labels: top-100k

#17446 Update and rename 4Tulemar.xml to Tulemar.xml
  src/chrome/content/rules/4Tulemar.xml
  src/chrome/content/rules/Tulemar.xml
Labels: top-1m

#17432 Create ObsPol.be.xml
  src/chrome/content/rules/ObsPol.be.xml
Labels: new-ruleset

#17276 Create CeCILL.info.xml
  src/chrome/content/rules/CeCILL.info.xml
Labels: new-ruleset

#17569 Update SDI-Tool.org.xml
  src/chrome/content/rules/SDI-Tool.org.xml
Labels: top-1m

#15507 Update ruleset: TorontoPolice.on.ca
  src/chrome/content/rules/TorontoPolice.on.ca.xml
Labels: top-1m

#17568 [TVTropes.org] Simplify ruleset
  src/chrome/content/rules/TVTropes.org.xml
  src/chrome/content/rules/TV_Tropes.xml
Labels: top-10k

#17566 Create Ouo.xml
  src/chrome/content/rules/Ouo.xml
Labels: top-1k

#17442 Update 1tulatv.ru.xml
  src/chrome/content/rules/1tulatv.ru.xml
Labels: top-100k, top-1m

#17450 Update Abila.com.xml
  src/chrome/content/rules/Abila.com.xml
Labels: top-1m

#17404 Create UESP.net.xml
  src/chrome/content/rules/UESP.net.xml
Labels: top-10k

#17438 Refactor and enhance trivialize-cookie-rules.js
  utils/trivialize-rules/trivialize-cookie-rules.js
Labels: enhancement

#17572 Create aarresaari.net.xml
  src/chrome/content/rules/aarresaari.net.xml
Labels: new-ruleset

#16667 Update ruleset: Posthaven.com
  src/chrome/content/rules/Posthaven.com-problematic.xml
  src/chrome/content/rules/Posthaven.com.xml
Labels: ruleset-enhancement, top-1m

#17134 Create ruleset: PlantOGram.com
  src/chrome/content/rules/PlantOGram.com.xml
Labels: new-ruleset

#17391 Update NASA.gov
  src/chrome/content/rules/NASA.gov.xml
  utils/ruleset-whitelist.csv
Labels: failing tests, top-1k

#17472 Added new ruleset - Cheapshark.com.xml
  src/chrome/content/rules/Cheapshark.com.xml
Labels: new-ruleset

#17575 Create communitycrimemap.xml
  src/chrome/content/rules/communitycrimemap.xml
Labels: top-1m

#14026 Create Freeones.xml
  src/chrome/content/rules/Freeones.xml
Labels: top-10k

#17580 Create MAGAimg.net.xml
  src/chrome/content/rules/MAGAimg.net.xml
Labels: top-100k

#17573 Re-enable Safe-mail.net.xml (fix #17267)
  src/chrome/content/rules/Safe-mail.net.xml
Labels: top-1m

#17595 Add "How to Fix Site" to Documentation
  CONTRIBUTING.md
Labels: docs

#17594 Create MichelbergerMonkey.com.xml
  src/chrome/content/rules/MichelbergerMonkey.com.xml
Labels: top-1m

#17511 Update BBC.xml
  src/chrome/content/rules/BBC-mismatches.xml
  src/chrome/content/rules/BBC.co.uk.xml
  src/chrome/content/rules/BBC.xml
  src/chrome/content/rules/bbc.co.uk-resources.xml
Labels: failing tests, top-100

#17293 Add some nongnu.org hosts
  src/chrome/content/rules/FSF.xml
Labels: ruleset-enhancement

#17600 Update QQ.xml
  src/chrome/content/rules/QQ.xml
Labels: top-100

#17504 Create AlFaseeh.com.xml
  src/chrome/content/rules/AlFaseeh.com.xml
Labels: top-100k

#17565 Update some securecookie with no coverage
  src/chrome/content/rules/Active-Events.xml
  src/chrome/content/rules/Broadcasthe.net.xml
  src/chrome/content/rules/Dropbox.xml
  src/chrome/content/rules/Esellerate.net.xml
  src/chrome/content/rules/Get_jaco.com.xml
  src/chrome/content/rules/Greek-media.xml
  src/chrome/content/rules/Guild-Wars-2.xml
  src/chrome/content/rules/LiveStrong.com.xml
  src/chrome/content/rules/Microtech.xml
  src/chrome/content/rules/QualityAgent.xml
  src/chrome/content/rules/Securepicssl.com.xml
  src/chrome/content/rules/Trafficmaxx.xml
  utils/ruleset-whitelist.csv
Labels: top-10k

#17604 Add Linuxbenchmarking.com.xml
  src/chrome/content/rules/Linuxbenchmarking.com.xml
Labels: new-ruleset

#17222 Create Overpass-api.de.xml
  src/chrome/content/rules/Overpass-api.de.xml
Labels: new-ruleset

#17614 Update QQ.com.xml
  src/chrome/content/rules/QQ.com-mixedcontent.xml
  src/chrome/content/rules/QQ.xml
Labels: top-100

#17463 Update and rename Ahnlab.com.xml to AhnLab.com.xml
  src/chrome/content/rules/AhnLab.com.xml
  src/chrome/content/rules/Ahnlab.com.xml
Labels: top-100k

#17592 Create MichelbergerHotel.com.xml
  src/chrome/content/rules/MichelbergerHotel.com.xml
Labels: new-ruleset

#17627 Update PConline.xml
  src/chrome/content/rules/PConline.xml
Labels: top-10k

#17628 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: top-100k

#17603 Add Cubana.cu.xml
  src/chrome/content/rules/Cubana.cu.xml
Labels: new-ruleset

#17602 Add Darwinsys.com.xml
  src/chrome/content/rules/Darwinsys.com.xml
Labels: new-ruleset

#13857 Split Potager.org.xml into more manageable rulesets
  src/chrome/content/rules/Pimienta.org.xml
  src/chrome/content/rules/Poivron.org.xml
  src/chrome/content/rules/Potager.org.xml
  src/chrome/content/rules/SweetPepper.org.xml
Labels: needs revision, ruleset-enhancement

#17540 Create sex8.xml
  src/chrome/content/rules/sex8.cc.xml
Labels: top-10k

#17526 Add ruleset: ILikeBigBits.com
  src/chrome/content/rules/ILikeBigBits.com.xml
Labels: top-1m

#17619 Update dxy.com.xml
  src/chrome/content/rules/dxy.com.xml
Labels: top-100k

#17527 Add ruleset: Casual-Effects.com
  src/chrome/content/rules/Casual-Effects.com.xml
Labels: top-1m

#17484 Add ruleset: LeanCrew.com
  src/chrome/content/rules/LeanCrew.com.xml
Labels: top-1m

#17536 Create ygshuwu.xml
  src/chrome/content/rules/ygshuwu.xml
Labels: top-1m

#17625 Add Technik.cafe.xml
  src/chrome/content/rules/Technik.cafe.xml
Labels: new-ruleset

#17624 Add Spadesecurity.com.xml
  src/chrome/content/rules/Spadesecurity.com.xml
Labels: new-ruleset

#17626 Enable Digitaltrends.com.xml
  src/chrome/content/rules/Digital_Trends.com.xml
  src/chrome/content/rules/Digitaltrends.com.xml
Labels: ruleset-enhancement, top-10k

#15853 Add Pcengines.ch.xml
  src/chrome/content/rules/Pcengines.ch.xml
Labels: new-ruleset

#17175 Add Nic.ir.xml
  src/chrome/content/rules/Nic.ir.xml
Labels: failing tests, new-ruleset, top-100k

#17601 Add Biocubafarma.cu.xml
  src/chrome/content/rules/Biocubafarma.cu.xml
Labels: new-ruleset

#17101 Add Akinator.com.xml
  src/chrome/content/rules/Akinator.com.xml
  utils/ruleset-whitelist.csv
Labels: new-ruleset, top-100k

#17481 Added Game Network rulesets
  src/chrome/content/rules/Gamer-network.net.xml
  src/chrome/content/rules/Nintendolife.com.xml
  src/chrome/content/rules/Pushsquare.com.xml
Labels: top-10k

#17185 add rule for Flappening.watch
  src/chrome/content/rules/Flappening.watch.xml
Labels: top-1m

#16044 Deleted handy.de obsolete rule
  src/chrome/content/rules/Handy.de.xml
Labels: ruleset-bug, top-1m

#15175 Add Trump Organization rulesets
  src/chrome/content/rules/Trump.com.xml
  src/chrome/content/rules/TrumpGolf.com.xml
  src/chrome/content/rules/TrumpHotels.com.xml
  src/chrome/content/rules/TrumpInternationalRealty.com.xml
  src/chrome/content/rules/TrumpStore.com.xml
  src/chrome/content/rules/TrumpWinery.com.xml
Labels: top-1m

#15746 Create passwordsgenerator.net.xml
  src/chrome/content/rules/passwordsgenerator.net.xml
Labels: new-ruleset, top-100k

#16737 Create ipv6forum.com.xml
  src/chrome/content/rules/IPv6Forum.com.xml
Labels: top-1m

#14535 Add revenuquebec.ca
  src/chrome/content/rules/RevenuQuebec.ca.xml
Labels: top-100k

#17635 [Game Network rulesets] add missing targets and fix code style
  src/chrome/content/rules/Gamer-network.net.xml
  src/chrome/content/rules/Nintendolife.com.xml
  src/chrome/content/rules/Pushsquare.com.xml
Labels: ruleset-enhancement, top-10k

#17623 Update default timestamp for deterministic builds
  utils/zipfile_deterministic.py
Labels: toolchain

#13907 add rule for Cityam.com
  src/chrome/content/rules/Cityam.com.xml
Labels: new-ruleset, top-100k

#12317 Fix wildcard-in-the-middle in General-Electric.xml
  src/chrome/content/rules/GEBlogs.com.xml
  src/chrome/content/rules/General-Electric.xml
Labels: high priority, ruleset-bug, ruleset-enhancement

#17291 Add Nuttcp.net.xml
  src/chrome/content/rules/Nuttcp.net.xml
Labels: new-ruleset

#17518 Delete GO.com.xml
  src/chrome/content/rules/GO.com.xml
Labels: top-1k

#15307 Hacklang.org
  src/chrome/content/rules/HackLang.org.xml
Labels: new-ruleset, top-1m

#15403 openweathermap.org
  src/chrome/content/rules/OpenWeatherMap.org.xml
Labels: new-ruleset, top-100k

#17642 [PyData.org] Update ruleset
  src/chrome/content/rules/PyData.org.xml
Labels: top-10k

#17647 [Dask.org] New ruleset
  src/chrome/content/rules/Dask.org.xml
Labels: new-ruleset, top-1m

#15755 Add Lxde.org.xml
  src/chrome/content/rules/Lxde.org.xml
Labels: new-ruleset, top-1m

#17644 [SphinxDoc.org] New ruleset
  src/chrome/content/rules/Sphinx-doc.org.xml
Labels: top-100k

#17615 Create yunlaige.com.xml
  src/chrome/content/rules/yunlaige.com.xml
Labels: top-100k
