Repository EFForg/https-everywhere, pull requests merged in 2019-08, with the labels that each got.

#18260 Update Starwood-Hotels-and-Resorts.xml
  src/chrome/content/rules/Starwood-Hotels-and-Resorts.xml
  src/chrome/content/rules/StarwoodHotels.com.xml
Labels: ruleset-enhancement, top-100k

#18243 Add Neis-One.org.xml
  src/chrome/content/rules/Neis-One.org.xml
  src/chrome/content/rules/Neis-One.org_mixedcontent.xml
Labels: new-ruleset, top-1m

#18265 Re-enable da.gd
  src/chrome/content/rules/Da.gd.xml
Labels: ruleset-enhancement

#18222 Create Radioreference.com.xml
  src/chrome/content/rules/Radioreference.com.xml
Labels: new-ruleset, top-100k

#18272 Update Stack-Exchange.xml
  src/chrome/content/rules/Stack-Exchange.xml
Labels: ruleset-enhancement, top-100

#18247 Re-enabling Cpunks.org.xml
  src/chrome/content/rules/Cpunks.org.xml
Labels: ruleset-enhancement

#14184 Created Acer.com.xml for Acer Care Center Updates
  src/chrome/content/rules/Acer.com.xml
Labels: failing tests, new-ruleset

#17796 Update TT.se.xml
  src/chrome/content/rules/TT.se.xml
Labels: ruleset-enhancement, top-1m

#18281 Update 1177.se.xml
  src/chrome/content/rules/1177.se.xml
Labels: ruleset-enhancement, top-100k

#18274 Create GitFoo.com.xml
  src/chrome/content/rules/GitFoo.com.xml
Labels: new-ruleset

#18283 Update Gsfacket.se.xml
  src/chrome/content/rules/Gsfacket.se.xml
Labels: ruleset-enhancement

#18287 Create PerspectiveAPI.com.xml
  src/chrome/content/rules/PerspectiveAPI.com.xml
Labels: new-ruleset

#18280 Re-enabling PICMET.org.xml
  src/chrome/content/rules/PICMET.org.xml
Labels: ruleset-enhancement

#18256 Update Overclock.net.xml
  src/chrome/content/rules/Overclock.net-problematic.xml
  src/chrome/content/rules/Overclock.net.xml
Labels: ruleset-enhancement, top-100k

#18282 Update and rename My_Healthcare_Contacts.xml to minavardkontakter.se.xml
  src/chrome/content/rules/My_Healthcare_Contacts.xml
  src/chrome/content/rules/minavardkontakter.se.xml
Labels: ruleset-enhancement

#17770 Create gigablast.com.xml
  src/chrome/content/rules/gigablast.com.xml
Labels: new-ruleset, top-1m

#18231 Create Capstone-engine.org.xml
  src/chrome/content/rules/Capstone-engine.org.xml
Labels: new-ruleset

#18320 Add NCRegister.com.xml
  src/chrome/content/rules/NCRegister.com.xml
Labels: new-ruleset, top-1m

#18315 Add Digint.ch.xml
  src/chrome/content/rules/Digint.ch.xml
Labels: new-ruleset

#18318 Add files and lists to FreeSWITCH.org.xml
  src/chrome/content/rules/FreeSWITCH.org.xml
Labels: new-ruleset, top-100k

#18290 Create zaobao.com.xml
  src/chrome/content/rules/zaobao.com.xml
Labels: new-ruleset, top-100k

#18186 [BangorDailyNews.com] Simplify ruleset
  src/chrome/content/rules/BangorDailyNews.com.xml
  src/chrome/content/rules/Bangor_Daily_News.xml
Labels: ruleset-enhancement, top-100k

#18313 Add Ghostscript.com.xml
  src/chrome/content/rules/Ghostscript.com.xml
Labels: new-ruleset, top-1m

#15854 Add Schweikert.ch.xml
  src/chrome/content/rules/Schweikert.ch.xml
Labels: new-ruleset

#14894 [Fark.com] Reactivate and simplify ruleset
  src/chrome/content/rules/Fark.xml
Labels: ruleset-enhancement, top-10k

#18326 Add more hosts to Java.net.xml
  src/chrome/content/rules/Java.net.xml
Labels: ruleset-enhancement, top-100k

#18321 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement, top-100k

#18323 Update Disney.co.jp.xml
  src/chrome/content/rules/Disney.co.jp.xml
Labels: ruleset-enhancement, top-10k

#18324 Create Comiket.co.jp.xml
  src/chrome/content/rules/Comiket.co.jp.xml
Labels: new-ruleset, top-100k

#18305 Create thrysoee.dk.xml
  src/chrome/content/rules/thrysoee.dk.xml
Labels: new-ruleset

#18292 Create zsnes.com.xml
  src/chrome/content/rules/zsnes.com.xml
Labels: new-ruleset, top-1m

#18301 Create tortall.net.xml
  src/chrome/content/rules/tortall.net.xml
Labels: new-ruleset

#18277 Create EquifaxBreachSettlement.com.xml
  src/chrome/content/rules/EquifaxBreachSettlement.com.xml
Labels: new-ruleset, top-10k

#18298 Update Yimg.com.xml
  src/chrome/content/rules/Yimg.com.xml
Labels: ruleset-enhancement

#18302 Create hkexnews.hk.xml
  src/chrome/content/rules/hkex.com.hk.xml
  src/chrome/content/rules/hkexnews.hk.xml
Labels: new-ruleset, top-100k

#18293 Create Animeanime.jp.xml
  src/chrome/content/rules/Animeanime.jp.xml
Labels: new-ruleset, top-100k

#18249 Create MrMondialisation.org.xml
  src/chrome/content/rules/MrMondialisation.org.xml
Labels: new-ruleset, top-1m

#18273 Re-enabling TheGrandTheatre.com.xml
  src/chrome/content/rules/TheGrandTheatre.com.xml
  src/chrome/content/rules/The_Grand.xml
Labels: ruleset-enhancement

#18269 Update FierceMarkets.xml
  src/chrome/content/rules/FierceMarkets.xml
Labels: ruleset-enhancement

#18309 Create surina.net.xml
  src/chrome/content/rules/surina.net.xml
Labels: new-ruleset

#18296 Create tset.de.xml
  src/chrome/content/rules/tset.de.xml
Labels: new-ruleset

#18338 Qq.com
  src/chrome/content/rules/QQ.com-Problematic.xml
  src/chrome/content/rules/QQ.com-mixedcontent.xml
  src/chrome/content/rules/QQ.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#18308 Create Rantsports.com.xml
  src/chrome/content/rules/Rantsports.com.xml
Labels: broken MCB, new-ruleset

#18328 Re-enable UNICEF.fi.xml
  src/chrome/content/rules/UNICEF.fi.xml
Labels: ruleset-enhancement

#17498 Exclude external dependencies from Istanbul and Coveralls.
  chromium/package.json
Labels: toolchain

#18347 Create ThreadReaderApp.com.xml
  src/chrome/content/rules/ThreadReaderApp.com.xml
Labels: new-ruleset, top-100k

#18344 Update Baidu.xml
  src/chrome/content/rules/Baidu.xml
Labels: ruleset-enhancement, top-100

#18331 Create Chatons.org.xml
  src/chrome/content/rules/Chatons.org.xml
Labels: new-ruleset

#18341 Create EnglishPage.com.xml
  src/chrome/content/rules/EnglishPage.com.xml
Labels: new-ruleset, top-100k

#18250 Re-enabling Cryptome.xml
  src/chrome/content/rules/Cryptome.xml
Labels: ruleset-enhancement, top-1m
