Repository EFForg/https-everywhere, pull requests merged in 2019-11, with the labels that each got.

#18417 Feature: Navigate to HTTP in EASE Once
  chromium/background-scripts/background.js
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
  chromium/pages/cancel/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: EASE

#18651 Add ruleset: ExploreFlask.com
  src/chrome/content/rules/ExploreFlask.com.xml
Labels: new-ruleset

#18654 Create ruleset: EasterSeals.org
  src/chrome/content/rules/EasterSeals.org.xml
Labels: new-ruleset

#18656 Create ruleset: CarKeySolutions.ca
  src/chrome/content/rules/CarKeySolutions.ca.xml
Labels: new-ruleset

#18646 Create openrct2.io.xml
  src/chrome/content/rules/openrct2.io.xml
Labels: new-ruleset

#18655 Create ruleset: Flyerify.com
  src/chrome/content/rules/Flyerify.com.xml
Labels: new-ruleset

#18623 Create zoo-bordeaux-pessac.com.xml
  src/chrome/content/rules/zoo-bordeaux-pessac.com.xml
Labels: new-ruleset

#18591 Create cincinnatizoo.org.xml
  src/chrome/content/rules/cincinnatizoo.org.xml
Labels: new-ruleset

#18653 Create ruleset: Scribble.nu
  src/chrome/content/rules/Scribble.nu.xml
Labels: new-ruleset

#18652 Create ruleset: Aquapel.ca
  src/chrome/content/rules/Aquapel.ca.xml
Labels: new-ruleset

#18636 Create cackle.me.xml
  src/chrome/content/rules/cackle.me.xml
Labels: new-ruleset, top-1m

#18667 Ensure that the translations script does not attempt to convert nonexistant translation files
  utils/chromium-translations.py
Labels: bug, i18n, toolchain

#18648 Create Grubstreet.com.xml
  src/chrome/content/rules/Grubstreet.com.xml
Labels: new-ruleset, top-100k

#18552 Add Reactiongifs.com.xml
  src/chrome/content/rules/Reactiongifs.com.xml
Labels: new-ruleset

#18560 Create glazdik.ru.xml
  src/chrome/content/rules/glazdik.ru.xml
Labels: new-ruleset

#18575 Create hotelmetropolitan.co.il.xml
  src/chrome/content/rules/hotelmetropolitan.co.il.xml
Labels: new-ruleset

#18657 Create ruleset: AntiqueMotorcycle.org
  src/chrome/content/rules/AntiqueMotorcycle.org.xml
Labels: new-ruleset

#18659 Create ruleset: JavaScriptIsSexy.com
  src/chrome/content/rules/JavaScriptIsSexy.com.xml
Labels: new-ruleset, top-1m

#18661 Create ruleset: FinancialHacks.ca
  src/chrome/content/rules/FinancialHacks.ca.xml
Labels: new-ruleset

#18676 Create clonezilla.org.xml
  src/chrome/content/rules/clonezilla.org.xml
Labels: new-ruleset, top-100k

#18689 Update Imgur.com.xml
  src/chrome/content/rules/Imgur.com.xml
  src/chrome/content/rules/Imgur.xml
Labels: ruleset-enhancement, top-100

#18691 Add target to hs-esslingen.de ruleset
  src/chrome/content/rules/Hochschule-Esslingen.xml
Labels: ruleset-enhancement

#18698 Update Gigabyte.us.xml
  src/chrome/content/rules/Gigabyte.us.xml
Labels: ruleset-enhancement

#18696 Update Gigabyte.eu.xml
  src/chrome/content/rules/Gigabyte.eu.xml
Labels: ruleset-enhancement

#18697 Update download.gigabyte.asia.xml
  src/chrome/content/rules/download.gigabyte.asia.xml
Labels: ruleset-enhancement

#18695 Fix multiple issues on EASE cancel page
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
Labels: EASE, bug, ui

#18567 Create grafica.app.xml
  src/chrome/content/rules/grafica.app.xml
Labels: new-ruleset

#18686 Add ruleset: home-assistant.io
  src/chrome/content/rules/Home-Assistant.io.xml
Labels: new-ruleset, top-10k

#18688 Update Gigabyte.com.xml
  src/chrome/content/rules/Gigabyte.com.xml
Labels: ruleset-enhancement, top-10k

#18633 Add exclusion to Chatango.com.xml (fix #9685)
  src/chrome/content/rules/Chatango.com.xml
Labels: ruleset-bug, ruleset-enhancement, top-10k

#18663 Create retroarch.com.xml
  src/chrome/content/rules/retroarch.com.xml
Labels: new-ruleset, top-100k

#18675 Create vfl.ru.xml
  src/chrome/content/rules/vfl.ru.xml
Labels: new-ruleset, top-100k

#18677 Create tldp.org.xml
  src/chrome/content/rules/tldp.org.xml
Labels: new-ruleset, top-100k

#18682 Create joxi.net.xml
  src/chrome/content/rules/joxi.net.xml
Labels: new-ruleset, top-100k

#18666 Re-enable BrightTalk ruleset
  src/chrome/content/rules/BrightTALK.com.xml
Labels: ruleset-enhancement, top-100k

#18669 Create Fidelity.com.hk.xml
  src/chrome/content/rules/Fidelity.com.hk.xml
Labels: new-ruleset, top-1m

#18681 Create techpowerup.org.xml
  src/chrome/content/rules/techpowerup.org.xml
Labels: new-ruleset, top-1m

#18622 Create dbq.edu.xml
  src/chrome/content/rules/dbq.edu.xml
Labels: new-ruleset, top-1m

#18701 Update Qpic.cn.xml
  src/chrome/content/rules/Qpic.cn.xml
Labels: china, ruleset-enhancement

#18683 Create klikr.org.xml
  src/chrome/content/rules/klikr.org.xml
Labels: new-ruleset

#18674 Create ipic.su.xml
  src/chrome/content/rules/ipic.su.xml
Labels: new-ruleset, top-1m

#18662 Create ruleset: En-Pro.com
  src/chrome/content/rules/En-Pro.com.xml
Labels: new-ruleset

#18693 Add humandesign.fi
  src/chrome/content/rules/HumanDesign.fi.xml
Labels: new-ruleset

#18671 Create filecrypt.co.xml
  src/chrome/content/rules/filecrypt.co.xml
Labels: new-ruleset, top-10k

#18692 Create LePoint.net.xml
  src/chrome/content/rules/LePoing.net.xml
Labels: new-ruleset

#18673 Add ruleset for thedailywtf.com
  src/chrome/content/rules/TheDailyWTF.com.xml
Labels: new-ruleset

#18684 Create hekasoft.com.xml
  src/chrome/content/rules/hekasoft.com.xml
Labels: new-ruleset

#18680 Add Programvareverkstedet (pvv.ntnu.no, pvv.org)
  src/chrome/content/rules/Programvareverkstedet.xml
Labels: new-ruleset

#18704 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement, top-100k

#18705 Create preuveneers.be.xml
  src/chrome/content/rules/preuveneers.be.xml
Labels: new-ruleset

#18712 Create applegate.com.xml
  src/chrome/content/rules/applegate.com.xml
Labels: new-ruleset

#18713 Create smartdnsproxy.com.xml
  src/chrome/content/rules/smartdnsproxy.com.xml
Labels: new-ruleset, top-100k

#18709 Add Inteligo.pl.xml
  src/chrome/content/rules/Inteligo.pl.xml
Labels: new-ruleset, top-100k

#18714 Create fatiguescience.com.xml
  src/chrome/content/rules/fatiguescience.com.xml
Labels: new-ruleset, top-1m

#18539 Create nexedi.com.xml
  src/chrome/content/rules/nexedi.com.xml
Labels: new-ruleset

#18711 Add AliorBank.pl.xml
  src/chrome/content/rules/AliorBank.pl.xml
Labels: new-ruleset, top-10k

#18703 Add the-eye.eu
  src/chrome/content/rules/the-eye.eu.xml
Labels: new-ruleset, top-100k

#18718 Create FactWire.org.xml
  src/chrome/content/rules/FactWire.org.xml
Labels: new-ruleset

#18710 Create cloudcma.com.xml
  src/chrome/content/rules/cloudcma.com.xml
Labels: new-ruleset, top-1m

#18707 Create boardreader.com.xml
  src/chrome/content/rules/boardreader.com.xml
Labels: new-ruleset, top-100k

#18717 Create plasq.com.xml
  src/chrome/content/rules/plasq.com.xml
Labels: new-ruleset, top-1m
