Repository EFForg/https-everywhere, pull requests merged in 2019-12, with the labels that each got.

#18730 Add z0r.de.xml
  src/chrome/content/rules/z0r.de.xml
Labels: new-ruleset, top-1m

#18732 Create Lionbrand.com
  src/chrome/content/rules/Lionbrand.com.xml
Labels: new-ruleset, top-1m

#18725 Update osuosl.org.xml
  src/chrome/content/rules/osuosl.org.xml
Labels: ruleset-enhancement, top-1m

#18637 [Labeller Dockerfile] pin node version
  utils/labeller/Dockerfile
Labels: toolchain

#18700 HTTP Config TLS Update
  test/rules/http.checker.config
Labels: toolchain

#18733 Create 1freehosting.com.xml
  src/chrome/content/rules/1freehosting.com.xml
Labels: new-ruleset

#18736 Remove unused imports
  utils/zipfile_deterministic.py
Labels: code-style

#18719 Create yapx.ru.xml
  src/chrome/content/rules/yapx.ru.xml
Labels: new-ruleset

#18737 Hotfix: EASE interstitial Link Failing for some Locales
  chromium/pages/cancel/style.css
  chromium/pages/cancel/ux.js
Labels: EASE, bug, ui

#18720 Create GileadHIV.com.xml
  src/chrome/content/rules/GileadHIV.com.xml
Labels: new-ruleset

#18721 Create evolutionofsmooth.com.xml
  src/chrome/content/rules/evolutionofsmooth.com.xml
Labels: new-ruleset, top-1m

#18738 Add Robert.ca.xml
  src/chrome/content/rules/Robert.ca.xml
Labels: new-ruleset

#18740 Add spacechase0.com.xml
  src/chrome/content/rules/spacechase0.com.xml
Labels: new-ruleset

#18741 Re-activate and Update HealthCare.gov.xml
  src/chrome/content/rules/HealthCare.gov.xml
  src/chrome/content/rules/Healthcare.gov.xml
Labels: ruleset-enhancement, top-1k

#18743 Rename and Update KAKAO.com.xml
  src/chrome/content/rules/KAKAO.com.xml
  src/chrome/content/rules/KAKAO.xml
Labels: ruleset-enhancement, top-1k

#18658 Create ruleset: AntiqueAppliances.com
  src/chrome/content/rules/AntiqueAppliances.com.xml
Labels: new-ruleset

#18742 Re-activate and Update Epoch Times related rulesets
  src/chrome/content/rules/EpochTimes.com.xml
  src/chrome/content/rules/Epoch_Times.xml
  src/chrome/content/rules/TheEpochTimes.com.xml
Labels: ruleset-enhancement, top-1k

#18744 Re-activate and simplify Stanford.edu.xml
  src/chrome/content/rules/Stanford-University-problematic.xml
  src/chrome/content/rules/Stanford-University.xml
  src/chrome/content/rules/Stanford.edu-falsemixed.xml
  src/chrome/content/rules/Stanford.edu.xml
Labels: ruleset-enhancement, top-10k

#18746 Re-activate and Update JetBrains.com.xml
  src/chrome/content/rules/JetBrains.com-falsemixed.xml
  src/chrome/content/rules/JetBrains.com.xml
  src/chrome/content/rules/JetBrains.xml
Labels: ruleset-enhancement, top-10k

#18747 Re-activate and Update India.com.xml
  src/chrome/content/rules/India.com.xml
Labels: ruleset-enhancement, top-10k

#18749 Remove 3D_Vision_Live.com.xml
  src/chrome/content/rules/3D_Vision_Live.com.xml
  src/chrome/content/rules/NVidia.xml
Labels: amazon-s3-2020, ruleset-enhancement

#18753 Remove AdExtent.com-problematic.xml
  src/chrome/content/rules/AdExtent.com-problematic.xml
  src/chrome/content/rules/AdExtent.com.xml
Labels: amazon-s3-2020

#18766 Add boards.4channel.org to ruleset
  src/chrome/content/rules/4chan.xml
Labels: ruleset-enhancement, top-1k
