Repository EFForg/https-everywhere, pull requests merged in 2019-09, with the labels that each got.

#18369 Upgrade travis ci distro from trusty to bionic
  .travis.yml
Labels: ruleset-testing

#18365 Create rufus.ie.xml
  src/chrome/content/rules/rufus.ie.xml
Labels: new-ruleset, top-10k

#18310 Update acast.com (fixes bbc.co.uk podcast playback)
  src/chrome/content/rules/acast.com.xml
Labels: high priority, ruleset-enhancement, top-100k

#18356 Update Threema.xml
  src/chrome/content/rules/Threema.xml
Labels: ruleset-enhancement, top-1m

#18358 Add rb-hk.de
  src/chrome/content/rules/rb-hk.de.xml
Labels: new-ruleset

#18339 Sina.cn
  src/chrome/content/rules/Sina.cn-mixedcontent.xml
  src/chrome/content/rules/Sina.cn.xml
Labels: ruleset-enhancement, top-10k

#18363 Update Weibo.cn.xml
  src/chrome/content/rules/Weibo.cn.xml
Labels: ruleset-enhancement, top-10k

#18364 Update Weibo.com.xml
  src/chrome/content/rules/Weibo.com.xml
Labels: ruleset-enhancement, top-100

#18352 Create EOS.org.xml
  src/chrome/content/rules/EOS.org.xml
Labels: new-ruleset, top-1m

#18379 Add timus.online.xml
  src/chrome/content/rules/timus.online.xml
Labels: new-ruleset

#18373 Update hsbc.com.hk.xml
  src/chrome/content/rules/hsbc.com.hk.xml
Labels: ruleset-enhancement, top-1k

#18317 Add Criu.org.xml
  src/chrome/content/rules/Criu.org.xml
Labels: new-ruleset

#18286 Create Ichijinsha.xml
  src/chrome/content/rules/Ichijinsha.co.jp.xml
Labels: new-ruleset

#18351 Add download.schneider-electric.com host target
  src/chrome/content/rules/Schneider-Electric.com.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#18382 Update University of South Florida rulesets
  src/chrome/content/rules/USFSP.edu.xml
  src/chrome/content/rules/University-of-South-Florida-mismatches.xml
  src/chrome/content/rules/University-of-South-Florida.xml
Labels: ruleset-enhancement, top-10k

#18383 Create hkexgroup.com.xml and lme.com.xml
  src/chrome/content/rules/hkex.com.hk.xml
  src/chrome/content/rules/hkexgroup.com.xml
  src/chrome/content/rules/lme.com.xml
Labels: top-100k

#18384 Create pull_request_template.md
  .github/pull_request_template.md
Labels: docs

#14747 Split zkb.ch from kantonalbanken.xml
  src/chrome/content/rules/Zkb.ch.xml
  src/chrome/content/rules/kantonalbanken.xml
Labels: top-100k

#18268 Create yash.osdn.jp.xml
  src/chrome/content/rules/yash.osdn.jp.xml
Labels: new-ruleset

#18325 Add Classpath.org.xml
  src/chrome/content/rules/Classpath.org.xml
Labels: new-ruleset

#18387 Fix fetch test fails when response header cannot be utf-8 decoded
  test/rules/src/https_everywhere_checker/http_client.py
Labels: ruleset-testing

#18355 Create freedos.org.xml
  src/chrome/content/rules/freedos.org.xml
Labels: failing tests, new-ruleset, top-1m

#18391 Add SystemSensor.ca.xml
  src/chrome/content/rules/SystemSensor.ca.xml
Labels: new-ruleset, top-1m

#18389 Create darlinghq.org.xml
  src/chrome/content/rules/darlinghq.org.xml
Labels: new-ruleset

#18396 Create meldmerge.org.xml
  src/chrome/content/rules/meldmerge.org.xml
Labels: new-ruleset, top-1m

#18393 Add E-Hentai.org.xml
  src/chrome/content/rules/E-Hentai-Forums.xml
  src/chrome/content/rules/E-Hentai.org.xml
Labels: new-ruleset, top-10k

#18385 Create HKET.com.xml
  src/chrome/content/rules/HKET.com.xml
Labels: new-ruleset, top-10k

#18335 Create Turkiye.gov.tr.xml
  src/chrome/content/rules/Turkiye.gov.tr.xml
Labels: new-ruleset, top-1k

#18329 Create Metro.Istanbul.xml
  src/chrome/content/rules/Metro.Istanbul.xml
Labels: new-ruleset, top-1m

#17657 Create jydoll.cn.xml
  src/chrome/content/rules/jydoll.cn.xml
Labels: china, new-ruleset, top-100k

#18401 Update amazon.cn.xml
  src/chrome/content/rules/Amazon.xml
  src/chrome/content/rules/amazon.cn.xml
Labels: china, top-100

#18327 Create 1over1.net.xml
  src/chrome/content/rules/1over1.net.xml
Labels: new-ruleset

#18402 Create qira.me.xml
  src/chrome/content/rules/qira.me.xml
Labels: new-ruleset

#18300 Update CUHK.xml
  src/chrome/content/rules/CUHK.xml
Labels: ruleset-enhancement, top-10k

#18297 Update WebMd.xml, related to #17965
  src/chrome/content/rules/WebMD.xml
Labels: ruleset-enhancement, top-1k

#18400 Update MIUI.com.xml
  src/chrome/content/rules/MIUI.com.xml
Labels: china, ruleset-enhancement, top-10k

#18332 Create TheFappeningBlog.com.xml [NSFW]
  src/chrome/content/rules/TheFappeningBlog.com.xml
Labels: new-ruleset, top-10k

#18284 Update tagesschau.de ruleset
  src/chrome/content/rules/tagesschau.de.xml
Labels: ruleset-enhancement, top-10k

#18270 Create Refinitiv.com.xml
  src/chrome/content/rules/Refinitiv.com.xml
Labels: new-ruleset, top-100k

#17441 Delete 148apps.com.xml
  src/chrome/content/rules/148apps.com.xml
Labels: ruleset-enhancement, top-1m

#18203 Update Experian.xml
  src/chrome/content/rules/Experian.xml
Labels: ruleset-enhancement, top-10k

#18271 Delete AEMI.xml, gone from dns
  src/chrome/content/rules/AEMI.xml
Labels: ruleset-enhancement

#13985 Delete Crowdin.net.xml and update Crowdin.com.xml
  src/chrome/content/rules/Crowdin.com.xml
  src/chrome/content/rules/Crowdin.net.xml
Labels: top-100k

#14910 Create GunFacts.info.xml
  src/chrome/content/rules/GunFacts.info.xml
Labels: new-ruleset, top-1m

#18398 Create mupen64plus.org.xml
  src/chrome/content/rules/mupen64plus.org.xml
Labels: new-ruleset

#18370 Ruleset for vaultize.com
  src/chrome/content/rules/Vaultize.com.xml
Labels: new-ruleset

#15183 TVMaze.com
  src/chrome/content/rules/TVMaze.com.xml
Labels: top-100k

#17211 Update CC.com.xml
  src/chrome/content/rules/CC.com.xml
Labels: ruleset-enhancement

#17210 Add Southpark.de.xml
  src/chrome/content/rules/Southpark.de.xml
Labels: new-ruleset

#17686 Add WorldOfGothic.com.xml
  src/chrome/content/rules/WorldOfGothic.com.xml
Labels: new-ruleset

#18306 Create Hollywoodtuna.com.xml
  src/chrome/content/rules/Hollywoodtuna.com.xml
Labels: new-ruleset, top-1m

#18266 Update Axis_Bank.xml
  src/chrome/content/rules/AxisBank.co.in.xml
  src/chrome/content/rules/AxisBank.com.xml
  src/chrome/content/rules/Axis_Bank.xml
Labels: ruleset-enhancement, top-1k

#18242 Add Randaris-Anime.net.xml
  src/chrome/content/rules/Randaris-Anime.net.xml
Labels: new-ruleset

#15362 Add ruleset gu.spb.ru
  src/chrome/content/rules/gu.spb.ru.xml
Labels: new-ruleset, top-100k

#15131 Add ruleset: SmartSource
  src/chrome/content/rules/SmartSource.xml
Labels: new-ruleset, top-1m

#18246 Create IslamicPortal.co.uk.xml
  src/chrome/content/rules/IslamicPortal.co.uk.xml
Labels: new-ruleset

#17730 Add WhatReallyHappened.com.xml
  src/chrome/content/rules/WhatReallyHappened.com.xml
Labels: new-ruleset, top-1m

#13352 Re-enable Arbor Networks ruleset
  src/chrome/content/rules/Arbor-Netscout.xml
Labels: ruleset-enhancement, top-1m

#18345 Create AlMostaneer.com.xml
  src/chrome/content/rules/AlMostaneer.com.xml
Labels: new-ruleset

#18132 Create StreamGoals.com.xml
  src/chrome/content/rules/StreamGoals.com.xml
Labels: new-ruleset, top-1m

#18314 Add Tpaste.us.xml
  src/chrome/content/rules/Tpaste.us.xml
Labels: new-ruleset

#17296 Add more hosts to Icinga.xml
  src/chrome/content/rules/Icinga.xml
Labels: ruleset-enhancement

#17666 Add Frauenpg.ch.xml
  src/chrome/content/rules/Frauenpg.ch.xml
Labels: new-ruleset

#18126 Create AntiPornGroup.com.xml
  src/chrome/content/rules/AntiPornGroup.com.xml
Labels: new-ruleset, top-1m

#15988 [Ticaretsicil.gov.tr] New ruleset
  src/chrome/content/rules/Ticaretsicil.gov.tr.xml
Labels: new-ruleset, top-1m

#18257 Update Factory_Expo_Home_Centers.xml
  src/chrome/content/rules/Factory_Expo_Home_Centers.xml
Labels: ruleset-enhancement, top-1m

#18261 Update Lohud.com.xml
  src/chrome/content/rules/Lohud.com.xml
Labels: ruleset-enhancement, top-100k

#18285 Update Folksam.se.xml
  src/chrome/content/rules/Folksam.se.xml
Labels: ruleset-enhancement

#18395 Add EHWiki.org.xml
  src/chrome/content/rules/EHWiki.org.xml
Labels: new-ruleset

#17700 Add targets to AdultSwim.com.xml and remove mixedcontent platform
  src/chrome/content/rules/AdultSwim.com.xml
  src/chrome/content/rules/Turner.com.xml
  src/chrome/content/rules/adultswim.xml
Labels: ruleset-enhancement, top-100k

#17390 Create debugconnection.com rule
  src/chrome/content/rules/debugconnection.xml
Labels: new-ruleset

#17792 Update Kriminalvarden.se.xml
  src/chrome/content/rules/Kriminalvarden.se.xml
Labels: ruleset-enhancement, top-1m

#18299 Create user.fm.xml
  src/chrome/content/rules/Fastmail.xml
  src/chrome/content/rules/user.fm.xml
Labels: new-ruleset, top-1m

#18278 Create BloggingTheology.com.xml
  src/chrome/content/rules/BloggingTheology.com.xml
Labels: new-ruleset

#18348 Create CafePlus.com.tr.xml
  src/chrome/content/rules/CafePlus.com.tr.xml
Labels: new-ruleset

#18322 Add rule for ocado.com
  src/chrome/content/rules/ocado.com.xml
Labels: new-ruleset, top-100k

#18165 Create Consensus911.org.xml
  src/chrome/content/rules/Consensus911.org.xml
Labels: new-ruleset

#18145 Create Commercial-Radio-Hong-Kong.xml
  src/chrome/content/rules/Commercial-Radio-Hong-Kong.xml
Labels: new-ruleset

#18228 Create Shamela.ws.xml
  src/chrome/content/rules/Shamela.ws.xml
Labels: new-ruleset, top-100k

#18248 Create AlDiwan.net.xml
  src/chrome/content/rules/AlDiwan.net.xml
Labels: new-ruleset, top-1m

#18316 Add Bues.ch.xml
  src/chrome/content/rules/Bues.ch.xml
Labels: new-ruleset

#18333 Create TheFappening2015.com.xml [NSFW]
  src/chrome/content/rules/TheFappening2015.com.xml
Labels: new-ruleset, top-1m

#18227 Create Pornwikileaks.com.xml
  src/chrome/content/rules/Pornwikileaks.com.xml
Labels: new-ruleset

#18232 Add Ace-book.net.xml
  src/chrome/content/rules/Ace-book.net.xml
Labels: new-ruleset

#18213 Added ruleset airsoftclubnederland.nl.xml
  src/chrome/content/rules/airsoftclubnederland.nl.xml
Labels: new-ruleset

#18394 Add HentaiVerse.org.xml
  src/chrome/content/rules/HentaiVerse.org.xml
Labels: new-ruleset

#18404 Create angr.io.xml
  src/chrome/content/rules/angr.io.xml
Labels: new-ruleset

#18196 Npm audit trivialize cdn rules scripts
  utils/trivialize-cdn-rules/package-lock.json
  utils/trivialize-cdn-rules/package.json
Labels: dependencies, security-critical, top-1m

#17789 Update Aftonbladet.xml
  src/chrome/content/rules/Aftonbladet.xml
Labels: ruleset-enhancement, top-10k

#17799 Create Polisen.se.xml
  src/chrome/content/rules/Polisen.se.xml
Labels: new-ruleset, top-1m

#18276 Update Riksgalden.se.xml
  src/chrome/content/rules/Riksgalden.se.xml
Labels: ruleset-enhancement

#18350 Create Kundelik.kz.xml
  src/chrome/content/rules/Kundelik.kz.xml
Labels: new-ruleset, top-100k

#17833 Update Fass.se.xml
  src/chrome/content/rules/Fass.se.xml
Labels: ruleset-enhancement, top-100k

#18349 Create YeniAkit.com.tr.xml
  src/chrome/content/rules/YeniAkit.com.tr.xml
Labels: new-ruleset, top-1k

#18334 Create Beardoholic.com.xml
  src/chrome/content/rules/Beardoholic.com.xml
Labels: new-ruleset, top-100k

#18330 Create LesLumieresdOrient.com.xml
  src/chrome/content/rules/LesLumieresdOrient.com.xml
Labels: new-ruleset

#18342 Create Moshimonsters.com.xml
  src/chrome/content/rules/Moshimonsters.com.xml
Labels: new-ruleset, top-100k

#18343 Re-enabling Kapital.kz.xml
  src/chrome/content/rules/Kapital.kz.xml
  src/chrome/content/rules/kapital.kz.xml
Labels: ruleset-enhancement, top-100k

#18267 Add learning.hccs.edu.xml
  src/chrome/content/rules/learning.hccs.edu.xml
Labels: new-ruleset

#17264 Create forum.gigabyte.ru.xml
  src/chrome/content/rules/forum.gigabyte.ru.xml
Labels: new-ruleset

#17691 Add acmp.ru.xml
  src/chrome/content/rules/acmp.ru.xml
Labels: new-ruleset, top-1m

#17728 Add unz.com.xml
  src/chrome/content/rules/unz.com.xml
Labels: new-ruleset, top-100k

#18193 Add Memo.tv.xml
  src/chrome/content/rules/Memo.tv.xml
Labels: new-ruleset

#18177 Add AmericanDreamCoalition.org.xml and ADCBlog.org.xml
  src/chrome/content/rules/ADCBlog.org.xml
  src/chrome/content/rules/AmericanDreamCoalition.org.xml
Labels: new-ruleset

#18054 Add Modicine.ru.xml
  src/chrome/content/rules/Modicine.ru.xml
Labels: new-ruleset

#18409 Create jacktrammellmusic.com.xml
  src/chrome/content/rules/jacktrammellmusic.com.xml
Labels: new-ruleset

#18241 Add rulesets for deutschlandfunk.de and dlf.de
  src/chrome/content/rules/Deutschlandfunk.de.xml
  src/chrome/content/rules/dlf.de.xml
Labels: new-ruleset, top-100k

#18304 Run hsts-prune and update impacted rulesets
  src/chrome/content/rules/1s_and_0s.nl.xml
  src/chrome/content/rules/Afterpay.com.xml
  src/chrome/content/rules/Asana.xml
  src/chrome/content/rules/Bitly_branded_short_domains.xml
  src/chrome/content/rules/BodyBuilding.com.xml
  src/chrome/content/rules/Cyphar.com.xml
  src/chrome/content/rules/Daniel_Miessler.com.xml
  src/chrome/content/rules/ECPIC.gov.xml
  src/chrome/content/rules/EFF.xml
  src/chrome/content/rules/Edas.xml
  src/chrome/content/rules/Filehippo.com.xml
  src/chrome/content/rules/Fimfiction.net.xml
  src/chrome/content/rules/Global-Witness.xml
  src/chrome/content/rules/Invidio.us.xml
  src/chrome/content/rules/ManilaPrinciples.org.xml
  src/chrome/content/rules/Marxists.xml
  src/chrome/content/rules/Miniclip.com.xml
  src/chrome/content/rules/Miniclip_CDN.com.xml
  src/chrome/content/rules/NAY.sk.xml
  src/chrome/content/rules/Naslovi.xml
  src/chrome/content/rules/Nstatic.com.xml
  src/chrome/content/rules/PCI-Security-Standards-Council.xml
  src/chrome/content/rules/PayMongo.xml
  src/chrome/content/rules/Perfect-Privacy.com.xml
  src/chrome/content/rules/Qabel.xml
  src/chrome/content/rules/Raiffeisen.ch.xml
  src/chrome/content/rules/Sauce_Labs.xml
  src/chrome/content/rules/Spilnu.dk.xml
  src/chrome/content/rules/TimeTrade.xml
  src/chrome/content/rules/US_Fish_and_Wildlife_Service.xml
  src/chrome/content/rules/Upstart.xml
  src/chrome/content/rules/Vivaldi.net.xml
  src/chrome/content/rules/Wit.ai.xml
  src/chrome/content/rules/audioboom.com.xml
  src/chrome/content/rules/l214.com.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100k

#18259 Create Tokyo-Broadcasting-System-Television.xml
  src/chrome/content/rules/Tokyo-Broadcasting-System-Television.xml
Labels: new-ruleset, top-100k

#18262 Create Xonotic.org.xml
  src/chrome/content/rules/Xonotic.org.xml
Labels: new-ruleset

#18245 Create IslamicBulletin.org.xml
  src/chrome/content/rules/IslamicBulletin.org.xml
Labels: new-ruleset

#18189 Remove broken hosts from LIU.se.xml
  src/chrome/content/rules/LIU.se.xml
Labels: ruleset-enhancement, top-100k

#18172 Create Choualbox.com.xml
  src/chrome/content/rules/Choualbox.com.xml
Labels: new-ruleset, top-1m

#17453 Update act-on.com.xml
  src/chrome/content/rules/Act-On.com.xml
  src/chrome/content/rules/act-on.com-mixedcontent.xml
  src/chrome/content/rules/act-on.com.xml
Labels: ruleset-enhancement

#18130 Create JusticeForStrumia.org.xml
  src/chrome/content/rules/JusticeForStrumia.org.xml
Labels: new-ruleset

#18125 Create AlRadNet.com.xml
  src/chrome/content/rules/AlRadNet.com.xml
Labels: new-ruleset

#18123 Create Nuqayah.com.xml
  src/chrome/content/rules/Nuqayah.com.xml
Labels: new-ruleset

#18124 Create AlRo7.net.xml
  src/chrome/content/rules/AlRo7.net.xml
Labels: new-ruleset, top-1m

#18279 Re-enabling OpenSignal.com.xml
  src/chrome/content/rules/OpenSignal.com.xml
Labels: ruleset-enhancement

#18085 Create trimble.com.xml
  src/chrome/content/rules/trimble.com.xml
Labels: new-ruleset, top-10k

#17609 Create ElberethZone.xml
  src/chrome/content/rules/ElberethZone.xml
Labels: new-ruleset

#18198 Add PremierLiga.ru.xml
  src/chrome/content/rules/PremierLiga.ru.xml
Labels: new-ruleset, top-1m

#17681 Add ShoutWiki.com.xml
  src/chrome/content/rules/ShoutWiki.com.xml
Labels: new-ruleset

#17591 Create Finto.fi.xml
  src/chrome/content/rules/Finto.fi.xml
Labels: new-ruleset

#15994 [Fizy.com] New ruleset
  src/chrome/content/rules/Fizy.com.xml
Labels: new-ruleset, top-1m

#15989 [Wiki-zero.net] New ruleset
  src/chrome/content/rules/Wiki-zero.net.xml
Labels: new-ruleset, top-100k

#18255 Add Pinboard.in.xml
  src/chrome/content/rules/Pinboard.in.xml
  src/chrome/content/rules/Pinboard.xml
Labels: new-ruleset, top-1m

#17671 Create pearsoncmg.com.xml
  src/chrome/content/rules/pearsoncmg.com.xml
Labels: new-ruleset

#17654 Add privat.bahnhof.se
  src/chrome/content/rules/Bahnhof.se.xml
Labels: ruleset-enhancement, top-100k

#18253 Add Boomerang.com.xml
  src/chrome/content/rules/Boomerang.com.xml
  src/chrome/content/rules/Boomerang.xml
Labels: new-ruleset, top-1m

#17289 Update OpenTTD
  src/chrome/content/rules/OpenTTD-expired.xml
  src/chrome/content/rules/OpenTTD.xml
  src/chrome/content/rules/Openttdcoop.org.xml
Labels: ruleset-enhancement

#17286 Add Otrs rulesets
  src/chrome/content/rules/Otrs.com.xml
  src/chrome/content/rules/Otrs.org.xml
Labels: new-ruleset

#17295 Add Nagios
  src/chrome/content/rules/Nagios.com.xml
  src/chrome/content/rules/Nagios.org.xml
Labels: new-ruleset

#18131 Create StephenHicks.org.xml
  src/chrome/content/rules/StephenHicks.org.xml
Labels: new-ruleset, top-1m

#17257 Create Virtmo.com.xml
  src/chrome/content/rules/virtmo.com.xml
Labels: new-ruleset

#17174 Add Me.bf.xml
  src/chrome/content/rules/Me.bf.xml
Labels: new-ruleset

#15510 Create ruleset: Dap.com
  src/chrome/content/rules/Dap.com.xml
Labels: new-ruleset

#16614 Add ruleset: Doutula.com
  src/chrome/content/rules/Doutula.com.xml
Labels: china, new-ruleset, top-100k

#17738 Add Dolibarr.org.xml
  src/chrome/content/rules/Dolibarr.org.xml
Labels: new-ruleset, top-1m

#17467 Update AlaskaAirlines.xml
  src/chrome/content/rules/AlaskaAirlines.xml
Labels: hold, needs revision, ruleset-enhancement

#16772 Add ruleset for project-diva-ac.net
  src/chrome/content/rules/Project-diva-ac.net.xml
Labels: new-ruleset

#16631 Add ruleset: Synthfont.com
  src/chrome/content/rules/Synthfont.com.xml
Labels: new-ruleset, top-1m

#14748 Update Banque_Cantonale_du_Valais.xml
  src/chrome/content/rules/Banque_Cantonale_du_Valais.xml
Labels: ruleset-enhancement, top-1m

#15754 Update Alpine_Linux.org.xml
  src/chrome/content/rules/AlpineLinux.org.xml
  src/chrome/content/rules/Alpine_Linux.org.xml
Labels: ruleset-enhancement, top-100k

#18312 Create snapraid.it.xml
  src/chrome/content/rules/snapraid.it.xml
Labels: new-ruleset

#17739 Add Suitecrm.com.xml
  src/chrome/content/rules/Suitecrm.com.xml
Labels: new-ruleset, top-1m

#13988 * Certificate chain for maths has been fixed, removed comment, and ad…
  src/chrome/content/rules/University-of-Oxford.xml
Labels: needs revision, ruleset-enhancement, top-10k

#17414 Create ruleset for lookup.uribl.com
  src/chrome/content/rules/Lookup.uribl.com.xml
Labels: new-ruleset

#17103 Add more targets to Init7.xml
  src/chrome/content/rules/Init7.xml
Labels: new-ruleset, ruleset-enhancement, top-1m

#18291 Create Japanese-Communist-Party.xml
  src/chrome/content/rules/Japanese-Communist-Party.xml
Labels: new-ruleset
