Repository EFForg/https-everywhere, pull requests merged in 2019-07, with the labels that each got.

#18149 Create FreedomHK.net.xml
  src/chrome/content/rules/FreedomHK.net.xml
Labels: new-ruleset

#18144 Create NotBackingDownUMass.org.xml
  src/chrome/content/rules/NotBackingDownUMass.org.xml
Labels: new-ruleset, top-1m

#18150 Create LIHKG.com.xml
  src/chrome/content/rules/LIHKG.com.xml
Labels: new-ruleset, top-10k

#18154 Update OpenStreetMap.de.xml
  src/chrome/content/rules/OpenStreetMap.de.xml
Labels: ruleset-enhancement, top-1m

#18075 Update Pearson.xml
  src/chrome/content/rules/Pearson.xml
Labels: ruleset-enhancement, top-10k

#18115 [LightTheNight.org] Simplify and enable ruleset
  src/chrome/content/rules/LightTheNight.org.xml
  src/chrome/content/rules/Light_the_Night.org.xml
Labels: ruleset-enhancement

#18155 Add world-nuclear-news.org
  src/chrome/content/rules/World-Nuclear-News.org.xml
Labels: new-ruleset, top-1m

#18133 Added semicolons to avoid auto semicolon insertion
  chromium/pages/options/ux.js
Labels: code-style

#18169 Create Poesie-Francaise.fr.xml
  src/chrome/content/rules/Poesie-Francaise.fr.xml
Labels: new-ruleset, top-1m

#18112 Run hsts-prune and fix impacted rulesets
  src/chrome/content/rules/911.gov.xml
  src/chrome/content/rules/Abuse.ch.xml
  src/chrome/content/rules/Bitly_branded_short_domains.xml
  src/chrome/content/rules/CDN_Instagram.com.xml
  src/chrome/content/rules/Check_Point-problematic.xml
  src/chrome/content/rules/Check_Point.xml
  src/chrome/content/rules/Digitec.ch.xml
  src/chrome/content/rules/Digitecgalaxus.ch.xml
  src/chrome/content/rules/Distraction.gov.xml
  src/chrome/content/rules/Equiac.com.xml
  src/chrome/content/rules/Galaxus.ch.xml
  src/chrome/content/rules/Google.com_Subdomains.xml
  src/chrome/content/rules/Inphi.xml
  src/chrome/content/rules/Instagr.am.xml
  src/chrome/content/rules/Instagram.xml
  src/chrome/content/rules/Instagrampartners.com.xml
  src/chrome/content/rules/M-net.de.xml
  src/chrome/content/rules/PostImage.xml
  src/chrome/content/rules/Privacy_tools.io.xml
  src/chrome/content/rules/Skyscanner.xml
  src/chrome/content/rules/Traffic_Safety_Marketing.gov.xml
  utils/ruleset-whitelist.csv
Labels: top-100

#18164 Create Dictionary.com.xml
  src/chrome/content/rules/Dictionary.com.xml
Labels: new-ruleset, top-10k

#17861 Add SkepticsAnnotatedBible.com
  src/chrome/content/rules/SkepticsAnnotatedBible.com.xml
Labels: new-ruleset, top-1m

#18113 Split and simplify clicky rulesets
  src/chrome/content/rules/Clicky.com.xml
  src/chrome/content/rules/GetClicky.com.xml
  src/chrome/content/rules/Getclicky.xml
  src/chrome/content/rules/StaticStuff.net.xml
Labels: ruleset-enhancement, top-100k

#18179 Update jenkins-ci.org ruleset
  src/chrome/content/rules/Jenkins-CI.org.xml
Labels: ruleset-enhancement, top-1m

#17621 Create GaySexPositionsGuide.com.xml
  src/chrome/content/rules/GaySexPositionsGuide.com.xml
Labels: new-ruleset

#17690 Add Reclam.de.xml
  src/chrome/content/rules/Reclam.de.xml
Labels: new-ruleset, top-1m

#17249 Create WhitneyWisconsinFans.com.xml
  src/chrome/content/rules/WhitneyWisconsinFans.com.xml
Labels: new-ruleset

#18161 Update hko.gov.hk.xml to include weather.gov.hk
  src/chrome/content/rules/hko.gov.hk.xml
Labels: ruleset-enhancement, top-10k

#18170 Create ModrsBook.com.xml
  src/chrome/content/rules/ModrsBook.com.xml
Labels: new-ruleset, top-100k

#18129 Create KnowTheirName.com.xml
  src/chrome/content/rules/KnowTheirName.com.xml
Labels: new-ruleset

#18139 Update Github-Pages.xml
  src/chrome/content/rules/Github-Pages.xml
Labels: ruleset-enhancement

#18146 Create Techquila.co.in.xml
  src/chrome/content/rules/Techquila.co.in.xml
Labels: new-ruleset, top-100k

#18128 Create Fikriyat.com.xml
  src/chrome/content/rules/Fikriyat.com.xml
Labels: new-ruleset, top-100k

#18181 add target api.mongodb.com
  src/chrome/content/rules/MongoDB.com.xml
Labels: ruleset-enhancement, top-10k

#15767 Update OASIS_Open.org.xml
  src/chrome/content/rules/OASIS_Open.org.xml
Labels: ruleset-enhancement, top-1m

#18183 [AmericanScientist.org] Simplify ruleset
  src/chrome/content/rules/AmericanScientist.org.xml
  src/chrome/content/rules/American_Scientist.org.xml
Labels: ruleset-enhancement, top-1m

#18184 Create SmallCultFollowing.com.xml
  src/chrome/content/rules/SmallCultFollowing.com.xml
Labels: new-ruleset

#18185 [ProspectMagazine.co.uk] Simplify ruleset
  src/chrome/content/rules/Prospect-Magazine.xml
  src/chrome/content/rules/ProspectMagazine.co.uk.xml
Labels: ruleset-enhancement, top-1m

#18187 Create Alkalm.net.xml
  src/chrome/content/rules/Alkalm.net.xml
Labels: new-ruleset

#18188 [BigCartel.com] Increase coverage
  src/chrome/content/rules/Big-Cartel.xml
  src/chrome/content/rules/BigCartel.com.xml
Labels: ruleset-enhancement, top-10k

#18152 Update CUHK.xml
  src/chrome/content/rules/CUHK.xml
Labels: ruleset-enhancement, top-10k

#18162 Create mhfa.com.au.xml
  src/chrome/content/rules/mhfa.com.au.xml
Labels: new-ruleset, top-1m

#18166 Create Stanographer.com.xml
  src/chrome/content/rules/Stanographer.com.xml
Labels: new-ruleset

#18168 Create Salla.sa.xml
  src/chrome/content/rules/Salla.sa.xml
Labels: new-ruleset, top-100k

#18173 Create jma.go.jp.xml
  src/chrome/content/rules/jma.go.jp.xml
Labels: new-ruleset, top-10k

#18041 Cwgv.com.tw.xml
  src/chrome/content/rules/cwgv.com.tw.xml
Labels: new-ruleset

#18044 Create taihe.com.xml
  src/chrome/content/rules/taihe.com.xml
Labels: new-ruleset, top-100k

#18050 Add Spinroot.com.xml
  src/chrome/content/rules/Spinroot.com.xml
Labels: new-ruleset

#17996 Add ruleset: EWONTFIX.com
  src/chrome/content/rules/EWONTFIX.com.xml
Labels: new-ruleset

#17733 Add UnRealWorld.fi.xml
  src/chrome/content/rules/UnRealWorld.fi.xml
Labels: new-ruleset, top-1m

#17839 Add netn.fi.xml
  src/chrome/content/rules/netn.fi.xml
Labels: new-ruleset

#17721 Add as200651.net
  src/chrome/content/rules/AS200651.net.xml
Labels: new-ruleset

#17800 Update Fastmail.xml
  src/chrome/content/rules/Fastmail.xml
Labels: ruleset-enhancement, top-100k

#17830 Add ProgramaJaponesOnline.com.br.xml
  src/chrome/content/rules/ProgramaJaponesOnline.com.br.xml
Labels: new-ruleset, top-1m

#18178 Update jenkins.io ruleset
  src/chrome/content/rules/jenkins.io.xml
Labels: ruleset-enhancement, top-100k

#18074 Delete GTCs-Online.xml
  src/chrome/content/rules/GTCs-Online.xml
Labels: ruleset-enhancement

#18167 Create TafasirStore.com.xml
  src/chrome/content/rules/TafasirStore.com.xml
Labels: new-ruleset

#17680 Add Css3test.com.xml
  src/chrome/content/rules/Css3test.com.xml
Labels: new-ruleset, top-1m

#17987 Delete FOX-Toolkit.xml
  src/chrome/content/rules/FOX-Toolkit.xml
Labels: ruleset-enhancement

#15636 Add ruleset for pcshannover.de #15635
  src/chrome/content/rules/pcshannover.de.xml
Labels: new-ruleset

#17645 [H5py.org] New ruleset
  src/chrome/content/rules/H5py.org.xml
Labels: new-ruleset, top-1m

#18215 Create OpenVim.com.xml
  src/chrome/content/rules/OpenVim.com.xml
Labels: new-ruleset, top-1m

#18163 Add anu.edu.au
  src/chrome/content/rules/ANU.edu.au.xml
Labels: new-ruleset, top-100k

#18216 Create RamanujanMachine.com.xml
  src/chrome/content/rules/RamanujanMachine.com.xml
Labels: new-ruleset

#18205 Add ruleset for cyberciti.biz
  src/chrome/content/rules/cyberciti.biz.xml
Labels: new-ruleset, top-10k

#18211 Create Junkudo.xml
  src/chrome/content/rules/Junkudo.xml
Labels: new-ruleset

#18045 Create Birdtree.org.xml
  src/chrome/content/rules/Birdtree.org.xml
Labels: new-ruleset

#16715 Create Adam-Barth.xml
  src/chrome/content/rules/Adam-Barth.xml
Labels: new-ruleset

#17608 Create MusikhusetAarhus.dk.xml
  src/chrome/content/rules/MusikhusetAarhus.dk.xml
Labels: new-ruleset

#18219 Create NatureIndex.com.xml
  src/chrome/content/rules/NatureIndex.com.xml
Labels: new-ruleset, top-1m

#18221 Create AudioBooks.com.xml
  src/chrome/content/rules/AudioBooks.com.xml
Labels: new-ruleset, top-100k

#18220 Create Level1Techs.com.xml
  src/chrome/content/rules/Level1Techs.com.xml
Labels: new-ruleset, top-100k

#18223 [TornadoWeb.org] Enable ruleset
  src/chrome/content/rules/TornadoWeb.org.xml
  src/chrome/content/rules/Tornado_Web.org.xml
Labels: new-ruleset, top-1m

#18224 Create Beuc.net.xml
  src/chrome/content/rules/Beuc.net.xml
Labels: new-ruleset, top-1m

#18214 Create Nazariyat.org.xml
  src/chrome/content/rules/Nazariyat.org.xml
Labels: new-ruleset

#18210 Create Wellcome-HK-Lucky-Draws.xml
  src/chrome/content/rules/Wellcome-HK-Lucky-Draws.xml
Labels: new-ruleset

#18230 Create Wayneashworthart.com.xml
  src/chrome/content/rules/Wayneashworthart.com.xml
Labels: new-ruleset

#17622 Remove byond rule
  src/chrome/content/rules/Byond.com.xml
Labels: ruleset-bug, top-100k, webmaster-request

#18182 [Barclays.co.uk] Simplify and reactivate ruleset
  src/chrome/content/rules/Barclays.co.uk.xml
  src/chrome/content/rules/Barclays.xml
Labels: ruleset-enhancement, top-10k

#18084 Add related rulesets
  src/chrome/content/rules/Aqicn.org.xml
  src/chrome/content/rules/Waqi.info.xml
Labels: ruleset-enhancement, top-100k

#18053 Add Encyclopatia.ru.xml
  src/chrome/content/rules/Encyclopatia.ru.xml
Labels: new-ruleset, top-1m
