Repository EFForg/https-everywhere, pull requests merged in 2019-06, with the labels that each got.

#18048 Update KOOORA.com.xml
  src/chrome/content/rules/KOOORA.com.xml
Labels: ruleset-enhancement, top-1k

#18047 Update dianping.com.xml
  src/chrome/content/rules/dianping.com.xml
Labels: ruleset-enhancement, top-1k

#18006 Create Download-Islamic-Religion-PDF-Ebooks.com.xml
  src/chrome/content/rules/Download-Islamic-Religion-PDF-Ebooks.com.xml
Labels: new-ruleset, top-1m

#17981 Create Waqfeya.com.xml
  src/chrome/content/rules/Waqfeya.com.xml
Labels: new-ruleset, top-10k

#18031 Create WhatCanIDoForMozilla.org.xml
  src/chrome/content/rules/WhatCanIDoForMozilla.org.xml
Labels: new-ruleset

#18028 Add ruleset for appliedprivacy.net
  src/chrome/content/rules/AppliedPrivacy.net.xml
Labels: new-ruleset

#18004 Create FluentInTurkish.com.xml
  src/chrome/content/rules/FluentInTurkish.com.xml
Labels: new-ruleset

#18008 Create LTTStore.com.xml
  src/chrome/content/rules/LTTStore.com.xml
Labels: new-ruleset, top-1m

#17994 Add ruleset: Collabnix.com
  src/chrome/content/rules/Collabnix.com.xml
Labels: new-ruleset, top-1m

#17991 Create syrianmalware.com.xml
  src/chrome/content/rules/syrianmalware.com.xml
Labels: new-ruleset

#17707 Add Rejected.us.xml
  src/chrome/content/rules/Rejected.us.xml
Labels: new-ruleset

#17798 Add Racketboy.com.xml
  src/chrome/content/rules/Racketboy.com.xml
Labels: new-ruleset, top-1m

#17887 Update Indiana_State_University.xml
  src/chrome/content/rules/Indiana_State_University.xml
Labels: ruleset-enhancement, top-100k

#18040 Update princeton.edu ruleset
  src/chrome/content/rules/Princeton.edu.xml
Labels: ruleset-enhancement, top-10k

#18037 Fix and update t-online.de ruleset
  src/chrome/content/rules/T-Online.xml
Labels: ruleset-enhancement, top-1k

#18057 Add Ghidra-SRE.org.xml
  src/chrome/content/rules/Ghidra-SRE.org.xml
  src/chrome/content/rules/National-Security-Agency.xml
Labels: new-ruleset, top-1m

#17995 Add ruleset: EtaLabs.net
  src/chrome/content/rules/EtaLabs.net.xml
Labels: new-ruleset

#18060 Update TIME.com.xml
  src/chrome/content/rules/TIME.com.xml
Labels: ruleset-enhancement, top-10k

#18052 Replace Array() with []
  chromium/background-scripts/rules.js
Labels: code-style

#17855 Add script to trivialize some left-wildcard targets
  utils/trivialize-rules/package-lock.json
  utils/trivialize-rules/package.json
  utils/trivialize-rules/trivialize-targets.js
Labels: toolchain

#17910 Update schema.xml
  test/validations/relaxng/schema.xml
Labels: ruleset-testing, toolchain

#18065 new Array() => []
  utils/trivialize-rules/trivialize-targets.js
Labels: code-style, minor

#18064 Fix ruleset editor
  chromium/pages/options/index.html
  chromium/pages/options/style.css
  chromium/pages/options/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#18061 Remove GPL2 code from rules test
  test/rules/src/https_everywhere_checker/check_rules.py
  test/rules/src/https_everywhere_checker/gvgen.py
  test/rules/src/https_everywhere_checker/rule_trie.py
Labels: EFF, toolchain

#17990 Re-enable Infradead.org.xml
  src/chrome/content/rules/Infradead.org.xml
Labels: ruleset-enhancement, top-1m

#18077 Update Cambridge-University-Press.xml, remove duplicates
  src/chrome/content/rules/Cambridge-Journals.xml
  src/chrome/content/rules/Cambridge-University-Press.xml
  src/chrome/content/rules/WordPress-blogs.xml
Labels: top-1k

#18071 Remove obsolete cloudfront rewrites from iEntry.com.xml
  src/chrome/content/rules/iEntry.com.xml
  src/chrome/content/rules/iEntry.xml
Labels: ruleset-enhancement, top-1m

#18070 Update University_of_Applied_Sciences_Kiel.xml
  src/chrome/content/rules/University_of_Applied_Sciences_Kiel.xml
Labels: ruleset-enhancement, top-100k

#18022 [RanalloLawOffice.com] Simplify and rename ruleset
  src/chrome/content/rules/Nicholas_Ranallo.xml
  src/chrome/content/rules/RanalloLawOffice.com.xml
Labels: ruleset-enhancement

#18072 Trivialize and update University_of_Houston.xml
  src/chrome/content/rules/University_of_Houston.xml
Labels: top-10k

#18010 Create 3Blue1Brown.com.xml
  src/chrome/content/rules/3Blue1Brown.com.xml
Labels: new-ruleset, top-1m

#17992 Add ruleset: Labix.org
  src/chrome/content/rules/Labix.org.xml
Labels: new-ruleset, top-1m

#18049 Update KOOORA.com.xml
  src/chrome/content/rules/KOOORA.com.xml
Labels: ruleset-enhancement, top-1k

#18073 Update HurricaneElectric.xml
  src/chrome/content/rules/HurricaneElectric.xml
Labels: top-100k

#17961 [NameSilo.com] New ruleset
  src/chrome/content/rules/NameSilo.xml
Labels: new-ruleset, top-100k

#17984 Create TheOJ.org.xml
  src/chrome/content/rules/TheOJ.org.xml
Labels: new-ruleset, top-1m

#18014 Create Cadence.gq.xml
  src/chrome/content/rules/Cadence.gq.xml
  src/chrome/content/rules/Cadence.moe.xml
Labels: new-ruleset

#17904 Re-activate and update FlyersRights.xml
  src/chrome/content/rules/FlyersRights.com.xml
  src/chrome/content/rules/FlyersRights.org.xml
Labels: ruleset-enhancement

#18033 Create FaithBooks.co.uk.xml
  src/chrome/content/rules/FaithBooks.co.uk.xml
Labels: new-ruleset

#18034 Create TypeRacer.com.xml
  src/chrome/content/rules/TypeRacer.com.xml
Labels: new-ruleset, top-100k

#18032 Create Al-Sabeel.net.xml
  src/chrome/content/rules/Al-Sabeel.net.xml
Labels: new-ruleset, top-1m

#17857 Create BinBayyah.net.xml
  src/chrome/content/rules/BinBayyah.net.xml
Labels: new-ruleset

#17832 Update AkademiskaHus.se.xml
  src/chrome/content/rules/AkademiskaHus.se.xml
Labels: ruleset-enhancement, top-1m

#17782 Create AlFeker.net.xml
  src/chrome/content/rules/AlFeker.net.xml
Labels: new-ruleset, top-100k

#17784 Create Uoydqx.com.xml
  src/chrome/content/rules/Uoydqx.com.xml
Labels: new-ruleset

#17767 Create bankid.com.xml
  src/chrome/content/rules/bankid.com.xml
Labels: new-ruleset, top-100k

#18079 Create AABEST.com.xml
  src/chrome/content/rules/AABEST.com.xml
  src/chrome/content/rules/AASTOCKS.com.xml
Labels: top-10k

#18078 Add m.thepiratebay.org
  src/chrome/content/rules/ThePirateBay.xml
  utils/ruleset-whitelist.csv
Labels: top-1k

#15766 Update FreeDesktop.xml
  src/chrome/content/rules/FreeDesktop.xml
Labels: ruleset-enhancement, top-1m

#17740 [Aqicn.org] New ruleset
  src/chrome/content/rules/Aqicn.org.xml
Labels: failing tests, new-ruleset, top-100k

#17741 [Waqi.info] New ruleset
  src/chrome/content/rules/Waqi.info.xml
Labels: failing tests, new-ruleset, top-100k

#15977 [Limesurvey.com] Split rulesets
  src/chrome/content/rules/LimeSurvey.com.xml
  src/chrome/content/rules/LimeSurvey.xml
Labels: top-1m

#17761 Create handelsbanken.se.xml
  src/chrome/content/rules/handelsbanken.se.xml
Labels: new-ruleset, top-100k

#18090 Create EditorConfig.org.xml
  src/chrome/content/rules/EditorConfig.org.xml
Labels: new-ruleset, top-1m

#17661 [LimeSurvey.org] Fix cert mismatch
  src/chrome/content/rules/LimeSurvey.org.xml
Labels: ruleset-enhancement, top-1m

#18087 Update UST.hk.xml, add www.cdgt.ust.hk
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement, top-100k

#18082 Create TheBabushkasOfChernobyl.com.xml
  src/chrome/content/rules/TheBabushkasOfChernobyl.com.xml
Labels: new-ruleset, top-1m

#17863 [Toastmasters.org] New ruleset
  src/chrome/content/rules/Toastmasters.org.xml
Labels: new-ruleset, top-100k

#18080 Add hzqx.com.xml
  src/chrome/content/rules/hzqx.com.xml
Labels: new-ruleset

#18094 Add changelogs.ubuntu.com
  src/chrome/content/rules/Ubuntu.xml
Labels: new-ruleset, top-10k

#18095 Add zufe.edu.cn.xml
  src/chrome/content/rules/zufe.edu.cn.xml
Labels: new-ruleset, top-100k

#18096 Updated USTC.edu.cn.xml
  src/chrome/content/rules/USTC.edu.cn.xml
Labels: ruleset-enhancement, top-10k

#18091 Scale the popup window to device width
  chromium/pages/popup/index.html
Labels: ui

#17742 Do not call safeToSecureCookie until necessary
  chromium/background-scripts/rules.js
Labels: enhancement

#18100 Add NoelShack.com.xml
  src/chrome/content/rules/NoelShack.com.xml
Labels: new-ruleset, top-100k

#18102 Add Libevent.org.xml
  src/chrome/content/rules/Libevent.org.xml
Labels: new-ruleset, top-1m

#18101 Add more hosts to Omnirom.org.xml
  src/chrome/content/rules/Omnirom.org.xml
Labels: ruleset-enhancement

#18109 Making the options and cancel pages more mobile friendly
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
  chromium/pages/options/index.html
  chromium/pages/options/style.css
  chromium/pages/options/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#18119 Create SesliSozluk.net.xml
  src/chrome/content/rules/SesliSozluk.net.xml
Labels: top-100k

#18104 fixes #18103
  utils/android-push.sh
Labels: needs more info

#18116 Create LeGorafi.fr.xml
  src/chrome/content/rules/LeGorafi.fr.xml
Labels: new-ruleset, top-100k

#18135 Update expreview.com.xml
  src/chrome/content/rules/expreview.com.xml
Labels: ruleset-enhancement

#18114 [USRowing.org] Default_off ruleset
  src/chrome/content/rules/USRowing.xml
Labels: ruleset-bug, top-1m

#18108 Add skyscraperpage.com
  src/chrome/content/rules/SkyscraperPage.com.xml
Labels: new-ruleset, top-100k

#18141 Create LGTM.com.xml
  src/chrome/content/rules/LGTM.com.xml
Labels: new-ruleset

#18137 Update Archive.is.xml
  src/chrome/content/rules/Archive.is.xml
Labels: ruleset-enhancement, top-10k

#18122 Create AlNawawiForty.com.xml
  src/chrome/content/rules/AlNawawiForty.com.xml
Labels: new-ruleset
