Repository EFForg/https-everywhere, pull requests merged in 2019-10, with the labels that each got.

#18467 Create logicalincrements.com.xml
  src/chrome/content/rules/logicalincrements.com.xml
Labels: new-ruleset, top-100k

#17828 Add PokeCommunity.com.xml
  src/chrome/content/rules/PokeCommunity.com.xml
Labels: new-ruleset, top-100k

#18463 Remove duplicates dice.com, www.dice.com
  src/chrome/content/rules/Dice-problematic.xml
  src/chrome/content/rules/Dice.com.xml
  src/chrome/content/rules/Dice.xml
Labels: ruleset-enhancement, top-10k

#15283 [TransLink.ca] New ruleset
  src/chrome/content/rules/Compasscard.ca.xml
  src/chrome/content/rules/TransLink.ca.xml
Labels: new-ruleset, top-100k

#18460 Remove duplicates members.webs.com
  src/chrome/content/rules/Webs-MixedContent.xml
  src/chrome/content/rules/Webs.com.xml
  src/chrome/content/rules/Webs.xml
  src/chrome/content/rules/Websimages.com.xml
Labels: ruleset-enhancement, top-10k

#18465 Create nerdbacon.com.xml
  src/chrome/content/rules/nerdbacon.com.xml
Labels: new-ruleset

#18397 Delete outdated rules from sumologic.com.
  src/chrome/content/rules/Sumo_Logic.com.xml
Labels: owner, ruleset-enhancement

#18353 Re-enabling Abbott-Laboratories.xml
  src/chrome/content/rules/Abbott-Laboratories.xml
  src/chrome/content/rules/abbott.com.xml
Labels: ruleset-enhancement, top-100k

#17258 Create XenoNode.com.xml
  src/chrome/content/rules/XenoNode.com.xml
Labels: new-ruleset

#17069 Add 179.ru
  src/chrome/content/rules/179.ru.xml
Labels: failing tests, new-ruleset, top-1m

#18468 Create interactivepasts.com.xml
  src/chrome/content/rules/interactivepasts.com.xml
Labels: new-ruleset

#17345 Create ruleset: Abercrombie.com
  src/chrome/content/rules/Abercrombie.xml
  utils/ruleset-whitelist.csv
Labels: new-ruleset, top-10k

#18303 Create Iraqueer.org.xml
  src/chrome/content/rules/Iraqueer.org.xml
Labels: new-ruleset

#18462 Remove duplicates help.walmart.com
  src/chrome/content/rules/Walmart.com-falsemixed.xml
  src/chrome/content/rules/Walmart.com.xml
Labels: ruleset-enhancement, top-1k

#18336 Create KizlarSoruyor.com.xml
  src/chrome/content/rules/KizlarSoruyor.com.xml
Labels: new-ruleset, top-10k, top-1k

#18436 Create test-smoke.org.xml
  src/chrome/content/rules/test-smoke.org.xml
Labels: new-ruleset

#16022 Update rules for notalwaysright.com and related domains
  src/chrome/content/rules/NotAlwaysFriendly.com.xml
  src/chrome/content/rules/NotAlwaysHopeless.com.xml
  src/chrome/content/rules/NotAlwaysRight.com.xml
  src/chrome/content/rules/NotAlwaysWorking.com.xml
  src/chrome/content/rules/notalways.xml
Labels: failing tests, ruleset-enhancement, top-100k

#18473 Create curve.co.uk.xml
  src/chrome/content/rules/curve.co.uk.xml
Labels: new-ruleset

#18469 Remove duplicates *.pdu.edu, gone from DNS
  src/chrome/content/rules/Portland_State_University-falsemixed.xml
  src/chrome/content/rules/Portland_State_University.xml
Labels: ruleset-enhancement, top-100k

#18472 Remove duplicates *.aweber.com
  src/chrome/content/rules/AWeber-Communications.xml
  src/chrome/content/rules/AWeber-static.com.xml
  src/chrome/content/rules/AWeber.com.xml
  src/chrome/content/rules/AWeber.xml
Labels: ruleset-enhancement, top-10k

#18478 Create emailarchivestaskforce.org.xml
  src/chrome/content/rules/emailarchivestaskforce.org.xml
Labels: new-ruleset

#18477 Add jabref.org
  src/chrome/content/rules/JabRef.org.xml
Labels: new-ruleset, top-1m

#18476 Create pspx.ru.xml
  src/chrome/content/rules/pspx.ru.xml
Labels: new-ruleset, top-1m

#18475 Remove duplicates www.uaa.alaska.edu
  src/chrome/content/rules/Alaska.edu.xml
  src/chrome/content/rules/University-of-Alaska-Anchorage.xml
  src/chrome/content/rules/University-of-Alaska.xml
Labels: ruleset-enhancement, top-100k

#17639 [PusherApp.com] Simplify ruleset
  src/chrome/content/rules/Pusher.com.xml
  src/chrome/content/rules/PusherApp.com.xml
Labels: ruleset-enhancement, top-100k

#15933 Create ruleset: Tub.ee
  src/chrome/content/rules/Tub.ee.xml
Labels: failing tests, new-ruleset

#14281 [SFGate.com] new ruleset
  src/chrome/content/rules/SFGate.com.xml
Labels: new-ruleset, top-10k

#16455 Create ruleset: Factiva.com
  src/chrome/content/rules/Factiva.com.xml
Labels: new-ruleset, top-100k

#16325 [carsales.com.au] New ruleset
  src/chrome/content/rules/carsales.com.au.xml
Labels: new-ruleset, top-10k

#15782 Update ruleset: Scene7
  src/chrome/content/rules/Scene7.xml
Labels: failing tests, ruleset-enhancement, top-10k

#17173 Add Listings360.bf.xml
  src/chrome/content/rules/Listings360.xml
Labels: new-ruleset

#17821 Add ruleset for etransfer.com
  src/chrome/content/rules/etransfer.com.xml
Labels: new-ruleset, top-1m

#18470 Add ruleset for stepmaniax.com
  src/chrome/content/rules/Stepmaniax.com.xml
Labels: new-ruleset

#18021 [MicrosoftStudios.com] Reactivate and rename ruleset
  src/chrome/content/rules/Microsoft.xml
  src/chrome/content/rules/MicrosoftStudios.com.xml
  src/chrome/content/rules/Microsoft_Studios.com.xml
Labels: ruleset-enhancement, top-100

#15880 Update NetBeans.xml
  src/chrome/content/rules/Ksplice.xml
  src/chrome/content/rules/MySQL.xml
  src/chrome/content/rules/NetBeans.xml
  src/chrome/content/rules/Oracle-mismatches.xml
  src/chrome/content/rules/Oracle.xml
Labels: ruleset-enhancement, top-100k

#17706 Add Onlyoffice.com.xml
  src/chrome/content/rules/Onlyoffice.com.xml
  src/chrome/content/rules/Onlyoffice.org.xml
  utils/ruleset-whitelist.csv
Labels: new-ruleset, top-100k, top-1m

#16660 Add ruleset for coletivos.org
  src/chrome/content/rules/Coletivos.org.xml
Labels: failing tests, new-ruleset

#13367 Create nytimes3xbfgragh.onion.xml
  src/chrome/content/rules/graylady3jvrrxbe.onion.xml
  src/chrome/content/rules/nytimes3xbfgragh.onion.xml
  utils/ruleset-whitelist.csv
Labels: new-ruleset

#18410 Add rule for RustFest.eu
  src/chrome/content/rules/RustFest.eu.xml
Labels: new-ruleset

#18481 Create wikidot.com.xml
  src/chrome/content/rules/Wikidot.xml
  src/chrome/content/rules/wikidot.com.xml
Labels: new-ruleset, top-10k

#18471 Add ruleset for my-aime.net
  src/chrome/content/rules/My-Aime.net.xml
Labels: new-ruleset

#18483 Whitelist all .onion rulesets
  src/chrome/content/rules/Gannett-Company.xml
  src/chrome/content/rules/USA_Today.xml
  src/chrome/content/rules/usatodayw7vu5egc.onion.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-1k

#15495 [Roblox] Update subdomains
  src/chrome/content/rules/Roblox.xml
Labels: ruleset-enhancement, top-1k

#18484 Update Ritter.vg.xml
  src/chrome/content/rules/Ritter.vg.xml
Labels: ruleset-enhancement

#18485 Update CoinPayments.net.xml
  src/chrome/content/rules/CoinPayments.com.xml
  src/chrome/content/rules/CoinPayments.net.xml
Labels: ruleset-enhancement, top-10k

#18486 Update OpenSocietyFoundations.org.xml
  src/chrome/content/rules/OpenSocietyFoundations.org.xml
  src/chrome/content/rules/opensocietyfoundations.org.xml
Labels: ruleset-enhancement, top-1m

#17049 Use "Onion Service" instead of "Hidden Service"
  src/chrome/content/rules/FacebookCoreWWWi.onion.xml
  src/chrome/content/rules/Protonirockerxow.onion.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100k

#18487 Create fliphtml5.com.xml
  src/chrome/content/rules/fliphtml5.com.xml
Labels: new-ruleset, top-10k

#17847 Add Fio_banka.xml
  src/chrome/content/rules/Fio.bank.xml
  src/chrome/content/rules/Fio.cz.xml
  src/chrome/content/rules/Fio.hu.xml
  src/chrome/content/rules/Fio.pl.xml
  src/chrome/content/rules/Fio.sk.xml
Labels: new-ruleset, top-10k

#18479 Create informit.com.xml
  src/chrome/content/rules/InformIT.com.xml
  src/chrome/content/rules/InformIT.xml
  src/chrome/content/rules/Pearson.xml
Labels: new-ruleset, top-100k

#17525 Properly install `chromedriver` on Mac.
  install-dev-dependencies.sh
Labels: toolchain

#18452 Normlise disabled site hostname and migrate stored list, fix #18451
  chromium/background-scripts/background.js
  chromium/background-scripts/store.js
  chromium/background-scripts/util.js
Labels: bug

#14807 [OSGeo.org] Add targets and simplify ruleset
  src/chrome/content/rules/OSGeo.org.xml
Labels: failing tests, ruleset-enhancement, top-100k, top-1m

#18488 Create jeremyheminger.com.xml
  src/chrome/content/rules/jeremyheminger.com.xml
Labels: new-ruleset

#18490 Create yuzusushisanmateo.com.xml
  src/chrome/content/rules/yuzusushisanmateo.com.xml
Labels: new-ruleset

#18489 Create lorenzonuvoletta.com.xml
  src/chrome/content/rules/lorenzonuvoletta.com.xml
Labels: new-ruleset

#17763 Create funktionstjanster.se.xml
  src/chrome/content/rules/funktionstjanster.se.xml
Labels: new-ruleset

#18498 Create freeactionscript.com.xml
  src/chrome/content/rules/freeactionscript.com.xml
Labels: new-ruleset, top-1m

#18497 Create as3gamegears.com.xml
  src/chrome/content/rules/as3gamegears.com.xml
Labels: new-ruleset

#18496 Create grindheadgames.com.xml
  src/chrome/content/rules/grindheadgames.com.xml
Labels: new-ruleset

#18494 Create sdkboy.com.xml
  src/chrome/content/rules/sdkboy.com.xml
Labels: new-ruleset

#18492 Create internetua.com.xml
  src/chrome/content/rules/internetua.com.xml
Labels: new-ruleset, top-1m

#18499 Create rudimental.co.uk.xml
  src/chrome/content/rules/rudimental.co.uk.xml
Labels: new-ruleset

#18500 Create monolith.zone.xml
  src/chrome/content/rules/monolith.zone.xml
Labels: new-ruleset

#18504 Create radeon.ru.xml
  src/chrome/content/rules/radeon.ru.xml
Labels: new-ruleset, top-1m

#18506 Create emuvr.net.xml
  src/chrome/content/rules/emuvr.net.xml
Labels: new-ruleset

#18505 Create chronox.de.xml
  src/chrome/content/rules/chronox.de.xml
Labels: new-ruleset

#18502 Create lazyfoo.net.xml
  src/chrome/content/rules/lazyfoo.net.xml
Labels: new-ruleset

#18493 Update UNC.edu.xml
  src/chrome/content/rules/UNC.edu-mixedcontent.xml
  src/chrome/content/rules/UNC.edu.xml
Labels: ruleset-enhancement, top-10k

#18233 Remove NS_BINDING_ABORTED from list of errors triggering EASE error page (fixes XPI installation on Firefox)
  chromium/background-scripts/background.js
Labels: EASE, bug, firefox

#18501 Add Armorgames.com.xml
  src/chrome/content/rules/Armorgames.com.xml
Labels: new-ruleset, top-10k

#18509 Create sanghicement.com.xml
  src/chrome/content/rules/sanghicement.com.xml
Labels: new-ruleset, top-1m

#18510 Remove empty line at beginning of ruleset-whitelist.csv
  utils/ruleset-whitelist.csv
Labels: bug

#18511 Create transcriber.ru.xml
  src/chrome/content/rules/transcriber.ru.xml
Labels: new-ruleset

#18512 Update and rename ION-Audio.xml to IONAudio.com.xml
  src/chrome/content/rules/ION-Audio.xml
  src/chrome/content/rules/IONAudio.com.xml
Labels: ruleset-enhancement, top-1m

#18513 Update and rename Vispa.xml to Vispa.net.uk.xml
  src/chrome/content/rules/Vispa.net.uk.xml
  src/chrome/content/rules/Vispa.xml
Labels: ruleset-enhancement

#18514 Create nervomusic.com.xml
  src/chrome/content/rules/nervomusic.com.xml
Labels: new-ruleset

#18515 Update and rename PBwiki.xml to PBworks.com.xml
  src/chrome/content/rules/PBwiki.xml
  src/chrome/content/rules/PBworks.com.xml
Labels: ruleset-enhancement, top-10k

#18516 Create lleo.me.xml
  src/chrome/content/rules/lleo.me.xml
Labels: new-ruleset, top-1m

#18517 Create iddh.org.br.xml
  src/chrome/content/rules/iddh.org.br.xml
Labels: new-ruleset

#18518 Create asciimation.co.nz.xml
  src/chrome/content/rules/asciimation.co.nz.xml
Labels: new-ruleset

#18519 Create deborahrfowler.com.xml
  src/chrome/content/rules/deborahrfowler.com.xml
Labels: new-ruleset

#18549 Create all4joomla.com.xml
  src/chrome/content/rules/all4joomla.com.xml
Labels: new-ruleset

#18547 Create pwntools.com.xml
  src/chrome/content/rules/pwntools.com.xml
Labels: new-ruleset

#18545 Create hddguru.com.xml
  src/chrome/content/rules/hddguru.com.xml
Labels: new-ruleset, top-100k

#18543 Create sql-join.com.xml
  src/chrome/content/rules/sql-join.com.xml
Labels: new-ruleset

#18534 Create libmng.com.xml
  src/chrome/content/rules/libmng.com.xml
Labels: new-ruleset

#18537 Create splitsider.com.xml
  src/chrome/content/rules/splitsider.com.xml
Labels: new-ruleset

#18526 Create javaops.ru.xml
  src/chrome/content/rules/javaops.ru.xml
Labels: new-ruleset

#18527 Create portablepython.com.xml
  src/chrome/content/rules/portablepython.com.xml
Labels: new-ruleset

#18522 Create jklakshmicement.com.xml
  src/chrome/content/rules/jklakshmicement.com.xml
Labels: new-ruleset

#18525 Add partial ruleset for JKU.at
  src/chrome/content/rules/Jku.at.xml
Labels: new-ruleset, top-100k

#18523 Create intec.edu.za.xml
  src/chrome/content/rules/intec.edu.za.xml
Labels: new-ruleset

#18561 Create act.org.xml
  src/chrome/content/rules/act.org.xml
Labels: new-ruleset, top-10k

#18531 Rename and Update DuckCorp.xml
  src/chrome/content/rules/DuckCorp.xml
  src/chrome/content/rules/mini-dweeb.org.xml
Labels: ruleset-enhancement

#18532 Update Umea_University.xml
  src/chrome/content/rules/Umea_University.xml
Labels: ruleset-enhancement, top-100k

#18529 Create rustedlogic.net.xml
  src/chrome/content/rules/rustedlogic.net.xml
Labels: new-ruleset

#18540 Create nero.com.xml
  src/chrome/content/rules/Nero.xml
  src/chrome/content/rules/nero.com.xml
Labels: new-ruleset, top-100k

#18530 Update MediaMind.xml
  src/chrome/content/rules/MediaMind.xml
Labels: ruleset-enhancement, top-1m

#18548 Update Nicovideo.jp.xml
  src/chrome/content/rules/Nicovideo.jp.xml
Labels: ruleset-enhancement, top-1k

#18538 Create gamedev.ru.xml
  src/chrome/content/rules/gamedev.ru.xml
Labels: new-ruleset, top-1m

#18551 Create foundry.com.xml
  src/chrome/content/rules/foundry.com.xml
Labels: new-ruleset, top-1m

#18558 Create jomsocial.com.xml
  src/chrome/content/rules/jomsocial.com.xml
Labels: new-ruleset, top-100k

#18559 Create gpuinfo.org.xml
  src/chrome/content/rules/gpuinfo.org.xml
Labels: new-ruleset, top-1m

#18554 Create wisdomweb.ru.xml
  src/chrome/content/rules/wisdomweb.ru.xml
Labels: new-ruleset, top-1m

#18601 Temporarily downgrade LTS to Dubnium branch to fix node-webcrypto-ossl install error
  .travis.yml
Labels: bug, high priority, toolchain

#18566 Update theeca.com.xml, related #17965
  src/chrome/content/rules/Entertainment-Consumers-Association-mismatches.xml
  src/chrome/content/rules/Entertainment-Consumers-Association.xml
  src/chrome/content/rules/theeca.com.xml
Labels: ruleset-enhancement

#18533 Create worldofspectrum.org.xml
  src/chrome/content/rules/worldofspectrum.org.xml
Labels: new-ruleset

#18546 Create meraferesources.co.za.xml
  src/chrome/content/rules/meraferesources.co.za.xml
Labels: broken MCB, new-ruleset

#18562 Run npm audit fix --force
  chromium/package-lock.json
  chromium/package.json
Labels: enhancement

#18565 Ignore loopback and private network addresses (such as 192.168.0.1)
  chromium/background-scripts/background.js
  chromium/background-scripts/ip_utils.js
  chromium/manifest.json
  chromium/test/ip_utils_test.js
Labels: enhancement

#18632 Add Elixir-Lang.org.xml
  src/chrome/content/rules/Elixir-Lang.org.xml
Labels: new-ruleset, top-100k

#18630 Add Scrapy.org.xml
  src/chrome/content/rules/Scrapy.org.xml
Labels: new-ruleset, top-100k

#18631 Add CPAN.org.xml
  src/chrome/content/rules/CPAN.org.xml
Labels: new-ruleset, top-100k

#18627 Update Iki.fi.xml
  src/chrome/content/rules/Iki.fi.xml
Labels: ruleset-enhancement

#18556 Create ideal-collaboration.net.xml
  src/chrome/content/rules/ideal-collaboration.net.xml
Labels: new-ruleset

#18564 Create openmsx.org.xml
  src/chrome/content/rules/openmsx.org.xml
Labels: new-ruleset

#18583 Create ubuntutheaterproject.com.xml
  src/chrome/content/rules/ubuntutheaterproject.com.xml
Labels: new-ruleset

#18585 Create sotawiki.net.xml
  src/chrome/content/rules/sotawiki.net.xml
Labels: new-ruleset

#18586 Create linux-notes.org.xml
  src/chrome/content/rules/linux-notes.org.xml
Labels: new-ruleset, top-1m

#18592 Create mandrakewine.com.xml
  src/chrome/content/rules/mandrakewine.com.xml
Labels: new-ruleset

#18593 Create bgslinc.com.xml
  src/chrome/content/rules/bgslinc.com.xml
Labels: new-ruleset

#18620 Create polarcloud.com.xml
  src/chrome/content/rules/polarcloud.com.xml
Labels: new-ruleset

#18634 Add ZX2C4.com.xml
  src/chrome/content/rules/ZX2C4.com.xml
Labels: new-ruleset

#18624 Create ubuntupodcast.org.xml
  src/chrome/content/rules/ubuntupodcast.org.xml
Labels: new-ruleset

#18628 Add OpenCV.org.xml
  src/chrome/content/rules/OpenCV.org.xml
Labels: new-ruleset, top-100k

#18629 Add HTTrack.com.xml
  src/chrome/content/rules/HTTrack.com.xml
Labels: new-ruleset, top-100k

#18574 Create marketoracle.co.uk.xml
  src/chrome/content/rules/marketoracle.co.uk.xml
Labels: new-ruleset, top-1m

#18595 Create winehq.org.ru.xml
  src/chrome/content/rules/winehq.org.ru.xml
Labels: new-ruleset

#18588 Create tilda.cc.xml
  src/chrome/content/rules/tilda.cc.xml
Labels: new-ruleset, top-10k

#18597 Update TheStandNews.com.xml
  src/chrome/content/rules/TheStandNews.com.xml
Labels: ruleset-enhancement, top-10k

#18626 Update PortForward.com.xml
  src/chrome/content/rules/PortForward.com.xml
Labels: ruleset-enhancement, top-100k

#18555 Create globbersthemes.com.xml
  src/chrome/content/rules/globbersthemes.com.xml
Labels: new-ruleset, top-1m

#18573 Create autotravel.ru.xml
  src/chrome/content/rules/autotravel.ru.xml
Labels: new-ruleset, top-1m

#18572 Create bullzip.com.xml
  src/chrome/content/rules/bullzip.com.xml
Labels: new-ruleset, top-1m

#18582 Create flowersofindia.net.xml
  src/chrome/content/rules/flowersofindia.net.xml
Labels: new-ruleset, top-1m

#18587 Create aimp.ru.xml
  src/chrome/content/rules/aimp.ru.xml
Labels: new-ruleset, top-1m

#18625 Update Mentor-Graphics.xml
  src/chrome/content/rules/Mentor-Graphics.xml
  src/chrome/content/rules/Mentor.com.xml
Labels: ruleset-enhancement, top-1m

#18635 Add ZNC.in.xml
  src/chrome/content/rules/ZNC.in.xml
Labels: new-ruleset

#18641 Add LibGen.is.xml
  src/chrome/content/rules/LibGen.is.xml
Labels: new-ruleset, top-10k

#18644 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement, top-100k

#18643 Create ruleset for www.deutschesklimaportal.de
  src/chrome/content/rules/Deutsches_Klimaportal.xml
Labels: new-ruleset

#18640 Add Biologo.ru.xml
  src/chrome/content/rules/Biologo.ru.xml
Labels: new-ruleset, top-1m

#18569 Create connectingcredentials.org.xml
  src/chrome/content/rules/connectingcredentials.org.xml
Labels: new-ruleset

#18570 Create joanganzcooneycenter.org.xml
  src/chrome/content/rules/joanganzcooneycenter.org.xml
Labels: new-ruleset

#18578 Create hotelchantelle.com.xml
  src/chrome/content/rules/hotelchantelle.com.xml
Labels: new-ruleset

#18581 Create ghosthousecreative.com.xml
  src/chrome/content/rules/ghosthousecreative.com.xml
Labels: new-ruleset

#18568 Create earlychildhoodcolorado.org.xml
  src/chrome/content/rules/earlychildhoodcolorado.org.xml
Labels: new-ruleset

#18617 Create jacksonzoo.org.xml
  src/chrome/content/rules/jacksonzoo.org.xml
Labels: new-ruleset

#18577 Create oraclefox.com.xml
  src/chrome/content/rules/oraclefox.com.xml
Labels: new-ruleset
