Repository EFForg/https-everywhere, pull requests merged in 2020-09, with the labels that each got.

#19538 Hotfix: remove securecookie tag from Soundcloud.xml
  src/chrome/content/rules/Soundcloud.xml
Labels: high priority, ruleset-enhancement

#19426 Create rssowl.org.xml
  src/chrome/content/rules/rssowl.org.xml
Labels: new-ruleset

#19434 Create cbor.io.xml
  src/chrome/content/rules/cbor.io.xml
Labels: new-ruleset

#19435 Create tehsausage.com.xml
  src/chrome/content/rules/tehsausage.com.xml
Labels: new-ruleset

#19436 Create windows93.net.xml
  src/chrome/content/rules/windows93.net.xml
Labels: new-ruleset

#19422 Create voffka.com.xml
  src/chrome/content/rules/Voffka.xml
Labels: new-ruleset, top-1m

#19437 Create utf8everywhere.org.xml
  src/chrome/content/rules/utf8everywhere.org.xml
Labels: new-ruleset

#19539 Re-enabled and extended OSU
  src/chrome/content/rules/Oregon-State-University.xml
Labels: ruleset-enhancement

#19439 Create snipboard.io.xml
  src/chrome/content/rules/snipboard.io.xml
Labels: new-ruleset, top-100k

#19443 Create gkovacs.com.xml
  src/chrome/content/rules/gkovacs.com.xml
Labels: new-ruleset

#19442 Create thegeekblog.co.uk.xml
  src/chrome/content/rules/thegeekblog.co.uk.xml
Labels: new-ruleset

#19444 Create cpcwiki.eu.xml
  src/chrome/content/rules/cpcwiki.eu.xml
Labels: new-ruleset

#19447 Create hoehrmann.de.xml
  src/chrome/content/rules/hoehrmann.de.xml
Labels: new-ruleset

#19450 Create academ.info.xml
  src/chrome/content/rules/academ.info.xml
Labels: new-ruleset

#19453 Create fmu.br.xml
  src/chrome/content/rules/fmu.br.xml
Labels: new-ruleset

#19467 Update EncryptEverything.ca ruleset
  src/chrome/content/rules/EncryptEverything.ca.xml
  src/chrome/content/rules/Encrypt_Everything.ca.xml
Labels: ruleset-enhancement

#19469 Add TaxChopper.ca.xml
  src/chrome/content/rules/TaxChopper.ca.xml
Labels: new-ruleset

#19470 Add WSPRnet.org.xml
  src/chrome/content/rules/WSPRnet.org.xml
Labels: new-ruleset

#19471 Add Tigertronics.com.xml
  src/chrome/content/rules/Tigertronics.com.xml
Labels: new-ruleset

#19472 Add DaemonPage.com.xml
  src/chrome/content/rules/DaemonPage.com.xml
Labels: new-ruleset

#19473 Add dof.gob.mx.xml
  src/chrome/content/rules/dof.gob.mx.xml
Labels: new-ruleset, top-1m

#19475 Mixxx DJ - add downloads site
  src/chrome/content/rules/Mixxx.org.xml
Labels: ruleset-enhancement

#19486 Expand tu-darmstadt.de
  src/chrome/content/rules/TU-Darmstadt.de.xml
Labels: ruleset-enhancement

#19497 Update Apple.com.xml
  src/chrome/content/rules/Apple.com.xml
Labels: ruleset-enhancement

#19498 Update Intel.xml, remove complex rewrites
  src/chrome/content/rules/Intel.xml
Labels: ruleset-enhancement, top-1k

#19499 Update Indymedia.xml, remove obsolete comment
  src/chrome/content/rules/Indymedia.xml
Labels: ruleset-enhancement, top-100k

#19503 Update Mashery.com.xml
  src/chrome/content/rules/Mashery.com.xml
  src/chrome/content/rules/Mashery.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19504 Update Enjin.xml
  src/chrome/content/rules/Enjin.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19505 Update Get.it.xml
  src/chrome/content/rules/Get.It.xml
  src/chrome/content/rules/Get.it.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19506 Rename and update GetChute.com.xml
  src/chrome/content/rules/GetChute.com.xml
  src/chrome/content/rules/GetChute.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19507 Update BannerSnack.com.xml
  src/chrome/content/rules/BannerSnack.com.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-100k

#19508 Update Cloudera.com.xml
  src/chrome/content/rules/Cloudera.com.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-100k

#19523 Update EToro.xml related rulesets
  src/chrome/content/rules/EToro.xml
  src/chrome/content/rules/etoro.com-falsemixed.xml
  src/chrome/content/rules/etorostatic.com.xml
Labels: new-ruleset

#19525 Update Zimbra.com.xml
  src/chrome/content/rules/Zimbra.com.xml
  src/chrome/content/rules/Zimbra.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19526 Delete Jamendo.xml
  src/chrome/content/rules/Jamendo.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19527 Update sunlightfoundation.com.xml
  src/chrome/content/rules/Sunlight-Foundation.xml
  src/chrome/content/rules/SunlightFoundation.com.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19528 Update Sidearm_Sports.xml
  src/chrome/content/rules/Sidearm_Sports-problematic.xml
  src/chrome/content/rules/Sidearm_Sports.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19488 Remove S3 V1 References and Update to S3 V2 in AWS
  src/chrome/content/rules/AmazonAWS.com.xml
Labels: amazon-s3-2020

#19533 Rename and update Justia.xml
  src/chrome/content/rules/Justia.com.xml
  src/chrome/content/rules/Justia.xml
Labels: ruleset-enhancement

#19556 Update WikiFur.com rules
  src/chrome/content/rules/WikiFur.xml
Labels: ruleset-enhancement

#19545 Add StumblingOn.com.xml
  src/chrome/content/rules/StumblingOn.com.xml
Labels: new-ruleset

#19552 Delete Bucket_Explorer.com.xml
  src/chrome/content/rules/Bucket_Explorer.com.xml
Labels: amazon-s3-2020

#19553 Rename and Update Pixlr.com.xml
  src/chrome/content/rules/Pixlr.com.xml
  src/chrome/content/rules/Pixlr.xml
Labels: amazon-s3-2020

#19554 Update Jamendo.com.xml
  src/chrome/content/rules/Jamendo.com.xml
Labels: ruleset-enhancement

#19557 Update Squarespace.xml related rulesets
  src/chrome/content/rules/Squarespace-clients.xml
  src/chrome/content/rules/Squarespace.xml
  src/chrome/content/rules/ohnopodcast.com.xml
Labels: amazon-s3-2020

#19558 Update Ubisoft-Entertainment.xml
  src/chrome/content/rules/Ubisoft-Entertainment.xml
Labels: amazon-s3-2020

#19559 Update MotherJones.com.xml
  src/chrome/content/rules/MotherJones.com.xml
Labels: amazon-s3-2020

#19560 Rename and Update Cl.ly.xml related rulesets
  src/chrome/content/rules/Cl.ly.xml
  src/chrome/content/rules/Cld.me.xml
  src/chrome/content/rules/GetCloudApp.com.xml
  src/chrome/content/rules/Linerunner-mismatches.xml
  src/chrome/content/rules/Linerunner.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19561 Update and rename Edublogs.org.xml
  src/chrome/content/rules/EduBlogs.org.xml
  src/chrome/content/rules/Edublogs.xml
Labels: amazon-s3-2020

#19126 Create 5ch.xml
  src/chrome/content/rules/5ch.xml
Labels: new-ruleset, top-10k, top-1k

#19568 Feature: EASE Copy Url
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
  chromium/pages/cancel/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: EASE, ui

#19465 Crx to Edge Build
  edge.sh
  install-dev-dependencies.sh
  make.sh
Labels: ms-edge

#19574 Remove FreeCopyright.com.xml (no working targets)
  src/chrome/content/rules/MyFreeCopyright.com-problematic.xml
  src/chrome/content/rules/MyFreeCopyright.com.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19572 Add belaruswith.me.xml
  src/chrome/content/rules/belaruswith.me.xml
Labels: new-ruleset

#19573 Remove Docstoc.xml (no working targets)
  src/chrome/content/rules/Docstoc.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19445 Create wpitchoune.net.xml
  src/chrome/content/rules/wpitchoune.net.xml
Labels: new-ruleset

#19440 Create skrinshoter.ru.xml
  src/chrome/content/rules/skrinshoter.ru.xml
Labels: needs revision, new-ruleset, top-100k

#19585 Remove Captura-Group.xml (no working targets)
  src/chrome/content/rules/Captura-Group.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19579 Update and rename Woot.xml to Woot.com.xml
  src/chrome/content/rules/Woot.com.xml
  src/chrome/content/rules/Woot.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19596 Hotfix: CRX Edge Script
  edge.sh
Labels: bug

#19542 Re-enabled nagios2.osuosl.org (works)
  src/chrome/content/rules/osuosl.org.xml
Labels: ruleset-enhancement

#19543 Create fofa.so.xml
  src/chrome/content/rules/fofa.so.xml
Labels: new-ruleset

#19548 Add VE7SCC.org.xml
  src/chrome/content/rules/VE7SCC.org.xml
Labels: new-ruleset

#19550 Add VPNGate.net.xml
  src/chrome/content/rules/VPNGate.net.xml
Labels: new-ruleset

#19551 Add VyprVPN.com.xml
  src/chrome/content/rules/VyprVPN.com.xml
Labels: new-ruleset

#19555 Update Born_This_Way_Foundation.xml
  src/chrome/content/rules/Born_This_Way_Foundation.xml
Labels: ruleset-enhancement

#19564 Add CodiMD.org.xml
  src/chrome/content/rules/CodiMD.org.xml
Labels: new-ruleset

#19565 Add weeklyosm.eu
  src/chrome/content/rules/Weeklyosm.eu.xml
Labels: new-ruleset

#19524 Update MediaFire.com.xml
  src/chrome/content/rules/MediaFire.com.xml
Labels: ruleset-enhancement

#19603 Add a ruleset for strasbourgfestival.com
  src/chrome/content/rules/strasbourgfestival.com.xml
Labels: new-ruleset

#19549 Update and add more ust.hk (HKUST) related rulesets
  src/chrome/content/rules/HKUST.edu.cn.xml
  src/chrome/content/rules/HKUST.edu.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: new-ruleset, ruleset-enhancement

#19580 Remove Quizsnack.com.xml (no working targets)
  src/chrome/content/rules/Quizsnack.com.xml
  src/chrome/content/rules/SnackTools.com.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19581 Update RPXNow.com.xml
  src/chrome/content/rules/RPXNow.com.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19583 Update and rename KIXEYE.xml to KIXEYE.com.xml
  src/chrome/content/rules/KIXEYE.com.xml
  src/chrome/content/rules/KIXEYE.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19584 Update GEBlogs.com.xml
  src/chrome/content/rules/GEBlogs.com.xml
Labels: amazon-s3-2020, ruleset-enhancement

#19617 Remove S3 Refernces to Issu Aps Ruleset
  src/chrome/content/rules/Issuu_Aps.xml
Labels: amazon-s3-2020

#19618 Remove S3 Refernces to FeedBlitz
  src/chrome/content/rules/FeedBlitz.xml
Labels: amazon-s3-2020

#19619 Remove Filemobile
  src/chrome/content/rules/Filemobile.xml
Labels: amazon-s3-2020

#19620 Remove Conpemium
  src/chrome/content/rules/Compendium.xml
Labels: amazon-s3-2020

#19622 Remove S3 Reference from SMF for Free
  src/chrome/content/rules/SMF_for_Free.xml
Labels: amazon-s3-2020

#19625 Update JanRain.xml related rulesets
  src/chrome/content/rules/JanRain.xml
  src/chrome/content/rules/JanRainCapture.com.xml
Labels: amazon-s3-2020

#19621 Remove Smowtion
  src/chrome/content/rules/Smowtion.xml
Labels: amazon-s3-2020

#19626 Remove S3 References from Scribd
  src/chrome/content/rules/Scribd.com.xml
Labels: amazon-s3-2020

#19627 Delete Wishabi.xml and Update Circular_Hub.xml
  src/chrome/content/rules/Circular_Hub.xml
  src/chrome/content/rules/Wishabi.xml
Labels: amazon-s3-2020

#19629 Delete SBNdev.net.xml
  src/chrome/content/rules/SBNdev.net.xml
Labels: amazon-s3-2020

#19631 Update PR-Newswire.xml
  src/chrome/content/rules/PR-Newswire.xml
Labels: amazon-s3-2020

#19630 Update IPR_Software.com.xml
  src/chrome/content/rules/IPR_Software.com.xml
Labels: amazon-s3-2020

#19628 Update and rename Roster-Teeth.xml to RoosterTeeth.com.xml
  src/chrome/content/rules/RoosterTeeth.com.xml
  src/chrome/content/rules/Roster-Teeth.xml
Labels: amazon-s3-2020

#19624 Update Blogtrottr.com.xml
  src/chrome/content/rules/Blogtrottr.com.xml
Labels: ruleset-enhancement
