Repository EFForg/https-everywhere, pull requests merged in 2020-06, with the labels that each got.

#19319 Add Rowetel.com.xml
  src/chrome/content/rules/Rowetel.com.xml
Labels: new-ruleset

#19292 Revert #19029 and #18760
  chromium/background-scripts/background.js
  chromium/pages/popup/ux.js
Labels: enhancement

#19325 Update Freshdesk.com.xml
  src/chrome/content/rules/Freshdesk.com.xml
  src/chrome/content/rules/Freshdesk.xml
Labels: ruleset-enhancement

#19324 Update NewsBlur.com.xml
  src/chrome/content/rules/NewsBlur.com.xml
Labels: ruleset-enhancement

#19323 Update InvestingChannel.com.xml
  src/chrome/content/rules/Investing-Channel.xml
  src/chrome/content/rules/InvestingChannel.com.xml
Labels: ruleset-enhancement

#19322 Update newsela.com.xml
  src/chrome/content/rules/newsela.com.xml
Labels: ruleset-enhancement

#19321 Update WhippleHill.com.xml
  src/chrome/content/rules/WhippleHill.com.xml
  src/chrome/content/rules/WhippleHill.xml
Labels: ruleset-enhancement

#19320 Update Typotheque.xml
  src/chrome/content/rules/Typotheque.xml
Labels: ruleset-enhancement

#19342 Add download.asrock.com
  src/chrome/content/rules/Asrock.com.xml
Labels: ruleset-enhancement

#19340 Create CDJapan.xml
  src/chrome/content/rules/CDJapan.xml
Labels: new-ruleset

#19317 Add k2b-bulk.ebay.de, fix ebay.de ruleset
  src/chrome/content/rules/ebay.de.xml
Labels: ruleset-enhancement

#19343 Update MeiTuan.com.xml
  src/chrome/content/rules/MeiTuan.com.xml
Labels: ruleset-enhancement

#19338 Create IPAC.global.xml
  src/chrome/content/rules/IPAC.global.xml
Labels: new-ruleset

#19348 Create Openid.org.cn.xml
  src/chrome/content/rules/Openid.org.cn.xml
Labels: new-ruleset

#19362 Remove Yuku.xml
  src/chrome/content/rules/Yuku.xml
Labels: ruleset-enhancement

#19361 Remove Ezaxess.com.xml
  src/chrome/content/rules/Ezaxess.com.xml
Labels: ruleset-enhancement

#19359 Remove Youmix.xml
  src/chrome/content/rules/Youmix.xml
Labels: ruleset-enhancement

#19357 Remove CEtrk.com.xml
  src/chrome/content/rules/CEtrk.com.xml
  src/chrome/content/rules/Crazy-Egg.xml
Labels: ruleset-enhancement

#19356 Remove UniversalSubtitles.xml
  src/chrome/content/rules/UniversalSubtitles.xml
Labels: ruleset-enhancement

#19354 Remove InfNX.xml
  src/chrome/content/rules/InfNX.xml
Labels: ruleset-enhancement

#19352 Update IMshopping.com.xml
  src/chrome/content/rules/IMshopping.com.xml
Labels: ruleset-enhancement

#19360 Update MICGadget.com ruleset
  src/chrome/content/rules/MIC-Gadget.xml
  src/chrome/content/rules/MICGadget.com.xml
Labels: ruleset-enhancement

#19353 Remove Pivotal_Labs.xml
  src/chrome/content/rules/Pivotal_Labs.xml
Labels: ruleset-enhancement

#19349 Add PhotoPea.com.xml
  src/chrome/content/rules/PhotoPea.com.xml
Labels: new-ruleset

#19364 Remove Lanyrd.xml
  src/chrome/content/rules/Lanyrd.xml
Labels: ruleset-enhancement

#19363 Remove Scripting-News.xml
  src/chrome/content/rules/Scripting-News.xml
Labels: ruleset-enhancement

#19350 Remove Minalyzer.com.xml and Chambal.xml
  src/chrome/content/rules/Chambal.xml
  src/chrome/content/rules/Minalyzer.com.xml
Labels: ruleset-enhancement

#19365 Add counsel.ust.hk
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement

#19358 Update DealerTrend.com.xml
  src/chrome/content/rules/DealerTrend.com.xml
Labels: ruleset-enhancement

#19355 Create silego.com ruleset
  src/chrome/content/rules/silego.com.xml
Labels: new-ruleset

#19367 Mimetype rulesets change for Opera
  .gitignore
  test/validations/filename/run.py
  test/validations/special/run.py
  utils/merge-rulesets.py
Labels: opera

#19375 Hotfix firefox preview ux
  chromium/pages/popup/style.css
Labels: firefox, ui

#19376 Add DartSearch.net.xml
  src/chrome/content/rules/DartSearch.net.xml
  src/chrome/content/rules/GoogleServices.xml
Labels: new-ruleset

#19371 Cykloserver.cz
  src/chrome/content/rules/Cykloserver.cz.xml
Labels: new-ruleset

#19135 Rewrite Alexa Labeller
  utils/labeller/Dockerfile
  utils/labeller/index.js
  utils/labeller/package-lock.json
  utils/labeller/package.json
  utils/labeller/process.js
  utils/labeller/test.js
Labels: toolchain

#19378 Photography
  src/chrome/content/rules/43rumors.com.xml
  src/chrome/content/rules/Canonwatch.com.xml
  src/chrome/content/rules/Fujirumors.com.xml
  src/chrome/content/rules/L-rumors.com.xml
  src/chrome/content/rules/Nikonrumors.com.xml
  src/chrome/content/rules/Opticallimits.com.xml
  src/chrome/content/rules/Petapixel.com.xml
  src/chrome/content/rules/Photographylife.com.xml
  src/chrome/content/rules/Sonyalpha.blog.xml
  src/chrome/content/rules/Sonyalpharumors.com.xml
Labels: new-ruleset, top-100k

#19377 ZSR.sk
  src/chrome/content/rules/ZSR.sk.xml
Labels: new-ruleset
