Repository EFForg/https-everywhere, pull requests merged in 2020-01, with the labels that each got.

#18774 Update yousuu.com.xml
  src/chrome/content/rules/yousuu.com.xml
Labels: china, ruleset-enhancement

#18757 Add AmamiyaSora.jp.xml
  src/chrome/content/rules/AmamiyaSora.jp.xml
Labels: new-ruleset

#18778 Add YogaDNS.com.xml
  src/chrome/content/rules/YogaDNS.com.xml
Labels: new-ruleset

#18752 Add tmp.ninja.xml
  src/chrome/content/rules/tmp.ninja.xml
Labels: new-ruleset

#18755 Fix parseIP call
  chromium/background-scripts/background.js
Labels: bug

#18763 Use the latest node LTS builds for unittests
  .travis.yml
  chromium/package-lock.json
  chromium/package.json
Labels: dependencies, enhancement

#18794 Rename The_FADER.com.xml to TheFader.com.xml and add more targets
  src/chrome/content/rules/TheFader.com.xml
  src/chrome/content/rules/The_FADER.com.xml
Labels: new-ruleset, top-100k

#18789 Add SSLEnforcer.com.xml
  src/chrome/content/rules/SSLEnforcer.com.xml
Labels: new-ruleset

#18788 Add Proxifier.com.xml
  src/chrome/content/rules/Proxifier.com.xml
Labels: new-ruleset, top-1m

#18795 Add targets to LightningMaps.org.xml
  src/chrome/content/rules/LightningMaps.org.xml
Labels: ruleset-enhancement, top-100k

#18793 Add HDME.eu.xml
  src/chrome/content/rules/HDME.eu.xml
Labels: new-ruleset, top-1m

#18792 Add QuickSilverMail.net.xml
  src/chrome/content/rules/QuickSilverMail.net.xml
Labels: new-ruleset

#18790 Add AOMedia.org.xml
  src/chrome/content/rules/AOMedia.org.xml
Labels: new-ruleset

#18768 Re-activate and Update Payoneer.com.xml
  src/chrome/content/rules/Payoneer.com.xml
Labels: ruleset-enhancement, top-10k

#18765 Split and Update HangSengBank.xml
  src/chrome/content/rules/HSI.com.hk.xml
  src/chrome/content/rules/HangSeng.com.cn.xml
  src/chrome/content/rules/HangSengBank.xml
Labels: ruleset-enhancement, top-10k

#18764 Update hsbc.com.hk.xml
  src/chrome/content/rules/hsbc.com.hk.xml
Labels: ruleset-enhancement, top-10k

#18798 Aktuality.sk
  src/chrome/content/rules/Azet.sk.xml
Labels: ruleset-enhancement, top-10k

#18761 Re-activate and Update iStockphoto.com.xml
  src/chrome/content/rules/iStockphoto.com.xml
  src/chrome/content/rules/istockphoto.com.xml
Labels: ruleset-enhancement, top-1k

#18770 Re-activate and Update TwitCasting.tv.xml
  src/chrome/content/rules/TwitCasting.tv.xml
  src/chrome/content/rules/TwitCasting.xml
Labels: ruleset-enhancement, top-10k

#18776 Re-activate and Update WeHeartIt.com.xml
  src/chrome/content/rules/WHI_CDN.com.xml
  src/chrome/content/rules/WHIcdn.com.xml
  src/chrome/content/rules/We-Heart-It.xml
  src/chrome/content/rules/WeHeartIt.com.xml
Labels: ruleset-enhancement, top-10k

#18802 electrospaces.net
  src/chrome/content/rules/Electrospaces.net.xml
Labels: new-ruleset

#18723 Create carnegiehub.org.xml
  src/chrome/content/rules/carnegiehub.org.xml
Labels: new-ruleset

#18806 Update FireEye.xml
  src/chrome/content/rules/FireEye.xml
Labels: ruleset-enhancement, top-100k

#18734 Update rsdn.org rule.
  src/chrome/content/rules/rsdn.org.xml
Labels: new-ruleset, top-1m

#18760 Fix bug causes MCB issues in EASE mode for some disabled sites
  chromium/background-scripts/background.js
Labels: EASE, bug

#18619 Allow users to whitelist hosts from the option page
  chromium/background-scripts/background.js
  chromium/background-scripts/rules.js
  chromium/background-scripts/util.js
  chromium/pages/options/index.html
  chromium/pages/options/style.css
  chromium/pages/options/ux.js
  chromium/test/rules_test.js
  chromium/test/util_test.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: enhancement

#18811 Add GameTechWiki.com.xml
  src/chrome/content/rules/GameTechWiki.com.xml
Labels: new-ruleset, top-1m

#18810 add whoisds
  src/chrome/content/rules/whoisds.xml
Labels: new-ruleset, top-100k, top-1m

#18816 Add AwkwardZombie.com.xml
  src/chrome/content/rules/AwkwardZombie.com.xml
Labels: new-ruleset, top-1m

#18804 Add Patches-Scrolls.com.xml
  src/chrome/content/rules/Patches-Scrolls.com.xml
Labels: new-ruleset, top-1m

#18805 Add Patches-Scrolls.de.xml
  src/chrome/content/rules/Patches-Scrolls.de.xml
Labels: new-ruleset

#18809 Add targets to Njal.la.xml
  src/chrome/content/rules/Njal.la.xml
Labels: ruleset-enhancement, top-1m

#18808 Add SourceRuns.org.xml
  src/chrome/content/rules/SourceRuns.org.xml
Labels: new-ruleset, top-1m

#18818 Add gitlab subdomain to FreeDesktop.org ruleset
  src/chrome/content/rules/FreeDesktop.xml
Labels: ruleset-enhancement, top-1m

#18819 [Mesa3d.org] add ruleset to always load via https
  src/chrome/content/rules/Mesa3d.org.xml
Labels: new-ruleset, top-1m

#18821 Chore: Remove en-US from link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs, enhancement

#18823 prosody.im is fixed
  src/chrome/content/rules/Prosody.im.xml
Labels: ruleset-enhancement

#18825 fix XMPP.net
  src/chrome/content/rules/XMPP.net.xml
Labels: ruleset-enhancement
