Repository EFForg/https-everywhere, pull requests merged in 2020-07, with the labels that each got.

#19374 Create tenhou.net
  src/chrome/content/rules/Tenhou.net.xml
Labels: new-ruleset, top-100k

#19139 Revert "[Fasthosts] Add coverage"
  src/chrome/content/rules/Fasthosts.xml
Labels: ruleset-bug, ruleset-enhancement

#19380 Add PythonTutor.ru.xml
  src/chrome/content/rules/PythonTutor.ru.xml
Labels: new-ruleset

#19383 NPM Updates
  chromium/package-lock.json
  chromium/package.json
  utils/trivialize-cdn-rules/package-lock.json
Labels: dependencies

#19381 Photography2
  src/chrome/content/rules/Cambridgeincolour.com.xml
  src/chrome/content/rules/Cameralabs.com.xml
  src/chrome/content/rules/Clarkvision.com.xml
  src/chrome/content/rules/Dustinabbott.net.xml
  src/chrome/content/rules/Ephotozine.com.xml
  src/chrome/content/rules/Imaging-resource.com.xml
  src/chrome/content/rules/The-digital-picture.com.xml
Labels: new-ruleset

#19406 HOTFIX: Statically write versions for Chromedriver
  test/setup_travis.sh
Labels: dependencies

#19401 Add rule for mkwrs.com
  src/chrome/content/rules/mkwrs.com.xml
Labels: new-ruleset

#19404 Admiringlight.com
  src/chrome/content/rules/Admiringlight.com.xml
Labels: new-ruleset

#19408 Update Torrentleech.org.xml
  src/chrome/content/rules/Torrentleech.org.xml
Labels: ruleset-enhancement

#19411 Invalid hosts colocation america
  src/chrome/content/rules/Colocation_America.com.xml
Labels: ruleset-enhancement

#19412 Too many redirects dmlp
  src/chrome/content/rules/DMLP.org.xml
Labels: ruleset-enhancement

#19405 Update HTTPS Everywhere Documentation
  CONTRIBUTING.md
  README.md
Labels: docs
