Repository EFForg/https-everywhere, pull requests merged in 2020-04, with the labels that each got.

#19071 Create abendblatt.de ruleset
  src/chrome/content/rules/Abendblatt.de.xml
Labels: new-ruleset

#19146 Unused rule e junkie
  src/chrome/content/rules/E-junkie.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#18706 Create nix.ru.xml
  src/chrome/content/rules/nix.ru.xml
Labels: new-ruleset, top-100k

#18990 Update Ars Technica related rulesets
  src/chrome/content/rules/Ars-Technica.xml
  src/chrome/content/rules/ArsTechnica.co.uk.xml
  src/chrome/content/rules/ArsTechnica.com.xml
  src/chrome/content/rules/ArsTechnica.net.xml
  src/chrome/content/rules/Conde-Nast-mismatches.xml
  src/chrome/content/rules/Conde-Nast.xml
  src/chrome/content/rules/Vanity-Fair.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#19050 Create technical-service.net ruleset
  src/chrome/content/rules/technical-service.net.xml
Labels: new-ruleset

#19074 Update 163.com.xml and Update 163.com-mixedcontent.xml
  src/chrome/content/rules/163.com-mixedcontent.xml
  src/chrome/content/rules/163.com.xml
Labels: china, ruleset-enhancement

#19078 Update 126.net.xml
  src/chrome/content/rules/126.net.xml
Labels: china, ruleset-enhancement

#19081 Update wiwo.de ruleset
  src/chrome/content/rules/WiWo.de.xml
Labels: ruleset-enhancement, top-100k

#19084 Add Devast.io.xml
  src/chrome/content/rules/Devast.io.xml
Labels: new-ruleset, top-1m

#19088 Create digidip.net ruleset
  src/chrome/content/rules/digidip.net.xml
Labels: new-ruleset, top-100k

#19106 Create sport.de ruleset
  src/chrome/content/rules/sport.de.xml
Labels: new-ruleset

#19108 Delete rules for my (old) domain.
  src/chrome/content/rules/Flameeyes.xml
Labels: owner, ruleset-enhancement

#19111 Create static-fra.de ruleset
  src/chrome/content/rules/static-fra.de.xml
Labels: new-ruleset

#19113 Update Bloomberg.xml
  src/chrome/content/rules/Bloomberg.xml
Labels: ruleset-enhancement

#19117 Update Bitly.xml
  src/chrome/content/rules/Bitly.xml
Labels: ruleset-enhancement, top-10k

#19115 Create HindustanTimes.com.xml
  src/chrome/content/rules/HindustanTimes.com.xml
Labels: new-ruleset, top-1k

#19105 Create watchcurbyourenthusiasm.com.xml
  src/chrome/content/rules/watchcurbyourenthusiasm.com.xml
Labels: new-ruleset

#19086 Create lfeeder.com ruleset
  src/chrome/content/rules/lfeeder.com.xml
Labels: new-ruleset

#19112 Update sport1.de ruleset
  src/chrome/content/rules/Sport1.de.xml
Labels: ruleset-enhancement

#19128 Create JREast.co.jp.xml
  src/chrome/content/rules/JREast.co.jp.xml
Labels: new-ruleset

#19122 Add NCStateFair.org.xml
  src/chrome/content/rules/NCStateFair.org.xml
Labels: new-ruleset

#19123 Create ktxtr.com ruleset
  src/chrome/content/rules/ktxtr.com.xml
Labels: new-ruleset

#19025 Use native bytes value as the default sort order
  utils/ruleset-whitelist-cleanup.sh
Labels: toolchain

#19145 Unused rule nijyuyon bimuunzu
  src/chrome/content/rules/Nijyuyon-Bimuunzu.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-10k

#19099 Create yourcmc.ru.xml
  src/chrome/content/rules/yourcmc.ru.xml
Labels: needs revision, new-ruleset

#18987 https_everywhere_checker syntax fixes
  test/rules/src/https_everywhere_checker/check_rules.py
  test/rules/src/https_everywhere_checker/rules.py
Labels: code-style, ruleset-testing, toolchain

#19141 Unused rule MyComputer
  src/chrome/content/rules/MyComputer.com.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#19147 E-rewards.com.xml: Add base domain used in rule
  src/chrome/content/rules/E-rewards.com.xml
Labels: ruleset-enhancement

#19148 Exhale.xml: Fixes and enhancements
  src/chrome/content/rules/Exhale.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#19164 Add targets to MacPorts.org.xml
  src/chrome/content/rules/MacPorts.org.xml
Labels: new-ruleset

#19154 Update Ubuntu.xml
  src/chrome/content/rules/Ubuntu-CN.xml
  src/chrome/content/rules/Ubuntu.com.cn.xml
  src/chrome/content/rules/Ubuntu.org.cn.xml
  src/chrome/content/rules/Ubuntu.xml
Labels: china, ruleset-enhancement, top-10k

#19189 HOTFIX: Chromedriver Failing Fix for Travis
  test/setup_travis.sh
Labels: bug, high priority

#19125 Exclude localhost subdomains from EASE redirection
  chromium/background-scripts/background.js
Labels: EASE, enhancement

#19181 Add Panli.com.xml
  src/chrome/content/rules/Panli.com.xml
Labels: china, new-ruleset

#19185 Add BSD.lv.xml
  src/chrome/content/rules/BSD.lv.xml
Labels: new-ruleset

#19183 Add SQLiteBrowser.org.xml
  src/chrome/content/rules/SQLiteBrowser.org.xml
Labels: new-ruleset

#19184 Add GeekGhost.net.xml
  src/chrome/content/rules/GeekGhost.net.xml
Labels: new-ruleset

#19167 Add Catch22.net.xml
  src/chrome/content/rules/Catch22.net.xml
Labels: new-ruleset

#19170 Add ExoticVM.com.xml
  src/chrome/content/rules/ExoticVM.com.xml
Labels: new-ruleset

#19171 Add WebOas.is.xml
  src/chrome/content/rules/WebOas.is.xml
Labels: new-ruleset

#19172 Add cheat.sh.xml
  src/chrome/content/rules/cheat.sh.xml
Labels: new-ruleset

#19173 Add explainshell.com.xml
  src/chrome/content/rules/explainshell.com.xml
Labels: new-ruleset

#19179 Create islandhealth.ca.xml
  src/chrome/content/rules/islandhealth.ca.xml
Labels: new-ruleset

#19187 Add Gwern.net.xml
  src/chrome/content/rules/Gwern.net.xml
Labels: new-ruleset

#19119 Add wiki.vg.xml
  src/chrome/content/rules/wiki.vg.xml
Labels: new-ruleset, top-1m

#19121 Add DeathGenerator.com.xml
  src/chrome/content/rules/DeathGenerator.com.xml
Labels: new-ruleset

#19134 Update LIHKG.com.xml
  src/chrome/content/rules/LIHKG.com.xml
Labels: ruleset-enhancement, top-10k

#19133 Add Bepo.fr.xml
  src/chrome/content/rules/Bepo.fr.xml
Labels: new-ruleset

#19159 Add FrontEndChecklist.io.xml
  src/chrome/content/rules/FrontEndChecklist.io.xml
Labels: new-ruleset

#19153 Telekom.sk.xml: Add missing host mail.telecom.sk
  src/chrome/content/rules/Telekom.sk.xml
Labels: ruleset-enhancement

#19155 Add restic.net.xml
  src/chrome/content/rules/restic.net.xml
Labels: new-ruleset

#19157 Add Starship.rs.xml
  src/chrome/content/rules/Starship.rs.xml
Labels: new-ruleset

#19156 Add Sass-lang.com.xml
  src/chrome/content/rules/Sass-lang.com.xml
Labels: new-ruleset, top-100k

#19129 Rename and update Alluremedia.com.xml
  src/chrome/content/rules/Alluremedia.com.xml
  src/chrome/content/rules/Alluremedia.xml
Labels: ruleset-enhancement

#19158 Add Shadowfacts.net.xml
  src/chrome/content/rules/Shadowfacts.net.xml
Labels: new-ruleset

#19152 Unused rule svenskaspel
  src/chrome/content/rules/Svenskaspel.se.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-1m

#19150 Unused rule millennium seating
  src/chrome/content/rules/Millennium_Seating.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#19142 Unused rule Eurexchange
  src/chrome/content/rules/Eurexchange.com.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#19137 Invalid hosts kuruc
  src/chrome/content/rules/Kuruc.info.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-1m

#19144 Unused rule Girl Scouts
  src/chrome/content/rules/Girl_Scouts.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-1m

#19149 Unused rule so furry
  src/chrome/content/rules/SoFurry.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100k

#19140 Fix regex syntax VitalWerks
  src/chrome/content/rules/Vitalwerks.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100k

#19131 Add PageAbode.com.xml
  src/chrome/content/rules/PageAbode.com.xml
Labels: new-ruleset

#19151 Add rclone.org.xml
  src/chrome/content/rules/rclone.org.xml
Labels: new-ruleset

#19136 Test data mismatch indymedia
  src/chrome/content/rules/Indymedia.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement, top-100k

#19130 Rename and update NewspaperDirect-mismatches.xml
  src/chrome/content/rules/NewspaperDirect-mismatches.xml
  src/chrome/content/rules/NewspaperDirect.xml
  src/chrome/content/rules/PressDisplay.com.xml
Labels: ruleset-enhancement, top-1m

#19176 Create mastodon.cloud ruleset
  src/chrome/content/rules/Mastodon.cloud.xml
Labels: new-ruleset

#19197 Add target to cdninstagram.com ruleset
  src/chrome/content/rules/CDN_Instagram.com.xml
Labels: new-ruleset

#19201 Add BGPView.io.xml
  src/chrome/content/rules/BGPView.io.xml
Labels: new-ruleset

#19200 Add RedditSearch.io.xml
  src/chrome/content/rules/RedditSearch.io.xml
Labels: new-ruleset

#19199 Add LearnXInYMinutes.com.xml
  src/chrome/content/rules/LearnXInYMinutes.com.xml
Labels: new-ruleset

#19198 Update Erlang.org.xml
  src/chrome/content/rules/Erlang.org.xml
Labels: ruleset-enhancement

#19193 Update file and contents for DogsbodyTechnology
  src/chrome/content/rules/DogsbodyTechnologyLtd.xml
  src/chrome/content/rules/Dogsbodytechnology.com.xml
Labels: owner, ruleset-enhancement

#19203 Add TetherReport.com.xml
  src/chrome/content/rules/TetherReport.com.xml
Labels: new-ruleset

#19169 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement

#19205 Add Frankfurtkanu.de.xml
  src/chrome/content/rules/Frankfurtkanu.de.xml
Labels: new-ruleset

#19120 Add Neil.brown.name.xml
  src/chrome/content/rules/Neil.brown.name.xml
Labels: new-ruleset

#19202 Add GloDLS.to.xml
  src/chrome/content/rules/GloDLS.to.xml
Labels: new-ruleset

#19138 Delete ubertags
  src/chrome/content/rules/UberTags-mismatches.xml
  src/chrome/content/rules/UberTags.xml
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#19196 Create JoinPeerTube.org.xml
  src/chrome/content/rules/JoinPeerTube.org.xml
Labels: new-ruleset

#19175 Updated chromedriver path to ensure correct symlink creation
  install-dev-dependencies.sh
Labels: dependencies
