Repository EFForg/https-everywhere, pull requests merged in 2020-05, with the labels that each got.

#19243 Add tinyimg.io.xml
  src/chrome/content/rules/tinyimg.io.xml
Labels: new-ruleset

#19223 Create Beeimg.com.xml (closes #19221)
  src/chrome/content/rules/Beeimg.com.xml
Labels: new-ruleset

#19161 Update Sinaimg.cn.xml
  src/chrome/content/rules/Sinaimg.cn.xml
Labels: china, ruleset-enhancement, top-100

#19162 Update Sina.cn.xml
  src/chrome/content/rules/Sina.cn-mixedcontent.xml
  src/chrome/content/rules/Sina.cn.xml
Labels: china, ruleset-enhancement, top-100

#19166 Update Sina.com.cn.xml
  src/chrome/content/rules/Sina.com.cn-mixedcontent.xml
  src/chrome/content/rules/Sina.com.cn.xml
Labels: china, ruleset-enhancement, top-100

#19194 Update 126.net.xml
  src/chrome/content/rules/126.net.xml
Labels: china, ruleset-enhancement

#19228 Delete Quora.xml
  src/chrome/content/rules/Quora.xml
Labels: ruleset-enhancement

#19218 Delete Peer1.ca.xml, all hosts gone from DNS
  src/chrome/content/rules/Peer1.ca.xml
Labels: ruleset-enhancement

#19260 Delete MiniMundos_online.com.xml, gone from DNS
  src/chrome/content/rules/Axeso5.com-falsemixed.xml
  src/chrome/content/rules/Axeso5.com.xml
  src/chrome/content/rules/MiniMundos_online.com.xml
Labels: ruleset-enhancement

#19258 Remove wildcard target from Spreadshirt related rulesets
  src/chrome/content/rules/Spreadshirt.xml
  src/chrome/content/rules/spreadshirt.at.xml
  src/chrome/content/rules/spreadshirt.be.xml
  src/chrome/content/rules/spreadshirt.ch.xml
  src/chrome/content/rules/spreadshirt.co.uk.xml
  src/chrome/content/rules/spreadshirt.com.au.xml
  src/chrome/content/rules/spreadshirt.com.xml
  src/chrome/content/rules/spreadshirt.de.xml
  src/chrome/content/rules/spreadshirt.dk.xml
  src/chrome/content/rules/spreadshirt.es.xml
  src/chrome/content/rules/spreadshirt.fi.xml
  src/chrome/content/rules/spreadshirt.fr.xml
  src/chrome/content/rules/spreadshirt.ie.xml
  src/chrome/content/rules/spreadshirt.it.xml
  src/chrome/content/rules/spreadshirt.net.xml
  src/chrome/content/rules/spreadshirt.nl.xml
  src/chrome/content/rules/spreadshirt.no.xml
  src/chrome/content/rules/spreadshirt.pl.xml
  src/chrome/content/rules/spreadshirt.se.xml
Labels: ruleset-enhancement

#19232 Re-enable Worldometers.info.xml and add more targets
  src/chrome/content/rules/Worldometers.info.xml
Labels: ruleset-enhancement

#19249 Create GirlsChannel.net.xml
  src/chrome/content/rules/GirlsChannel.net.xml
Labels: new-ruleset

#19206 Update Baidu.xml
  src/chrome/content/rules/Baidu.xml
Labels: china, ruleset-enhancement, top-100

#19212 Create Cht.sh.xml
  src/chrome/content/rules/Cht.sh.xml
Labels: new-ruleset

#19213 Create Ping.pe.xml
  src/chrome/content/rules/Ping.pe.xml
Labels: new-ruleset

#19215 Update Ticketmaster related rulesets
  src/chrome/content/rules/Ticketmaster.ae.xml
  src/chrome/content/rules/Ticketmaster.at.xml
  src/chrome/content/rules/Ticketmaster.be.xml
  src/chrome/content/rules/Ticketmaster.ch.xml
  src/chrome/content/rules/Ticketmaster.co.nz.xml
  src/chrome/content/rules/Ticketmaster.co.uk.xml
  src/chrome/content/rules/Ticketmaster.com.au.xml
  src/chrome/content/rules/Ticketmaster.com.mx.xml
  src/chrome/content/rules/Ticketmaster.cz.xml
  src/chrome/content/rules/Ticketmaster.de.xml
  src/chrome/content/rules/Ticketmaster.dk.xml
  src/chrome/content/rules/Ticketmaster.es.xml
  src/chrome/content/rules/Ticketmaster.eu.xml
  src/chrome/content/rules/Ticketmaster.fi.xml
  src/chrome/content/rules/Ticketmaster.fr.xml
  src/chrome/content/rules/Ticketmaster.gr.xml
  src/chrome/content/rules/Ticketmaster.ie.xml
  src/chrome/content/rules/Ticketmaster.it.xml
  src/chrome/content/rules/Ticketmaster.nl.xml
  src/chrome/content/rules/Ticketmaster.no.xml
  src/chrome/content/rules/Ticketmaster.pl.xml
  src/chrome/content/rules/Ticketmaster.se.xml
  src/chrome/content/rules/Ticketmaster.xml
  src/chrome/content/rules/Ticketweb.co.uk.xml
  src/chrome/content/rules/Ticketweb.com.xml
Labels: ruleset-enhancement

#19217 Update BT_Wi-fi.xml
  src/chrome/content/rules/BT_Wi-fi.xml
Labels: ruleset-enhancement

#19219 Update Overclockers.com.xml
  src/chrome/content/rules/Overclockers.com.xml
Labels: ruleset-enhancement

#19220 Update ShopWiki.com.xml
  src/chrome/content/rules/Oversee.xml
  src/chrome/content/rules/ShopWiki.com.xml
  src/chrome/content/rules/ShopWiki.xml
Labels: ruleset-enhancement

#19222 Create fitgirl-repacks.site
  src/chrome/content/rules/Fitgirl-repacks.site.xml
Labels: new-ruleset

#19224 Create Oprah.com.xml (closes #19077)
  src/chrome/content/rules/Oprah.com.xml
Labels: new-ruleset

#19216 Add Tanzschule-wernecke.de.xml
  src/chrome/content/rules/Tanzschule-wernecke.de.xml
Labels: new-ruleset

#19225 Create Kb.se.xml (closes #19022)
  src/chrome/content/rules/Kb.se.xml
Labels: new-ruleset

#19267 Update Bdimg.com.xml
  src/chrome/content/rules/Bdimg.com-mixedcontent.xml
  src/chrome/content/rules/Bdimg.com.xml
Labels: china

#19268 Update Sina.com.cn.xml
  src/chrome/content/rules/Sina.com.cn-mixedcontent.xml
  src/chrome/content/rules/Sina.com.cn.xml
Labels: china, top-100

#19265 Update Baidu.xml
  src/chrome/content/rules/Baidu.xml
Labels: china, top-100

#19269 Update Weibo.com.xml
  src/chrome/content/rules/Weibo.com.xml
Labels: china, ruleset-enhancement, top-100

#19226 Create Csair.com.xml (closes #18803)
  src/chrome/content/rules/Csair.com.xml
Labels: new-ruleset

#19275 Fix double-load of rulesets on update of update channels (fixes #19102)
  chromium/background-scripts/background.js
  chromium/background-scripts/update.js
Labels: bug

#19256 Add IndieHackers.com.xml
  src/chrome/content/rules/IndieHackers.com.xml
Labels: new-ruleset

#19227 Create bay12games.com.xml
  src/chrome/content/rules/bay12games.com.xml
Labels: new-ruleset

#19255 Add shoutout.wix.com to Wix.xml
  src/chrome/content/rules/Wix.xml
Labels: ruleset-enhancement

#19237 Add Circl.lu.xml
  src/chrome/content/rules/Circl.lu.xml
Labels: new-ruleset

#19182 Fix minor UX issues on the options page
  chromium/pages/options/style.css
Labels: enhancement, ui

#19254 Fix JS errors found by LGTM.com
  chromium/.eslintrc.json
  chromium/background-scripts/background.js
  chromium/background-scripts/incognito.js
  chromium/background-scripts/rules.js
  chromium/background-scripts/store.js
  chromium/pages/cancel/ux.js
  chromium/pages/debugging-rulesets/ux.js
  chromium/pages/options/ux.js
  chromium/pages/popup/ux.js
  chromium/test/incognito_test.js
  chromium/test/rules_test.js
  chromium/test/testing_utils.js
  chromium/test/update_test.js
  chromium/test/util_test.js
Labels: bug

#19231 Add NFARL.org.xml
  src/chrome/content/rules/NFARL.org.xml
Labels: new-ruleset

#19233 Add GamerSky.com.xml
  src/chrome/content/rules/GamerSky.com.xml
Labels: new-ruleset

#19288 Release 2020.5.20
  chromium/manifest.json
  src/META-INF/cose.manifest
  src/META-INF/cose.sig
  src/META-INF/manifest.mf
  src/META-INF/mozilla.rsa
  src/META-INF/mozilla.sf
Labels: release

#19272 Delete OPML.xml
  src/chrome/content/rules/OPML.xml
Labels: ruleset-enhancement

#19285 Update University-of-California-San-Diego.xml
  src/chrome/content/rules/University-of-California-San-Diego.xml
Labels: ruleset-enhancement

#19284 Update University-of-California-Berkeley.xml
  src/chrome/content/rules/University-of-California-Berkeley.xml
Labels: ruleset-enhancement

#19283 Update University_of_California_San_Francisco.xml
  src/chrome/content/rules/University_of_California_San_Francisco.xml
Labels: ruleset-enhancement

#19247 Create Bridgew.edu.xml
  src/chrome/content/rules/Bridgew.edu.xml
Labels: new-ruleset

#19274 Update Petridish.org.xml
  src/chrome/content/rules/Petridish-mismatches.xml
  src/chrome/content/rules/Petridish.org.xml
  src/chrome/content/rules/Petridish.xml
Labels: ruleset-enhancement

#19273 Update Onswipe.com.xml
  src/chrome/content/rules/Onswipe.com.xml
  src/chrome/content/rules/Onswipe.xml
Labels: ruleset-enhancement

#19271 Update MediaMatters.org.xml
  src/chrome/content/rules/MediaMatters.org.xml
Labels: ruleset-enhancement

#19270 Update FastSpring.com.xml
  src/chrome/content/rules/FastSpring-mismatches.xml
  src/chrome/content/rules/FastSpring.com.xml
  src/chrome/content/rules/FastSpring.xml
Labels: ruleset-enhancement

#19262 Update Leanpub.com.xml
  src/chrome/content/rules/Leanpub.com.xml
Labels: ruleset-enhancement

#19261 Update PBS.org related rulesets
  src/chrome/content/rules/PBS.org.xml
  src/chrome/content/rules/PBS.xml
  src/chrome/content/rules/PBSKids.org.xml
  src/chrome/content/rules/ShopPBS.org.xml
Labels: ruleset-enhancement

#19259 Update PatriotPost.us related rulesets
  src/chrome/content/rules/PatriotPost.com.xml
  src/chrome/content/rules/PatriotPost.us.xml
  src/chrome/content/rules/The_Patriot_Post.xml
Labels: ruleset-enhancement

#19253 Add ModArchive.org.xml
  src/chrome/content/rules/ModArchive.org.xml
Labels: new-ruleset

#19248 Update UPC.edu related rulesets
  src/chrome/content/rules/Polytechnic-University-of-Catalonia-mismatches.xml
  src/chrome/content/rules/Polytechnic-University-of-Catalonia.xml
  src/chrome/content/rules/UPC.edu.xml
  src/chrome/content/rules/UPC.es.xml
Labels: ruleset-enhancement

#19244 Add RC24.xyz.xml
  src/chrome/content/rules/RC24.xyz.xml
Labels: new-ruleset

#19238 Update HKGov-HKMA.xml
  src/chrome/content/rules/HKGov-HKMA.xml
Labels: ruleset-enhancement

#19236 Create iqoption.com.xml
  src/chrome/content/rules/iqoption.com.xml
Labels: new-ruleset

#19235 Create Investing.com.xml
  src/chrome/content/rules/Investing.com.xml
Labels: new-ruleset

#19263 Update Idea_Stations.org.xml
  src/chrome/content/rules/Idea_Stations.org.xml
Labels: ruleset-enhancement

#19250 Add technet.cz
  src/chrome/content/rules/technet-cz.xml
Labels: new-ruleset

#19143 Create klikr.pw
  src/chrome/content/rules/klikr.pw.xml
Labels: new-ruleset

#19246 Add ComputerCraft.ru.xml
  src/chrome/content/rules/ComputerCraft.ru.xml
Labels: new-ruleset

#18609 Create fczbkk.com.xml
  src/chrome/content/rules/fczbkk.com.xml
Labels: failing tests, new-ruleset

#18647 Create Giardini.biz.xml
  src/chrome/content/rules/Giardini.biz.xml
Labels: failing tests, new-ruleset

#18670 Create keep4u.ru.xml
  src/chrome/content/rules/keep4u.ru.xml
Labels: new-ruleset, top-100k, top-1m

#18672 Create radio-browser.info.xml
  src/chrome/content/rules/radio-browser.info.xml
Labels: failing tests, needs revision, new-ruleset

#19204 Add VoDLocker.to.xml
  src/chrome/content/rules/VoDLocker.to.xml
Labels: new-ruleset

#19192 Add ModTheSims.info.xml
  src/chrome/content/rules/ModTheSims.info.xml
Labels: new-ruleset

#18860 Update dw.com ruleset
  src/chrome/content/rules/DW-World.de.xml
  src/chrome/content/rules/DW.com.xml
  src/chrome/content/rules/DW.de.xml
Labels: ruleset-enhancement, top-10k, top-1m

#18528 Create smspower.org.xml
  src/chrome/content/rules/smspower.org.xml
Labels: new-ruleset, top-1m

#19245 Create boincstats.com.xml
  src/chrome/content/rules/boincstats.com.xml
Labels: new-ruleset

#19251 Add tekram.com
  src/chrome/content/rules/tekram.com.xml
Labels: new-ruleset

#19114 Create squarefaction.ru.xml
  src/chrome/content/rules/squarefaction.ru.xml
Labels: new-ruleset, top-1m

#18841 Add myaccount.ee.co.uk to Everything_Everywhere.xml
  src/chrome/content/rules/Everything_Everywhere.xml
Labels: ruleset-enhancement, top-100k

#19305 Add exclusion to Open.ac.uk.xml
  src/chrome/content/rules/Open.ac.uk.xml
Labels: ruleset-enhancement

#19214 Update cheat.sh.xml
  src/chrome/content/rules/cheat.sh.xml
Labels: ruleset-enhancement

#18685 Add ruleset: Tim.it
  src/chrome/content/rules/Tim.it.xml
Labels: new-ruleset, top-10k

#18722 Update ComiXology.com.xml
  src/chrome/content/rules/ComiXology.com.xml
Labels: new-ruleset, top-100k

#18724 Update Desk.com.xml
  src/chrome/content/rules/Desk.com.xml
Labels: top-100k, top-1m

#19073 Create suedkurier.de ruleset
  src/chrome/content/rules/SUEDKURIER.de.xml
Labels: new-ruleset, top-1m

#19082 Create finanzen.net ruleset
  src/chrome/content/rules/FINANZEN.NET.xml
Labels: new-ruleset, top-10k

#19303 Update TheStandNews.com.xml
  src/chrome/content/rules/TheStandNews.com.xml
Labels: ruleset-enhancement

#19300 Create BabyDiscuss.com.xml
  src/chrome/content/rules/BabyDiscuss.com.xml
Labels: new-ruleset

#19298 Update LIHKG.com.xml
  src/chrome/content/rules/LIHKG.com.xml
Labels: ruleset-enhancement

#19297 Update Unwire.hk.xml
  src/chrome/content/rules/Unwire.hk.xml
Labels: ruleset-enhancement

#19301 Create Demosisto.hk.xml
  src/chrome/content/rules/Demosisto.hk.xml
Labels: new-ruleset

#19299 Update HKGOLDEN.com.xml
  src/chrome/content/rules/HKGOLDEN.com.xml
Labels: ruleset-enhancement

#19186 Create iga.net.xml
  src/chrome/content/rules/iga.net.xml
Labels: new-ruleset

#19190 [apnic.net] Moved wq to active target, added new sub-domains
  src/chrome/content/rules/Asia-Pacific-Network-Information-Centre.xml
Labels: ruleset-enhancement

#19310 Add sr.ht.xml
  src/chrome/content/rules/sr.ht.xml
Labels: new-ruleset

#19311 Create Watsons.com.hk.xml
  src/chrome/content/rules/Watsons.com.hk.xml
Labels: new-ruleset

#19312 Add CDTFA.ca.gov.xml
  src/chrome/content/rules/CDTFA.ca.gov.xml
Labels: new-ruleset

#19316 Delete SlideMyPics.xml
  src/chrome/content/rules/SlideMyPics.xml
Labels: ruleset-enhancement

#19315 Delete Long_Access.com.xml
  src/chrome/content/rules/Long_Access.com.xml
Labels: ruleset-enhancement

#19314 Delete Instaemail.net.xml
  src/chrome/content/rules/Instaemail.net.xml
Labels: ruleset-enhancement
