Repository EFForg/https-everywhere, pull requests merged in 2020-03, with the labels that each got.

#18814 Re-enable PRQ.se.xml and add more targets
  src/chrome/content/rules/PRQ.se.xml
Labels: ruleset-enhancement

#18715 Create greatplacetowork.com.xml
  src/chrome/content/rules/greatplacetowork.com.xml
Labels: new-ruleset

#18973 Create istio.io ruleset
  src/chrome/content/rules/Istio.io.xml
Labels: new-ruleset, top-100k

#18995 update Ecosia.xml subdomains, short URL
  src/chrome/content/rules/Ecosia.org.xml
Labels: ruleset-enhancement, top-1k

#18967 Remove deleted rulesets from whitelist
  test/run_travis.sh
  utils/ruleset-whitelist-cleanup.sh
  utils/ruleset-whitelist.csv
Labels: ruleset-enhancement

#19004 Use Tor Browser user agent for fetch tests
  test/rules/checker.config.sample
  test/rules/coverage.checker.config
  test/rules/http.checker.config
  test/rules/manual.checker.config
Labels: enhancement, toolchain

#19007 Hotfix: Update Ruleset Whitelist
  utils/ruleset-whitelist.csv
Labels: toolchain

#18993 New Feature: Upboarding page
  chromium/background-scripts/background.js
  chromium/background-scripts/modules/on_before.js
  chromium/images/eff-logo-monogram-red.png
  chromium/images/onboarding/add_disabled_site.gif
  chromium/images/onboarding/ease_badssl.gif
  chromium/images/onboarding/httpseverywhere-logo.png
  chromium/pages/onboarding/style.css
  chromium/pages/onboarding/updated.html
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#18964 Update Cipher List for Pending Fetch Test
  test/rules/src/https_everywhere_checker/http_client.py
Labels: ruleset-enhancement, ruleset-testing

#19010 Update and rename MediaPost.xml to MediaPost.com.xml
  src/chrome/content/rules/MediaPost.com.xml
  src/chrome/content/rules/MediaPost.xml
  utils/ruleset-whitelist.csv
Labels: amazon-s3-2020, ruleset-enhancement, top-10k

#19011 Update NYTimes related rulesets
  src/chrome/content/rules/NYTimes-Problematic.xml
  src/chrome/content/rules/NYTimes.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-100

#19016 Update BBC.com.xml, fix #19012
  src/chrome/content/rules/BBC.com.xml
Labels: high priority, ruleset-enhancement, top-100

#18999 Add PiStar.uk.xml
  src/chrome/content/rules/PiStar.uk.xml
Labels: new-ruleset

#19020 Add ImprovedTube.com.xml
  src/chrome/content/rules/ImprovedTube.com.xml
Labels: new-ruleset

#19000 Add dark mode support for EASE error page
  chromium/images/banner-red.png
  chromium/images/banner-red.svg
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
Labels: EASE, ui

#19024 Create coronavirus.gov.hk.xml
  src/chrome/content/rules/GovHK.xml
  src/chrome/content/rules/coronavirus.gov.hk.xml
Labels: new-ruleset

#18969 Create tvtv.de ruleset
  src/chrome/content/rules/tvtv.de.xml
Labels: new-ruleset, top-1m

#18955 Create ariva.de ruleset
  src/chrome/content/rules/ARIVA.DE.xml
Labels: new-ruleset, top-10k

#18975 Update OU.edu.xml
  src/chrome/content/rules/OU.edu.xml
Labels: amazon-s3-2020, ruleset-enhancement, top-10k

#18971 Update arte ruleset
  src/chrome/content/rules/arte.xml
Labels: ruleset-enhancement, top-10k

#18977 Create bfdi.bund.de ruleset
  src/chrome/content/rules/BfDI.bund.de.xml
  src/chrome/content/rules/Verwaltung_Online.xml
Labels: new-ruleset, top-100k

#18976 Create bundesbank.de ruleset
  src/chrome/content/rules/Bundesbank.de.xml
Labels: new-ruleset

#18982 Update goldkeys.org related rulesets
  src/chrome/content/rules/Goldkeys.net.xml
  src/chrome/content/rules/Goldkeys.org.xml
Labels: ruleset-enhancement

#18988 Create otc-cta.gc.ca.xml
  src/chrome/content/rules/otc-cta.gc.ca.xml
Labels: new-ruleset

#18883 Create saskcoop.xml
  src/chrome/content/rules/saskcoop.xml
Labels: new-ruleset

#18884 Create sierraclubbc.xml
  src/chrome/content/rules/sierraclubbc.xml
Labels: new-ruleset

#18882 Create saskatooncarshare.xml
  src/chrome/content/rules/saskatooncarshare.xml
Labels: new-ruleset

#19032 Resolve a regression which breaks whitelisting features, fix #19029
  chromium/pages/popup/ux.js
Labels: bug

#19031 Add Samoanic.ws.xml
  src/chrome/content/rules/Samoanic.ws.xml
Labels: new-ruleset

#19039 Add Cirrus-CI.com.xml
  src/chrome/content/rules/Cirrus-CI.com.xml
Labels: new-ruleset

#18996 Create narcity.xml
  src/chrome/content/rules/narcity.xml
Labels: new-ruleset, top-1k

#19037 Create kohsuke.org ruleset
  src/chrome/content/rules/Kohsuke.org.xml
Labels: new-ruleset

#19006 Rule for moja.tatrabanka.sk replaced with more general rule
  src/chrome/content/rules/Moja.tatrabanka.sk.xml
  src/chrome/content/rules/Tatrabanka.sk.xml
Labels: ruleset-enhancement, top-100k

#19040 Fix and update heatmap ruleset
  src/chrome/content/rules/Heatmap.xml
Labels: ruleset-enhancement

#19041 Create trbo.com ruleset
  src/chrome/content/rules/trbo.com.xml
Labels: new-ruleset

#19042 Create stroeerdigitalgroup.de ruleset
  src/chrome/content/rules/stroeerdigitalgroup.de.xml
Labels: new-ruleset

#19043 Create facebook.net ruleset
  src/chrome/content/rules/facebook.net.xml
Labels: new-ruleset

#19044 Add target to and disable targets from welt.de ruleset
  src/chrome/content/rules/Welt.de.xml
Labels: ruleset-enhancement

#18911 Update and rename CathayPacific.com.xml
  src/chrome/content/rules/CathayPacific.com.xml
  src/chrome/content/rules/CathayPacificCargo.com.xml
  src/chrome/content/rules/Cathay_Pacific.xml
Labels: ruleset-enhancement, top-10k

#18978 Update Sinica.edu.tw.xml
  src/chrome/content/rules/Sinica.edu.tw.xml
Labels: ruleset-enhancement, top-100k

#19001 Re-activate and Update UBS.xml
  src/chrome/content/rules/UBS.xml
Labels: ruleset-enhancement, top-10k

#19038 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement

#19048 Add target to spiegel.de ruleset
  src/chrome/content/rules/Spiegel.xml
Labels: ruleset-enhancement

#19053 Create upscore.com ruleset
  src/chrome/content/rules/UpScore.com.xml
Labels: new-ruleset

#19045 Create asadcdn.com ruleset
  src/chrome/content/rules/asadcdn.com.xml
Labels: new-ruleset

#19047 Create requirejs.org ruleset
  src/chrome/content/rules/RequireJS.org.xml
Labels: new-ruleset

#19054 Create cdntrf.com ruleset
  src/chrome/content/rules/cdntrf.com.xml
Labels: new-ruleset

#19051 Create hna.de ruleset
  src/chrome/content/rules/HNA.de.xml
Labels: new-ruleset

#19060 Create geoedge.be ruleset
  src/chrome/content/rules/geoedge.be.xml
Labels: new-ruleset

#19062 Create funke.press ruleset
  src/chrome/content/rules/funke.press.xml
Labels: new-ruleset

#19064 Update tinypass.com ruleset
  src/chrome/content/rules/Tinypass.com.xml
Labels: ruleset-enhancement

#19065 Fix computerbild.de ruleset
  src/chrome/content/rules/computerbild.de.xml
Labels: ruleset-enhancement

#19059 Create yieldlove.com ruleset
  src/chrome/content/rules/Yieldlove.com.xml
Labels: new-ruleset

#19066 Create tag24.de ruleset
  src/chrome/content/rules/TAG24.de.xml
Labels: new-ruleset

#19046 Create msl24.de ruleset
  src/chrome/content/rules/msl24.de.xml
Labels: new-ruleset

#19057 Add target to and remove target from express.de ruleset
  src/chrome/content/rules/Express.de.xml
Labels: new-ruleset

#19072 Update and Rename lofter.com-mixedcontent.xml to lofter.com.xml
  src/chrome/content/rules/lofter.com-mixedcontent.xml
  src/chrome/content/rules/lofter.com.xml
Labels: china, new-ruleset

#19058 Create welect.de ruleset
  src/chrome/content/rules/Welect.de.xml
Labels: new-ruleset

#19070 Create twiago.com ruleset
  src/chrome/content/rules/Twiago.com.xml
Labels: new-ruleset

#19080 Add Cephalofair.com.xml
  src/chrome/content/rules/Cephalofair.com.xml
Labels: new-ruleset

#19083 Update LongTail ruleset
  src/chrome/content/rules/LongTail.xml
Labels: ruleset-enhancement

#19089 added client.foldingathome.org
  src/chrome/content/rules/Client.foldingathome.org.xml
Labels: new-ruleset

#19096 Update sportschau.de ruleset
  src/chrome/content/rules/Wdr.de.xml
Labels: ruleset-enhancement

#19097 Update kicker.de ruleset
  src/chrome/content/rules/Kicker.de.xml
Labels: ruleset-enhancement

#19100 Create apester.com ruleset
  src/chrome/content/rules/Apester.com.xml
Labels: new-ruleset

#19093 Create gamepro.de ruleset
  src/chrome/content/rules/GamePro.de.xml
Labels: new-ruleset

#19092 Create pcgameshardware.de ruleset
  src/chrome/content/rules/PCGamesHardware.de.xml
Labels: new-ruleset

#19098 Create bunte.de ruleset
  src/chrome/content/rules/BUNTE.de.xml
Labels: new-ruleset

#19067 Create recognified.net ruleset
  src/chrome/content/rules/recognified.net.xml
Labels: new-ruleset

#19055 Create glomex.com ruleset
  src/chrome/content/rules/glomex.com.xml
Labels: new-ruleset

#19063 Create vi-serve.com ruleset
  src/chrome/content/rules/vi-serve.com.xml
Labels: new-ruleset

#19075 Create die-neue-welle.de ruleset
  src/chrome/content/rules/die-neue-welle.de.xml
Labels: new-ruleset

#18984 Create fpslreb-crtespf.gc.ca.xml
  src/chrome/content/rules/fpslreb-crtespf.gc.ca.xml
Labels: failing tests, new-ruleset

#19049 Update EMS ruleset
  src/chrome/content/rules/EMS.xml
Labels: ruleset-enhancement

#19061 Create cleverpush.com ruleset
  src/chrome/content/rules/CleverPush.com.xml
Labels: new-ruleset

#18989 Create alternacare.ca.xml
  src/chrome/content/rules/alternacare.ca.xml
Labels: new-ruleset

#19068 Create ifec.org.hk.xml
  src/chrome/content/rules/ifec.org.hk.xml
Labels: new-ruleset

#19104 Update Centralfield.com.xml
  src/chrome/content/rules/Centralfield.com.xml
Labels: ruleset-enhancement

#19103 Update hko.gov.hk.xml
  src/chrome/content/rules/hko.gov.hk.xml
Labels: ruleset-enhancement

#19091 Create bacontent.de ruleset
  src/chrome/content/rules/bacontent.de.xml
Labels: new-ruleset

#19095 Create servote.de ruleset
  src/chrome/content/rules/servote.de.xml
Labels: new-ruleset

#19094 Create cgames.de ruleset
  src/chrome/content/rules/cgames.de.xml
Labels: new-ruleset
