Repository EFForg/https-everywhere, pull requests merged in 2020-08, with the labels that each got.

#19423 Update University-of-Cambridge.xml
  src/chrome/content/rules/University-of-Cambridge.xml
Labels: ruleset-enhancement

#19400 Create yuji.ne.jp ruleset
  src/chrome/content/rules/yuji.ne.jp.xml
Labels: new-ruleset

#19466 Add external-content subdomain to DuckDuckGo ruleset
  src/chrome/content/rules/DuckDuckGo.xml
Labels: ruleset-enhancement

#19417 Create Dailynous.com.xml
  src/chrome/content/rules/Dailynous.com.xml
Labels: new-ruleset

#19424 Create thom-designstudio.com.xml
  src/chrome/content/rules/thom-designstudio.com.xml
Labels: new-ruleset

#19427 Create apikabu.ru.xml
  src/chrome/content/rules/apikabu.ru.xml
Labels: new-ruleset

#19425 Create soundbounce.org.xml
  src/chrome/content/rules/soundbounce.org.xml
Labels: new-ruleset

#19429 Create iconarchive.com.xml
  src/chrome/content/rules/iconarchive.com.xml
Labels: new-ruleset

#19428 Create radio.garden.xml
  src/chrome/content/rules/radio.garden.xml
Labels: new-ruleset

#19430 Create dcmuseum.co.uk.xml
  src/chrome/content/rules/dcmuseum.co.uk.xml
Labels: new-ruleset

#19431 Create ijg.org.xml
  src/chrome/content/rules/ijg.org.xml
Labels: new-ruleset

#19432 Create firealpaca.com.xml
  src/chrome/content/rules/firealpaca.com.xml
Labels: new-ruleset

#19433 Create re2c.org.xml
  src/chrome/content/rules/re2c.org.xml
Labels: new-ruleset

#19457 Create agoradesk.com.xml
  src/chrome/content/rules/agoradesk.com.xml
Labels: new-ruleset, owner

#19456 Create localmonero.co.xml
  src/chrome/content/rules/localmonero.co.xml
Labels: new-ruleset, owner

#19468 README Docs Update: Testing
  CONTRIBUTING.md
  test/README.md
Labels: docs

#19302 Update Appledaily.xml
  src/chrome/content/rules/Appledaily.com.hk.xml
  src/chrome/content/rules/Appledaily.com.tw.xml
  src/chrome/content/rules/Appledaily.com.xml
  src/chrome/content/rules/Appledaily.xml
Labels: ruleset-enhancement, top-10k

#19474 Update External Dependency: Pako
  chromium/external/README.md
  chromium/package-lock.json
  chromium/package.json
Labels: dependencies

#19520 Feature action update
  .github/actions/https-everywhere-labeller/action.yml
  .github/actions/https-everywhere-labeller/dist/index.js
  .github/actions/https-everywhere-labeller/index.js
  .github/workflows/main.yml
Labels: toolchain

#19519 Add rules for Wikiscan.org
  src/chrome/content/rules/Wikiscan.xml
Labels: new-ruleset

#19479 Adding error message when the host being disabled is invalid
  chromium/pages/options/index.html
  chromium/pages/options/style.css
  chromium/pages/options/ux.js
  src/chrome/locale/en/https-everywhere.dtd
Labels: ui

#19534 Bump ECMAScript version to ES2019 to make ESLint pass
  chromium/.eslintrc.json
Labels: EFF, toolchain
