Repository EFForg/https-everywhere, pull requests merged in 2020-02, with the labels that each got.

#18826 Add Rule for Dict.cn
  src/chrome/content/rules/Dict.cn.xml
Labels: china, new-ruleset, top-10k

#18807 Update Redmine.org.xml
  src/chrome/content/rules/Redmine.org.xml
Labels: ruleset-enhancement, top-1m

#18842 Linux-KVM.org
  src/chrome/content/rules/Linux-KVM.org.xml
Labels: new-ruleset

#18835 Add bazaar.canonical.com
  src/chrome/content/rules/Canonical.xml
Labels: ruleset-enhancement, top-1m

#18833 Add Netlib.org.xml
  src/chrome/content/rules/Netlib.org.xml
Labels: new-ruleset

#18827 Add new ruleset for Frdic.com
  src/chrome/content/rules/Frdic.com.xml
Labels: new-ruleset, top-1m

#18782 Update UST.hk.xml
  src/chrome/content/rules/UST.hk.xml
Labels: ruleset-enhancement, top-100k

#18769 Re-activate and Update Rambler.ru.xml
  src/chrome/content/rules/Rambler.ru.xml
Labels: ruleset-enhancement, top-1k

#18800 Create termbin.com.xml
  src/chrome/content/rules/termbin.com.xml
Labels: new-ruleset, top-1m

#18779 Add codeforces.com
  src/chrome/content/rules/Codeforces.com.xml
Labels: new-ruleset, top-10k

#18727 Create ibiblio.org.xml
  src/chrome/content/rules/ibiblio.org.xml
Labels: new-ruleset, top-100k, top-1m

#18875 Add ruleset for githubassets.com
  src/chrome/content/rules/GitHub.xml
  src/chrome/content/rules/githubassets.com.xml
Labels: new-ruleset, top-100k

#18870 Add ruleset for wanderreitkarte.de
  src/chrome/content/rules/wanderreitkarte.de.xml
Labels: new-ruleset

#18871 Add ruleset for openlayers.org
  src/chrome/content/rules/OpenLayers.org.xml
Labels: new-ruleset, top-1m

#18872 Add ruleset for opensnowmap.org
  src/chrome/content/rules/OpenSnowMap.org.xml
Labels: new-ruleset

#18854 Add ruleset for hochwasser-rlp.de
  src/chrome/content/rules/Hochwasser-RLP.de.xml
Labels: new-ruleset, top-100k

#18855 Add rulesets for hochwasserzentralen.info and mhwz.de
  src/chrome/content/rules/Hochwasserzentralen.de.xml
  src/chrome/content/rules/Hochwasserzentralen.info.xml
  src/chrome/content/rules/mhwz.de.xml
Labels: new-ruleset

#18868 Add ruleset for fr.de
  src/chrome/content/rules/FR.de.xml
Labels: new-ruleset, top-100k

#18861 Add ruleset for futurezone.de
  src/chrome/content/rules/futurezone.de.xml
Labels: new-ruleset, top-100k

#18869 Add ruleset for opentopomap.org
  src/chrome/content/rules/OpenTopoMap.org.xml
Labels: new-ruleset

#18862 Add ruleset for heute.at
  src/chrome/content/rules/heute.at.xml
Labels: new-ruleset, top-100k

#18864 Add ruleset for mdr.de
  src/chrome/content/rules/MDR.de.xml
Labels: new-ruleset, top-10k

#18857 Add ruleset for berliner-zeitung.de
  src/chrome/content/rules/Berliner-Zeitung.de.xml
Labels: new-ruleset, top-100k

#18853 Update stern.de ruleset
  src/chrome/content/rules/Stern.de.xml
Labels: ruleset-enhancement, top-10k

#18847 Update n-tv.de ruleset
  src/chrome/content/rules/n-tv.de.xml
Labels: ruleset-enhancement, top-10k

#18876 Update and rename Roundhouse.xml to Roundhouse.org.uk.xml
  src/chrome/content/rules/Roundhouse.org.uk.xml
  src/chrome/content/rules/Roundhouse.xml
Labels: ruleset-enhancement

#18851 Update merkur.de ruleset
  src/chrome/content/rules/Merkur.de.xml
Labels: ruleset-enhancement, top-10k

#18879 Update weather.com ruleset
  src/chrome/content/rules/Weather.com.xml
Labels: top-1k

#18850 Add ruleset for darksky.net
  src/chrome/content/rules/DarkSky.net.xml
Labels: new-ruleset, top-100k

#18839 Add ruleset for elektronik-kompendium.de
  src/chrome/content/rules/Elektronik-Kompendium.de.xml
Labels: new-ruleset, top-100k

#18837 Update gnupg.org ruleset
  src/chrome/content/rules/GnuPG.org.xml
Labels: ruleset-enhancement, top-1m

#18836 Add Gpg4win.de ruleset
  src/chrome/content/rules/Gpg4win.de.xml
  src/chrome/content/rules/Gpg4win.org.xml
Labels: new-ruleset, top-1m

#18829 Add more targets to kit.edu ruleset
  src/chrome/content/rules/Karlsruhe_Institute_of_Technology.xml
Labels: new-ruleset, top-1m

#18831 Add ruleset for themeparkreview.com
  src/chrome/content/rules/ThemeParkReview.com.xml
Labels: new-ruleset

#18838 Update leo.org ruleset
  src/chrome/content/rules/Leo.org.xml
Labels: ruleset-enhancement, top-10k

#18844 Rename and Update Branson_Zipline.xml
  src/chrome/content/rules/Branson_Zipline.xml
  src/chrome/content/rules/WolfeBransonZipline.com.xml
Labels: ruleset-enhancement

#18878 Update gnutls.org ruleset
  src/chrome/content/rules/GnuTLS.org.xml
Labels: ruleset-enhancement

#18845 Fix and update welt.de ruleset
  src/chrome/content/rules/Welt.de.xml
Labels: ruleset-enhancement, top-10k

#18863 Add ruleset for watson.de
  src/chrome/content/rules/watson.de.xml
Labels: new-ruleset, top-100k

#18856 Add ruleset for bz-berlin.de
  src/chrome/content/rules/BZ-Berlin.de.xml
Labels: new-ruleset, top-100k

#18846 Update spiegel.de ruleset
  src/chrome/content/rules/Spiegel.xml
Labels: ruleset-enhancement, top-1k

#18874 Add ruleset for tagesspiegel.de
  src/chrome/content/rules/Tagesspiegel.de.xml
Labels: new-ruleset, top-10k

#18849 Fix and update zdf ruleset
  src/chrome/content/rules/zdf.xml
Labels: ruleset-enhancement, top-10k

#18908 Update notepad-plus-plus.org ruleset
  src/chrome/content/rules/Notepad++.xml
Labels: ruleset-enhancement, top-10k

#18909 Add ruleset for codeblocks.org
  src/chrome/content/rules/Codeblocks.org.xml
Labels: new-ruleset, top-1m

#18915 [engadget.com] Update ruleset
  src/chrome/content/rules/Engadget.com.xml
Labels: ruleset-enhancement, top-10k

#18907 Update videolan.org ruleset
  src/chrome/content/rules/VideoLAN.org.xml
Labels: ruleset-enhancement, top-10k

#18895 Add ruleset for psychology-tools.com
  src/chrome/content/rules/Psychology-Tools.com.xml
Labels: new-ruleset, owner

#18906 Add ruleset for keepassxc.org
  src/chrome/content/rules/KeePassXC.org.xml
Labels: new-ruleset, top-1m

#18822 Update DLsite.com.xml
  src/chrome/content/rules/DLsite.com.xml
  src/chrome/content/rules/DLsite.jp.xml
  src/chrome/content/rules/blogimg.jp.xml
Labels: ruleset-enhancement, top-10k

#18890 Remove upupgame from cdngc.net.xml
  src/chrome/content/rules/cdngc.net.xml
Labels: ruleset-enhancement

#18929 Update centos.org ruleset
  src/chrome/content/rules/CentOS.org.xml
Labels: ruleset-enhancement, top-100k

#18947 Create netzwelt.de ruleset
  src/chrome/content/rules/NETZWELT.de.xml
Labels: new-ruleset, top-10k

#18934 Update mariadb.com and mariadb.org rulesets
  src/chrome/content/rules/MariaDB.com.xml
  src/chrome/content/rules/MariaDB.org.xml
  src/chrome/content/rules/MariaDB.xml
  src/chrome/content/rules/Monty_Program.xml
Labels: ruleset-enhancement, top-100k

#18932 Add ruleset for ice-wm.org
  src/chrome/content/rules/Ice-WM.org.xml
Labels: new-ruleset

#18922 Add ruleset for metropolnews.info
  src/chrome/content/rules/Metropolnews.info.xml
Labels: new-ruleset

#18923 Add ruleset for presseportal.de
  src/chrome/content/rules/Presseportal.de.xml
Labels: new-ruleset, top-100k

#18928 Update sqlite.org ruleset
  src/chrome/content/rules/SQLite.xml
Labels: ruleset-enhancement, top-100k

#18931 Add ruleset for enlightenment.org
  src/chrome/content/rules/Enlightenment.org.xml
Labels: new-ruleset

#18933 Add ruleset for systemd.io
  src/chrome/content/rules/systemd.io.xml
Labels: new-ruleset

#18917 Fix rule hostname typos (#12297)
  src/chrome/content/rules/City-Mail.xml
  src/chrome/content/rules/EPEAT.xml
  src/chrome/content/rules/MVG-mobil.de.xml
  src/chrome/content/rules/OHeffernan.xml
  src/chrome/content/rules/The-Republic.xml
  src/chrome/content/rules/Whisper-Gifts.xml
Labels: ruleset-enhancement

#18935 Add ruleset for verkehrsinfo-bw.de
  src/chrome/content/rules/VerkehrsInfo-BW.de.xml
Labels: new-ruleset

#18920 Add ruleset for connect.de
  src/chrome/content/rules/connect.de.xml
Labels: new-ruleset, top-100k

#18936 Add ruleset for emberjs.com
  src/chrome/content/rules/Emberjs.com.xml
Labels: new-ruleset, top-1m

#18901 Update tz.de ruleset
  src/chrome/content/rules/TZ.de.xml
Labels: ruleset-enhancement, top-10k

#18905 Update cygwin.com ruleset
  src/chrome/content/rules/Cygwin.com.xml
Labels: ruleset-enhancement, top-1m

#18912 Add ruleset for bnn.de
  src/chrome/content/rules/BNN.de.xml
Labels: new-ruleset, top-100k

#18914 Add ruleset for waz.de
  src/chrome/content/rules/waz.de.xml
Labels: new-ruleset, top-100k

#18948 Create t3n.de ruleset
  src/chrome/content/rules/t3n.de.xml
Labels: new-ruleset, top-100k

#18801 Ignore /kr/ pages in fedex.com
  src/chrome/content/rules/FedEx.com.xml
Labels: needs test coverage update, ruleset-bug, ruleset-enhancement, top-1k

#18930 Rename and update xfce.org ruleset
  src/chrome/content/rules/XFCE.org.xml
Labels: ruleset-enhancement

#18894 Add ruleset for swr.de
  src/chrome/content/rules/SWR.de.xml
Labels: new-ruleset, top-100k

#18865 Amend check rules python for Fetch Test
  test/rules/disable-broken-rulesets.checker.config
  test/rules/src/https_everywhere_checker/check_rules.py
Labels: ruleset-testing, toolchain

#18858 Fix focus.de ruleset
  src/chrome/content/rules/Focus.de.xml
Labels: ruleset-enhancement, top-10k

#18961 Update daserste.de ruleset
  src/chrome/content/rules/DasErste.de.xml
Labels: top-10k

#18959 Create zierer.com ruleset
  src/chrome/content/rules/Zierer.com.xml
Labels: new-ruleset

#18956 Create ludwigshafen.de and ludwigshafen-diskutiert.de rulesets
  src/chrome/content/rules/Ludwigshafen-diskutiert.de.xml
  src/chrome/content/rules/Ludwigshafen.de.xml
Labels: new-ruleset

#18937 Update Deutschlandradio rulesets
  src/chrome/content/rules/DeutschlandRadio.xml
  src/chrome/content/rules/Deutschlandfunk.de.xml
  src/chrome/content/rules/Deutschlandfunkkultur.de.xml
  src/chrome/content/rules/Deutschlandfunknova.de.xml
  src/chrome/content/rules/Deutschlandradio.de.xml
  src/chrome/content/rules/dlf.de.xml
Labels: ruleset-enhancement, top-100k

#18913 Add ruleset for chip.de
  src/chrome/content/rules/CHIP.de.xml
Labels: new-ruleset, top-1k

#18848 Fix and update sueddeutsche.de ruleset
  src/chrome/content/rules/Suddeutsche_Zeitung-problematic.xml
  src/chrome/content/rules/Suddeutsche_Zeitung.xml
Labels: ruleset-enhancement, top-10k

#18924 Add ruleset for gnupg.com
  src/chrome/content/rules/GnuPG.com.xml
  src/chrome/content/rules/GnuPG.org.xml
Labels: new-ruleset

#18899 voxmedia.com-resources.xml: Remove dup targets
  src/chrome/content/rules/voxmedia.com-resources.xml
Labels: ruleset-enhancement

#18820 Add mesa.freedesktop.org
  src/chrome/content/rules/FreeDesktop.xml
Labels: ruleset-enhancement, top-1m

#18834 Add Linux-nfs.org.xml
  src/chrome/content/rules/Linux-nfs.org.xml
Labels: new-ruleset

#18840 Add ruleset for bsh.de
  src/chrome/content/rules/BSH.de.xml
  src/chrome/content/rules/Verwaltung_Online.xml
Labels: new-ruleset, top-100k

#18843 Update EmuNewz-Network.xml
  src/chrome/content/rules/EmuNewz-Network.xml
  src/chrome/content/rules/EmuNewz.net.xml
  src/chrome/content/rules/JPCSP.org.xml
Labels: ruleset-enhancement

#18903 Add ruleset for öpnvkarte.de
  src/chrome/content/rules/OEPNVKarte.xml
Labels: new-ruleset

#18859 Update FAZ ruleset
  src/chrome/content/rules/FAZ-mismatches.xml
  src/chrome/content/rules/FAZ.xml
Labels: ruleset-enhancement, top-10k

#18927 Update NPR.org.xml
  src/chrome/content/rules/NPR.org.xml
Labels: ruleset-enhancement, top-1k

#18926 Update gulli.com.xml
  src/chrome/content/rules/gulli.com.xml
Labels: ruleset-enhancement

#18830 Add ruleset for coasterforce.com
  src/chrome/content/rules/CoasterForce.com.xml
Labels: new-ruleset

#18852 Update rtl.de ruleset
  src/chrome/content/rules/RTL.de.xml
Labels: ruleset-enhancement, top-100k

#18919 AmazonAWS.com.xml: Remove failing test
  src/chrome/content/rules/AmazonAWS.com.xml
  src/chrome/content/rules/Law_Business_Research_CDN.xml
Labels: ruleset-enhancement, top-100

#18888 Madison-Logic.xml: Fix regex replacement group
  src/chrome/content/rules/Madison-Logic.xml
Labels: ruleset-enhancement

#18952 Orion_Magazine.org.xml: Add .com target
  src/chrome/content/rules/Orion_Magazine.org.xml
Labels: ruleset-enhancement

#18974 Create eslint.org ruleset
  src/chrome/content/rules/ESLint.org.xml
Labels: new-ruleset, top-100k

#18972 Update 3sat.de ruleset
  src/chrome/content/rules/3sat.xml
Labels: ruleset-enhancement

#18925 Update Demand Media related rulesets
  src/chrome/content/rules/Cracked.com.xml
  src/chrome/content/rules/CrackedCDN.com.xml
  src/chrome/content/rules/Demand-Media-mismatches.xml
  src/chrome/content/rules/Demand-Media.xml
  src/chrome/content/rules/DemandStudios.com.xml
  src/chrome/content/rules/ENomCentral.xml
  src/chrome/content/rules/Enom.xml
  src/chrome/content/rules/GolfLink.com.xml
  src/chrome/content/rules/GolfLink.net.xml
  src/chrome/content/rules/Trails.com.xml
  src/chrome/content/rules/glimg.net.xml
Labels: ruleset-enhancement, top-1m

#18979 Update Sina.com.cn.xml
  src/chrome/content/rules/Sina.com.cn.xml
Labels: china, ruleset-enhancement, top-100

#18904 Update and rename Invite_Media.xml to InviteMedia.com.xml
  src/chrome/content/rules/InviteMedia.com.xml
  src/chrome/content/rules/Invite_Media.xml
Labels: ruleset-enhancement

#18992 Fix options page appearance on Firefox when dark mode is on
  chromium/pages/options/style.css
Labels: bug, firefox, ui
