Repository EFForg/https-everywhere, pull requests merged in 2020-11, with the labels that each got.

#19632 Add rules for Asfar.org.uk
  src/chrome/content/rules/Asfar.org.uk.xml
Labels: new-ruleset

#19646 Add a ruleset for artefact.org
  src/chrome/content/rules/artefact.org.xml
Labels: new-ruleset

#19647 Add a ruleset for molodoi.net
  src/chrome/content/rules/molodoi.net.xml
Labels: new-ruleset

#19648 Add Stephenpi.com.xml
  src/chrome/content/rules/Stephenpi.com.xml
Labels: new-ruleset

#19672 Create bmf1.dk.xml
  src/chrome/content/rules/bmf1.dk.xml
Labels: new-ruleset

#19671 Create davidperkinsphotography.com.xml
  src/chrome/content/rules/davidperkinsphotography.com.xml
Labels: new-ruleset

#19716 Create cppreference.com.xml
  src/chrome/content/rules/cppreference.com.xml
Labels: new-ruleset

#19668 Create alcohol-soft.com.xml
  src/chrome/content/rules/alcohol-soft.com.xml
Labels: new-ruleset

#19720 Add Pkcell.com.xml
  src/chrome/content/rules/Pkcell.com.xml
Labels: new-ruleset

#19707 Add rules for Restcountries.eu
  src/chrome/content/rules/Restcountries.eu.xml
Labels: new-ruleset

#19724 Add rules for ss-iptv.com
  src/chrome/content/rules/ss-iptv.com.xml
Labels: new-ruleset

#19700 Create Thecanadaline.com.xml
  src/chrome/content/rules/Thecanadaline.com.xml
Labels: new-ruleset

#19683 Add rules for jennyvixenryan.com
  src/chrome/content/rules/Jennyvixenryan.com.xml
Labels: new-ruleset

#19726 Create jmsustainability.com.xml
  src/chrome/content/rules/jmsustainability.com.xml
Labels: new-ruleset

#19740 Update rules for Open Library.org
  src/chrome/content/rules/Open_Library.org.xml
Labels: new-ruleset

#19735 Create tildeslash.com.xml
  src/chrome/content/rules/tildeslash.com.xml
Labels: new-ruleset

#19752 Add MarginalRevolution.com.xml
  src/chrome/content/rules/MarginalRevolution.com.xml
Labels: new-ruleset

#19749 Add modulus.com.xml
  src/chrome/content/rules/modulus.com.xml
Labels: new-ruleset

#19747 Add WilsonTimes.com.xml
  src/chrome/content/rules/WilsonTimes.com.xml
Labels: new-ruleset

#19746 Add 0chan.one.xml
  src/chrome/content/rules/0chan.one.xml
Labels: new-ruleset

#19742 Add IndianaCourts.us.xml
  src/chrome/content/rules/IndianaCourts.us.xml
Labels: new-ruleset

#19718 Add Indeed.co.uk.xml
  src/chrome/content/rules/Indeed.co.uk.xml
Labels: new-ruleset

#19725 Create ccxmedia.org.xml
  src/chrome/content/rules/ccxmedia.org.xml
Labels: new-ruleset

#19605 Add cmpxchg8b.com.xml
  src/chrome/content/rules/cmpxchg8b.com.xml
Labels: new-ruleset

#19681 Create zeus-software.com.xml
  src/chrome/content/rules/zeus-software.com.xml
Labels: new-ruleset

#19732 Update OpenVPN.xml
  src/chrome/content/rules/OpenVPN.xml
Labels: ruleset-enhancement

#19760 Add mpg123.org.xml
  src/chrome/content/rules/mpg123.org.xml
Labels: new-ruleset

#19754 Add SpaceLab.ie.xml
  src/chrome/content/rules/SpaceLab.ie.xml
Labels: new-ruleset

#19645 Add a ruleset for alsace-lait.com
  src/chrome/content/rules/alsace-lait.com.xml
Labels: new-ruleset

#19759 Add nzbget.net.xml
  src/chrome/content/rules/nzbget.net.xml
Labels: new-ruleset

#19734 Create angband.pl.xml
  src/chrome/content/rules/angband.pl.xml
Labels: new-ruleset

#19744 Add SmallArmsReview.com.xml
  src/chrome/content/rules/SmallArmsReview.com.xml
Labels: new-ruleset

#19770 Remove OpenMailBox.org.xml
  src/chrome/content/rules/OpenMailBox.org.xml
Labels: ruleset-enhancement

#19764 Update Bittorrent.org.xml
  src/chrome/content/rules/Bittorrent.org.xml
Labels: ruleset-enhancement, top-1m

#19708 Modification: Opera CRX Creation
  browser-dist/browser-dist.md
  browser-dist/edge.sh
  browser-dist/opera.sh
  make.sh
Labels: opera

#19779 IOCCC.org
  src/chrome/content/rules/IOCCC.org.xml
Labels: ruleset-enhancement

#19755 Update Raptr.com.xml
  src/chrome/content/rules/Raptr.com.xml
  src/chrome/content/rules/raptrcdn.com.xml
Labels: ruleset-enhancement

#19756 Remove ICMail.xml
  src/chrome/content/rules/ICMail.xml
Labels: ruleset-enhancement

#19757 Remove Instella_Platform.xml
  src/chrome/content/rules/Instella_Platform.xml
Labels: ruleset-enhancement

#19743 Add CafePharma.com.xml
  src/chrome/content/rules/CafePharma.com.xml
Labels: new-ruleset, top-1m

#19637 Move Global Setting for Defaults up in UI
  chromium/pages/popup/index.html
  chromium/pages/popup/style.css
Labels: ui

#19774 Update Politico.xml
  src/chrome/content/rules/Politico.xml
Labels: top-1k

#19763 Add TikTok.com.xml
  src/chrome/content/rules/TikTok.xml
Labels: new-ruleset, top-1k

#19294 Show the grey icon for whitelisted sites with a port number
  chromium/background-scripts/background.js
  chromium/background-scripts/util.js
  chromium/test/util_test.js
Labels: enhancement

#19673 Create ltr-data.se.xml
  src/chrome/content/rules/ltr-data.se.xml
Labels: new-ruleset

#19674 Create flyingwith.us.xml
  src/chrome/content/rules/flyingwith.us.xml
Labels: new-ruleset

#19675 Create js1k.com.xml
  src/chrome/content/rules/js1k.com.xml
Labels: new-ruleset

#19680 Create waidelotte.org.xml
  src/chrome/content/rules/waidelotte.org.xml
Labels: new-ruleset

#19685 Create alf.nu.xml
  src/chrome/content/rules/alf.nu.xml
Labels: new-ruleset

#19686 Create wolfbeast.com.xml
  src/chrome/content/rules/wolfbeast.com.xml
Labels: new-ruleset

#19690 Create alt-usage-english.org.xml
  src/chrome/content/rules/alt-usage-english.org.xml
Labels: new-ruleset

#19706 Add Nettog.dk.xml
  src/chrome/content/rules/Nettog.dk.xml
Labels: new-ruleset

#19709 add frankfurt-university.de.xml
  src/chrome/content/rules/frankfurt-university.de.xml
Labels: new-ruleset, top-1m

#19713 Add rules for cointelegraph.com
  src/chrome/content/rules/Cointelegraph.com.xml
Labels: new-ruleset, top-10k

#19717 Add Dogpile.com.xml
  src/chrome/content/rules/Dogpile.com.xml
Labels: new-ruleset, top-100k, top-1m

#19719 Create analog.com.xml
  src/chrome/content/rules/analog.com.xml
Labels: new-ruleset, top-100k, top-10k

#19721 Update Lurkmore.to.xml
  src/chrome/content/rules/Lurkmore.to.xml
Labels: ruleset-enhancement, top-1m

#19723 Update Pikabu.ru.xml
  src/chrome/content/rules/Pikabu.ru.xml
Labels: ruleset-enhancement, top-10k

#19728 Add rules for Razzies.com
  src/chrome/content/rules/Razzies.com.xml
Labels: new-ruleset

#19789 Update and rename amap.xml to amap.com.xml
  src/chrome/content/rules/amap-mixedcontent.xml
  src/chrome/content/rules/amap.com.xml
  src/chrome/content/rules/amap.xml
Labels: china

#19727 Create elections.bc.ca.xml
  src/chrome/content/rules/elections.bc.ca.xml
Labels: new-ruleset, top-1m

#19751 Add onepace.net.xml
  src/chrome/content/rules/onepace.net.xml
Labels: new-ruleset, top-1m

#19806 Create List.org.xml (GNU Mailman)
  src/chrome/content/rules/List.org.xml
Labels: new-ruleset
