Repository EFForg/https-everywhere, pull requests merged in 2020-10, with the labels that each got.

#19571 Change Naming Convention - Block/Allow Listing for Clarity and Inclusion
  docs/en_US/faq.md
  docs/es/faq.md
  test/rules/coverage.checker.config
  test/rules/http.checker.config
  test/validations/special/duplicate-allowlist-cleanup.sh
  test/validations/special/duplicate-allowlist.txt
  test/validations/special/run.py
  utils/mk-client-allowlist/dbconnect.py
  utils/mk-client-allowlist/run.py
  utils/ruleset-allowlist-cleanup.sh
  utils/ruleset-allowlist.csv
Labels: docs, toolchain

#19639 Remove 8chan.co.xml
  src/chrome/content/rules/8chan.co.xml
Labels: ruleset-enhancement

#19640 Remove Unused MKClient Utility
  utils/mk-client-allowlist/dbconnect.py
  utils/mk-client-allowlist/run.py
Labels: code-style

#19606 WIPO
  src/chrome/content/rules/WIPO.int.xml
Labels: new-ruleset

#19649 Add Fast.com.xml
  src/chrome/content/rules/Fast.com.xml
Labels: new-ruleset, top-1k

#19604 Update hsbc.com.hk.xml
  src/chrome/content/rules/hsbc.com.hk.xml
Labels: ruleset-enhancement

#19602 Add Invidious.xyz.xml
  src/chrome/content/rules/Invidious.xyz.xml
Labels: new-ruleset

#19601 Add Invidious.tube.xml
  src/chrome/content/rules/Invidious.tube.xml
Labels: new-ruleset

#19600 Add Invidious.site.xml
  src/chrome/content/rules/Invidious.site.xml
Labels: new-ruleset

#19591 Update Ow.ly.xml
  src/chrome/content/rules/Ow.ly.xml
Labels: ruleset-enhancement

#19594 Rename and update CityEmail.com.xml
  src/chrome/content/rules/CityEmail.com.xml
  src/chrome/content/rules/Wizard-Internet-Services.xml
Labels: ruleset-enhancement

#19590 Update EPEAT.xml
  src/chrome/content/rules/EPEAT.xml
Labels: ruleset-enhancement

#19589 Rename and update PragmaticMarketing.com.xml
  src/chrome/content/rules/PragmaticMarketing.com.xml
  src/chrome/content/rules/Pragmatic_Marketing.com.xml
Labels: ruleset-enhancement, top-1m

#19592 Delete Rev2pub.com.xml
  src/chrome/content/rules/M2pub.com.xml
  src/chrome/content/rules/Matomy-Media.xml
  src/chrome/content/rules/Matomy_Market.xml
  src/chrome/content/rules/Rev2pub.com.xml
  src/chrome/content/rules/Xtendmedia.com.xml
Labels: ruleset-enhancement

#19642 Remove Old Issue Format Bot
  utils/issue-format-bot/.env.example
  utils/issue-format-bot/.eslintrc.json
  utils/issue-format-bot/.gitignore
  utils/issue-format-bot/LICENSE
  utils/issue-format-bot/README.md
  utils/issue-format-bot/app.json
  utils/issue-format-bot/docs/deploy.md
  utils/issue-format-bot/docs/development.md
  utils/issue-format-bot/index.js
  utils/issue-format-bot/lib/alexa.js
  utils/issue-format-bot/lib/helptext.js
  utils/issue-format-bot/lib/issueedit.js
  utils/issue-format-bot/lib/labeler.js
  utils/issue-format-bot/lib/newissue.js
  utils/issue-format-bot/lib/parse.js
  utils/issue-format-bot/lib/validate.js
  utils/issue-format-bot/package-lock.json
  utils/issue-format-bot/package.json
  utils/issue-format-bot/test/.eslintrc
  utils/issue-format-bot/test/alexa-mock-test.js
  utils/issue-format-bot/test/context-mock-test.js
  utils/issue-format-bot/test/helptext-test.js
  utils/issue-format-bot/test/issueedit-handler-test.js
  utils/issue-format-bot/test/labeler-test.js
  utils/issue-format-bot/test/lib/handlerutil.js
  utils/issue-format-bot/test/mocks/alexa.js
  utils/issue-format-bot/test/mocks/context.js
  utils/issue-format-bot/test/mocks/robot.js
  utils/issue-format-bot/test/newissue-handler-test.js
  utils/issue-format-bot/test/parse-test.js
  utils/issue-format-bot/test/robot-mock-test.js
  utils/issue-format-bot/test/validate-test.js
Labels: minor

#19651 Update dianping.com.xml
  src/chrome/content/rules/dianping.com.xml
Labels: china, ruleset-enhancement

#19655 Hotfix: Update Chromedriver
  test/setup_travis.sh
Labels: toolchain

#19652 Add JSXC.org.xml
  src/chrome/content/rules/JSXC.org.xml
Labels: new-ruleset

#19659 Translate Chinese language comment in JD.com.xml
  src/chrome/content/rules/JD.com.xml
Labels: china, ruleset-enhancement

#19566 Add inmediahk.net.xml
  src/chrome/content/rules/inmediahk.net.xml
Labels: new-ruleset

#19658 Remove Sidibouras.xml
  src/chrome/content/rules/Sidibouras.xml
Labels: ruleset-enhancement

#19636 Hotfix: Amend URL Construction Log Error
  chromium/background-scripts/background.js
Labels: enhancement, minor

#19612 Add Crunchyroll.com.xml
  src/chrome/content/rules/Crunchyroll.com.xml
Labels: new-ruleset, top-1k

#19662 Update JD.com-Problematic.xml
  src/chrome/content/rules/JD.com-Problematic.xml
Labels: china, ruleset-enhancement

#19663 Update Jcloud.com.xml
  src/chrome/content/rules/Jcloud.com.xml
Labels: china, ruleset-enhancement

#19588 Rename and update OculusVR.com.xml
  src/chrome/content/rules/OculusVR.com.xml
  src/chrome/content/rules/Oculus_VR.xml
Labels: ruleset-enhancement, top-100k

#19529 Update AASTOCKS.com.xml
  src/chrome/content/rules/AASTOCKS.com.xml
Labels: ruleset-enhancement, top-10k, top-1k

#19593 Rename and update Ecwid.com.xml
  src/chrome/content/rules/Ecwid.com.xml
  src/chrome/content/rules/Ecwid.xml
Labels: ruleset-enhancement, top-10k

#18900 Greek-travel.xml: Remove outdated tests and rules
  src/chrome/content/rules/Greek-travel.xml
  utils/ruleset-allowlist.csv
Labels: ruleset-enhancement, top-100k, top-1k, top-1m

#19609 Create Rulesets for issue #18059 (Whoer.net.xml & Surfshark.com.xml)
  src/chrome/content/rules/Surfshark.com.xml
  src/chrome/content/rules/Whoer.net.xml
Labels: new-ruleset, top-100k, top-10k

#19616 Add 9anime.to.xml
  src/chrome/content/rules/9anime.to.xml
Labels: new-ruleset, top-10k

#19441 Create lostpic.net.xml
  src/chrome/content/rules/lostpic.net.xml
Labels: needs revision, new-ruleset, top-100k, top-1m

#19661 Update and Rename JD.com-CIties.xml to JD.com-Cities.xml
  src/chrome/content/rules/JD.com-Cities.xml
Labels: china, ruleset-enhancement

#19698 Update ximalaya.xml
  src/chrome/content/rules/ximalaya.xml
Labels: china, ruleset-enhancement

#19697 Update douban.fm.xml
  src/chrome/content/rules/douban.fm.xml
Labels: china, ruleset-enhancement

#19696 Update doubanio.com.xml
  src/chrome/content/rules/doubanio.com.xml
Labels: china, ruleset-enhancement

#19695 Update Douban.com.xml
  src/chrome/content/rules/Douban.com.xml
Labels: china, ruleset-enhancement

#19694 Update Weibo.cn.xml
  src/chrome/content/rules/Weibo.cn.xml
Labels: china, ruleset-enhancement

#19702 Update JD.com.xml
  src/chrome/content/rules/JD.com-Problematic.xml
  src/chrome/content/rules/JD.com.xml
Labels: ruleset-enhancement

#19703 Update 360_Safe.com.xml
  src/chrome/content/rules/360_Safe.com.xml
Labels: china, ruleset-enhancement

#19699 Update DNS-shop.ru.xml
  src/chrome/content/rules/DNS-shop.ru.xml
  src/chrome/content/rules/dns-shop.ru.xml
Labels: ruleset-enhancement, top-10k

#19701 Add rules for Bitfun.co
  src/chrome/content/rules/Bitfun.co.xml
Labels: new-ruleset, top-10k

#19670 Create softwareok.com.xml
  src/chrome/content/rules/softwareok.com.xml
Labels: new-ruleset, top-100k, top-1m

#19676 Update jsbin.com.xml
  src/chrome/content/rules/jsbin.com.xml
Labels: new-ruleset, top-100k

#19684 Add rules for Romhacking.net
  src/chrome/content/rules/Romhacking.net.xml
Labels: new-ruleset, top-100k, top-1m

#19569 Add FireSmoke.ca.xml
  src/chrome/content/rules/FireSmoke.ca.xml
Labels: new-ruleset, top-1m

#19577 Add VSIXGallery.com.xml
  src/chrome/content/rules/VSIXGallery.com.xml
Labels: new-ruleset, top-1m

#19598 Create piccy.info.xml
  src/chrome/content/rules/piccy.info.xml
Labels: new-ruleset, top-1m

#19613 Add AwesomeStuffToBuy.com.xml
  src/chrome/content/rules/AwesomeStuffToBuy.com.xml
Labels: new-ruleset, top-1m

#19615 Add InternetX.com.xml
  src/chrome/content/rules/InternetX.com.xml
Labels: new-ruleset, top-1m

#19643 Add Nic.bc.ca.xml
  src/chrome/content/rules/Nic.bc.ca.xml
Labels: new-ruleset, top-1m

#19669 Create mucommander.com.xml
  src/chrome/content/rules/mucommander.com.xml
Labels: new-ruleset, top-1m

#19677 Create pqube.co.uk.xml
  src/chrome/content/rules/pqube.co.uk.xml
Labels: new-ruleset, top-1m

#19682 Add Memtest.org.xml
  src/chrome/content/rules/Memtest.org.xml
Labels: new-ruleset, top-1m

#19687 Add rules for Wikisimpsons
  src/chrome/content/rules/Wikisimpsons.xml
Labels: new-ruleset, top-1m

#19689 add cdn.cnn.com target
  src/chrome/content/rules/CNN.com.xml
Labels: top-100

#19711 Add CPlusPlus.com.xml
  src/chrome/content/rules/CPlusPlus.com.xml
Labels: new-ruleset

#19688 Update Pull Request Template to be More Helpful
  .github/PULL_REQUEST_TEMPLATE/existing_contributors.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: docs

#19738 Update Wuala.xml
  src/chrome/content/rules/Wuala.xml
Labels: ruleset-enhancement
