Repository EFForg/https-everywhere, pull requests merged in 2020-12, with the labels that each got.

#19796 Update rules for Kym-cdn.com
  src/chrome/content/rules/KYM-CDN.com.xml
Labels: ruleset-enhancement

#19739 Add goodweave.org
  src/chrome/content/rules/goodweave.org.xml
Labels: new-ruleset

#19741 Add banned.video.xml
  src/chrome/content/rules/banned.video.xml
Labels: new-ruleset, top-10k

#19745 Add AdvocateAndDemocrat.com.xml
  src/chrome/content/rules/AdvocateAndDemocrat.com.xml
Labels: new-ruleset

#19748 Add co.cumberland.nc.us.xml
  src/chrome/content/rules/co.cumberland.nc.us.xml
Labels: new-ruleset

#19750 Add 02ch.su.xml
  src/chrome/content/rules/02ch.su.xml
Labels: new-ruleset

#19765 Add CounterMail.com.xml
  src/chrome/content/rules/CounterMail.com.xml
Labels: new-ruleset

#19766 Add msgsafe.io.xml
  src/chrome/content/rules/msgsafe.io.xml
Labels: new-ruleset, top-1m

#19767 Add swissnode.ch.xml
  src/chrome/content/rules/swissnode.ch.xml
Labels: new-ruleset

#19768 Add soverin.net.xml
  src/chrome/content/rules/soverin.net.xml
Labels: new-ruleset, top-1m

#19769 Add novo-ordo.com.xml
  src/chrome/content/rules/novo-ordo.com.xml
Labels: new-ruleset

#19773 Create Gab.com.xml
  src/chrome/content/rules/Gab.com.xml
Labels: new-ruleset, top-100k, top-10k

#19790 Update Tianya.cn
  src/chrome/content/rules/tianya.cn-mixedcontent.xml
  src/chrome/content/rules/tianya.cn.xml
Labels: china, ruleset-enhancement, top-100

#19691 Create Blogto.com.xml
  src/chrome/content/rules/Blogto.com.xml
Labels: new-ruleset, top-100k, top-10k

#19792 Ministry of Interior of the Slovak Republic
  src/chrome/content/rules/MINV.sk.xml
Labels: new-ruleset, top-100k

#19800 Create theindigokitchen.com.xml
  src/chrome/content/rules/theindigokitchen.com.xml
Labels: new-ruleset

#19809 Create Sharesight.com.xml
  src/chrome/content/rules/Shareshight.com.xml
Labels: top-100k

#19804 Add rules for Intertwingly.net
  src/chrome/content/rules/Intertwingly.net.xml
Labels: new-ruleset, top-1m

#19813 Create playphrase.me.xml
  src/chrome/content/rules/playphrase.me.xml
Labels: top-1m

#19817 Create geacron.com.xml
  src/chrome/content/rules/geacron.com.xml
Labels: top-1m

#19820 Create regettingold.com.xml
  src/chrome/content/rules/regettingold.com.xml
Labels: top-100k

#19822 Create acme.com.xml
  src/chrome/content/rules/acme.com.xml
Labels: top-1m

#19844 Introduce Modular CSS
  chromium/pages/base.css
  chromium/pages/main.css
  chromium/pages/options/index.html
  chromium/pages/options/style.css
  chromium/pages/popup/style.css
Labels: ui

#19849 Options UI: Adding Responsiveness
  chromium/pages/base.css
  chromium/pages/options/index.html
  chromium/pages/options/style.css
Labels: ui

#19781 Open option page in a new tab
  chromium/manifest.json
Labels: EFF, ui

#19856 Adjust CSS for Better Alignment in Options UI
  chromium/pages/options/style.css
Labels: ui
