Repository EFForg/https-everywhere, pull requests merged in 2021-04, with the labels that each got.

#20046 Fix invalid ruleset scope typings
  chromium/background-scripts/rules.js
  chromium/background-scripts/update.js
Labels: bug

#20049 DuckDuckGo Smarter Encryption Update Channel
  CONTRIBUTING.md
  LICENSE.txt
  chromium/background-scripts/update_channels.js
  chromium/test/update_test.js
  docs/adrs/bloom-filter-rule-signing.md
  docs/adrs/duckduckgo-smarter-encryption.md
  utils/sign-bloom/ddgse
  utils/sign-bloom/ddgse.json
Labels: new-ruleset, ruleset-enhancement, sign-rulesets

#19991 Fix access to undefined property `state` of type `Ruleset`
  chromium/background-scripts/rules.js
Labels: bug

#20044 Add missing default values in background.js
  chromium/background-scripts/background.js
Labels: bug

#20013 Added valgrind.org
  src/chrome/content/rules/valgrind.org.xml
Labels: new-ruleset

#20036 Added more domains to funet.fi
  src/chrome/content/rules/Funet.fi.xml
Labels: ruleset-enhancement

#20007 Added nvaccess.org
  src/chrome/content/rules/nvaccess.org.xml
Labels: new-ruleset

#20033 Added openwall.info
  src/chrome/content/rules/openwall.info.xml
Labels: new-ruleset

#20030 No longer different content on git.infradead.org
  src/chrome/content/rules/Infradead.org.xml
Labels: ruleset-enhancement

#20014 Added candelatech.com
  src/chrome/content/rules/candelatech.com.xml
Labels: new-ruleset

#20061 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs
