Repository EFForg/https-everywhere, pull requests merged in 2021-06, with the labels that each got.

#20043 Fix unexpected arithmetic operations on strings
  chromium/background-scripts/ip_utils.js
Labels: bug

#19811 Add rules for Umsmash.com
  src/chrome/content/rules/Umsmash.com.xml
Labels: new-ruleset

#19939 Create direxion.xml
  src/chrome/content/rules/direxion.xml
  utils/ruleset-allowlist.csv
Labels: new-ruleset

#20092 Amend Incognito Key for Chrome and Firefox
  chromium/manifest.json
  make.sh
Labels: EASE, chrome, firefox
