Repository EFForg/https-everywhere, pull requests merged in 2021-02, with the labels that each got.

#19907 Hotfix: Amend Google.tld_Subdomains.xml Cookie Rule
  src/chrome/content/rules/Google.tld_Subdomains.xml
Labels: chrome

#19912 Create imgburn.com.xml
  src/chrome/content/rules/imgburn.com.xml
Labels: new-ruleset

#19931 [Ruleset] Add More Coverage for Google.tld_Subdomains.xml
  src/chrome/content/rules/Google.tld_Subdomains.xml
  utils/ruleset-allowlist.csv
Labels: enhancement

#19914 Add radentscheid-frankfurt.de
  src/chrome/content/rules/Radentscheid-frankfurt.de.xml
Labels: new-ruleset

#19913 uschovna.cz
  src/chrome/content/rules/Uschovna.cz.xml
Labels: new-ruleset

#19918 Create trust.org.xml
  src/chrome/content/rules/trust.org.xml
Labels: new-ruleset

#19915 Update SONGLYRICS.com.xml
  src/chrome/content/rules/SONGLYRICS.com.xml
Labels: ruleset-enhancement

#19920 Freefilm.to
  src/chrome/content/rules/Freefilm.to.xml
Labels: new-ruleset

#19919 Sashe.sk
  src/chrome/content/rules/Sashe.sk.xml
Labels: new-ruleset
