Repository EFForg/https-everywhere, pull requests merged in 2021-03, with the labels that each got.

#19926 Create quakelive.com.xml
  src/chrome/content/rules/quakelive.com.xml
Labels: new-ruleset

#19930 Add rules for Yiwutaro.com
  src/chrome/content/rules/yiwutaro.com.xml
Labels: new-ruleset

#19935 Create onlineprospectus.net.xml
  src/chrome/content/rules/onlineprospectus.net.xml
Labels: new-ruleset

#19936 Create glest.org.xml
  src/chrome/content/rules/glest.org.xml
Labels: new-ruleset

#19937 Update wz2100.net.xml
  src/chrome/content/rules/Warzone2100.xml
  src/chrome/content/rules/wz2100.net.xml
Labels: ruleset-enhancement

#19940 Create edens.com.xml
  src/chrome/content/rules/edens.com.xml
Labels: new-ruleset

#19941 Update naver.com.xml
  src/chrome/content/rules/Naver.com.xml
  src/chrome/content/rules/Naver_Corp.com.xml
  src/chrome/content/rules/naver.com.xml
Labels: ruleset-enhancement

#19942 Update daum.net.xml
  src/chrome/content/rules/Daum_Communications.xml
  src/chrome/content/rules/daum.net.xml
Labels: ruleset-enhancement

#19932 Create jiri-dvorak.cz.xml
  src/chrome/content/rules/jiri-dvorak.cz.xml
Labels: new-ruleset

#19848 Create cppc.ca.xml
  src/chrome/content/rules/cppc.ca.xml
Labels: new-ruleset

#19933 Create yvt.jp.xml
  src/chrome/content/rules/yvt.jp.xml
Labels: new-ruleset

#13559 Re-enable MSDN.xml
  src/chrome/content/rules/MSDN.xml
Labels: needs revision, top-100

#19910 Adding bloom-filter based redirects
  chromium/background-scripts/background.js
  chromium/background-scripts/update.js
  chromium/background-scripts/util.js
  chromium/background-scripts/wasm.js
  chromium/pages/options/ux.js
  chromium/pages/popup/ux.js
  utils/sign-bloom/add_timestamp.py
  utils/sign-bloom/async-airgap.sh
  utils/sign-bloom/async-request.sh
  utils/sign-bloom/standalone.sh
  utils/sign-rulesets/async-airgap.sh
Labels: enhancement

#19929 Create thedarkmod.com.xml
  src/chrome/content/rules/The_Dark_Mod.com.xml
  src/chrome/content/rules/thedarkmod.com.xml
Labels: new-ruleset

#19860 Create sunxdcc.com.xml
  src/chrome/content/rules/sunxdcc.com.xml
Labels: new-ruleset

#19961 Create uhrp.org.xml
  src/chrome/content/rules/uhrp.org.xml
Labels: new-ruleset

#19975 Create robinhood.xml
  src/chrome/content/rules/robinhood.xml
Labels: new-ruleset

#19987 [REFACTOR] Move to Python 3
  browser-dist/edge.sh
  browser-dist/opera.sh
  docs/en_US/ruleset-update-channels.md
  hooks/precommit
  install-dev-dependencies.sh
  make.sh
  test/chromium.sh
  test/fetch.sh
  test/firefox.sh
  test/manual.sh
  test/rules/src/https_everywhere_checker/check_rules.py
  test/script.py
  test/validations.sh
  test/validations/filename/run.py
  test/validations/relaxng/run.py
  test/validations/securecookie/run.py
  test/validations/special/duplicate-allowlist-cleanup.sh
  test/validations/special/run.py
  test/validations/test-coverage/run.sh
  utils/chromium-translations.py
  utils/create-platform-certs/create_platform_certs.sh
  utils/create-platform-certs/split_combined_cert_file.py
  utils/create_zip.py
  utils/merge-rulesets.py
  utils/setversion.py
  utils/standalone-translations.py
  utils/zipfile_deterministic.py
Labels: performance, toolchain
