Repository EFForg/https-everywhere, pull requests merged in 2021-05, with the labels that each got.

#19993 Create Fantia.jp.xml
  src/chrome/content/rules/Fantia.jp.xml
Labels: top-10k

#20005 Add S.to.xml
  src/chrome/content/rules/S.to.xml
Labels: top-10k

#20004 Create radio.garden.xml
  src/chrome/content/rules/radio.garden.xml
Labels: needs revision, top-100k

#20034 Added more domains to NaverCorp
  src/chrome/content/rules/Naver_Corp.com.xml
Labels: top-100k

#20035 Added jaist.ac.jp
  src/chrome/content/rules/jaist.ac.jp.xml
Labels: top-1m
