Repository EFForg/https-everywhere, pull requests merged in 2021-01, with the labels that each got.

#19884 Create bitlaunch.io.xml
  src/chrome/content/rules/bitlaunch.io.xml
Labels: new-ruleset, owner

#19868 Fix chromium-driver for Debian 10+; Use firefox-esr instead of iceweasel
  install-dev-dependencies.sh
Labels: toolchain

#19633 Add gvt1.com.xml
  src/chrome/content/rules/gvt1.com.xml
Labels: new-ruleset

#19878 Update test/setup_travis.sh
  test/setup_travis.sh
Labels: toolchain

#19876 Create CodecGuide.com.xml
  src/chrome/content/rules/CodecGuide.com.xml
Labels: new-ruleset

#19891 Create bjoernkarmann.dk.xml
  src/chrome/content/rules/bjoernkarmann.dk.xml
Labels: new-ruleset

#19886 Create host4coins.net.xml
  src/chrome/content/rules/host4coins.net.xml
Labels: new-ruleset

#19874 Fail2ban.org.xml: Add missing target
  src/chrome/content/rules/Fail2ban.org.xml
Labels: ruleset-enhancement

#19729 Create RTHK.hk.xml
  src/chrome/content/rules/RTHK.hk.xml
  src/chrome/content/rules/RTHK.org.hk.xml
Labels: new-ruleset, top-10k, top-1m

#19712 Add ruleset secouchermoinsbete
  src/chrome/content/rules/secouchermoinsbete.fr.xml
Labels: new-ruleset

#19736 Add ruleset for skbbank.ru
  src/chrome/content/rules/skbbank.ru.xml
Labels: new-ruleset, top-1m

#19831 Create MeWe.com.xml
  src/chrome/content/rules/MeWe.com.xml
Labels: new-ruleset, top-1k

#19832 Create Knexjs.org.xml
  src/chrome/content/rules/Knexjs.org.xml
Labels: new-ruleset, top-1m

#19833 Update PocketMatrix.com.xml
  src/chrome/content/rules/PocketMatrix.com.xml
Labels: ruleset-enhancement

#19829 Emphasize temporary exceptions in EASE mode, fix #18970
  chromium/external/README.md
  chromium/package-lock.json
  chromium/package.json
  chromium/pages/base.css
  chromium/pages/cancel/index.html
  chromium/pages/cancel/style.css
  chromium/pages/cancel/ux.js
  chromium/pages/main.css
  src/chrome/locale/en/https-everywhere.dtd
Labels: EASE, ui

#19835 Europe miniatures.com.xml
  src/chrome/content/rules/Europe_Miniatures.xml
  src/chrome/content/rules/europe-miniatures.com.xml
Labels: ruleset-enhancement

#19836 Update Joomlancers.com.xml
  src/chrome/content/rules/Joomlancers.com.xml
Labels: ruleset-enhancement

#19837 Create marketingautomation-linz.de.xml
  src/chrome/content/rules/marketingautomation-linz.de.xml
Labels: new-ruleset

#19839 Update LondonStockExchange.com.xml
  src/chrome/content/rules/London-Stock-Exchange.xml
  src/chrome/content/rules/LondonStockExchange.com.xml
Labels: ruleset-enhancement, top-100k

#19840 Create esp8266.com.xml
  src/chrome/content/rules/esp8266.com.xml
Labels: new-ruleset, top-100k

#19892 Enable coin.space.xml
  src/chrome/content/rules/coin.space.xml
Labels: ruleset-enhancement, top-1m

#19657 Update regex in trivialize-cdn-rules
  utils/trivialize-cdn-rules/index.js
Labels: toolchain

#19873 Create wclc.com.xml
  src/chrome/content/rules/wclc.com.xml
Labels: new-ruleset, top-1m

#19872 Add CashTravel.info.xml
  src/chrome/content/rules/CashTravel.info.xml
Labels: new-ruleset, top-100k

#19857 Create dev47apps.com.xml
  src/chrome/content/rules/dev47apps.com.xml
Labels: new-ruleset, top-100k

#19875 Create naturedestinations.ca.xml
  src/chrome/content/rules/naturedestinations.ca.xml
Labels: new-ruleset

#19895 Create hkcnews.com.xml
  src/chrome/content/rules/hkcnews.com.xml
Labels: new-ruleset

#19861 Create amule.org.xml
  src/chrome/content/rules/amule.org.xml
Labels: new-ruleset

#19882 Create mtv.com.xml
  src/chrome/content/rules/mtv.com.xml
Labels: new-ruleset, top-10k

#19901 Create hkstockadr.com.xml
  src/chrome/content/rules/hkstockadr.com.xml
Labels: new-ruleset

#19862 Create chomikuj.pl.xml
  src/chrome/content/rules/chomikuj.pl.xml
  src/chrome/content/rules/static-chomikuj.pl.xml
Labels: new-ruleset, top-10k

#19904 Create nasdaqtrader.com.xml
  src/chrome/content/rules/nasdaqtrader.com.xml
Labels: new-ruleset

#19908 Update NPM Dependency
  utils/labeller/package-lock.json
  utils/labeller/package.json
Labels: high priority, toolchain

#19610 Add OMC.net.xml
  src/chrome/content/rules/OMC.net.xml
Labels: new-ruleset

#19540 Re-enabled OSU Foundation
  src/chrome/content/rules/osufoundation.org.xml
Labels: ruleset-enhancement

#19863 Create filediva.com.xml
  src/chrome/content/rules/filediva.com.xml
Labels: new-ruleset

#19805 Bratislava public transport
  src/chrome/content/rules/DPB.sk.xml
  src/chrome/content/rules/Ubian.sk.xml
Labels: new-ruleset

#19854 Zoznam.sk
  src/chrome/content/rules/Topky.sk.xml
  src/chrome/content/rules/Zoznam.sk.xml
Labels: new-ruleset, top-10k

#19853 Slovak universities
  src/chrome/content/rules/EUBA.sk.xml
  src/chrome/content/rules/STUBA.sk.xml
  src/chrome/content/rules/TRUNI.sk.xml
  src/chrome/content/rules/TUKE.sk.xml
  src/chrome/content/rules/TUZVO.sk.xml
  src/chrome/content/rules/UNIBA.sk.xml
  src/chrome/content/rules/UNIPO.sk.xml
  src/chrome/content/rules/UNIZA.sk.xml
Labels: new-ruleset, top-1m

#19846 Slovak Goverment updates
  src/chrome/content/rules/SlovakGovernment.xml
Labels: ruleset-enhancement

#19845 Slovensko.digital
  src/chrome/content/rules/Slovensko.digital.xml
Labels: new-ruleset

#19847 IWPR.net
  src/chrome/content/rules/IWPR.net.xml
Labels: new-ruleset

#19842 Create flippfly.com.xml
  src/chrome/content/rules/flippfly.com.xml
Labels: new-ruleset

#19855 KSH: Add exclusion for /Statinfo/
  src/chrome/content/rules/KSH.xml
Labels: ruleset-bug
